#pragma once

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamBackend, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamNotifications, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamUserSlots, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamRequestTracker, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamEditor, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamRuntime, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamContent, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamMicroservices, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamStats, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamLobby, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamMatchmaking, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamStore, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamParty, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamFriend, Log, All);

BEAMABLECORE_API DECLARE_LOG_CATEGORY_EXTERN(LogBeamCli, Log, All);
