// Copyright Beamable, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Farming/FarmTypes.h"
#include "BeamPlantData.h"
#include "BeamSeedData.h"
#include "BeamBackend/SemanticTypes/BeamContentId.h"
#include "Collectible/BeamFarmCollectibleActor.h"
#include "AutoGen/SubSystems/BeamBeamFarmMsApi.h"
#include "AutoGen/SubSystems/BeamFarmMs/BeamFarmMsGetGroundItemsRequest.h"
#include "AutoGen/SubSystems/BeamFarmMs/BeamFarmMsGetSlotStatesRequest.h"
#include "AutoGen/SubSystems/BeamFarmMs/BeamFarmMsGetPlayerLevelRequest.h"
#include "AutoGen/GroundItemEntry.h"
#include "AutoGen/SlotStateEntry.h"
#include "AutoGen/GetPlayerLevelResult.h"
#include "Runtime/BeamRuntime.h"
#include "BeamFarmSubsystem.generated.h"

class UBeamContentSubsystem;
class AFarmSlotActor;

DECLARE_DELEGATE_TwoParams(FOnBeamFarmCallResult, bool /*bSuccess*/, const FString& /*PayloadOrError*/);

// ─── Slot interaction delegates (AFarmSlotActor subscribes) ──────────────────

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSlotShouldPlant,
                                               const FString&, SlotId,
                                               const FBeamSeedData&, SeedData,
                                               const FBeamPlantData&, PlantData);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmSlotShouldHarvest, const FString&, SlotId);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmSlotShouldCancelPlant, const FString&, SlotId);

// ─── Player level data ────────────────────────────────────────────────────────

USTRUCT(BlueprintType)
struct BEAMPROJ_BEAMFARM_API FBeamFarmPlayerLevelData
{
	GENERATED_BODY()

	// Current player level (0-based).
	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Level")
	int32 Level = 0;

	// Total XP accumulated.
	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Level")
	int32 TotalXp = 0;

	// XP needed to complete the current level (i.e. reach the next one).
	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Level")
	int32 XpForCurrentLevel = 0;

	// XP earned so far within the current level.
	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Level")
	int32 XpIntoCurrentLevel = 0;

	// Progress through the current level in [0, 1]. Returns 1 at max level.
	
	float GetProgress()
	{
		if (XpForCurrentLevel <= 0) return 1.f;
		return FMath::Clamp((float)XpIntoCurrentLevel / (float)XpForCurrentLevel, 0.f, 1.f);
	}
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnBeamFarmPlayerLevelUp,
                                             int32, OldLevel,
                                             int32, NewLevel);

DECLARE_DYNAMIC_DELEGATE_ThreeParams(FOnPlayerLevelRefreshed, bool, bSuccess, int32, OldLevel, int32, NewLevel);

// ─── Collectible spawner delegates (UFarmCollectibleSpawner subscribes) ───────

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSpawnerCollectibleSpawned,
                                               const FString&, SpawnerId,
                                               ABeamFarmCollectibleActor*, Collectible,
                                               const FTransform&, SpawnTransform);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSpawnerCollectibleCollected,
                                               const FString&, SpawnerId,
                                               APawn*, Collector,
                                               const FBeamFarmCollectibleInfo&, Info);

// ─── Spawn configuration ──────────────────────────────────────────────────────
// Passed from UFarmCollectibleSpawner::BeginPlay to UBeamFarmSubsystem::RegisterSpawner.
// Carries the complete designer-authored configuration for one spawner.

USTRUCT(BlueprintType)
struct BEAMPROJ_BEAMFARM_API FBeamFarmSpawnConfig
{
	GENERATED_BODY()

	// Unique identifier for this spawner. Generated by UFarmCollectibleSpawner if left empty.
	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FString SpawnerId;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	EBeamFarmSpawnMode SpawnMode = EBeamFarmSpawnMode::FixedTransforms;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TSubclassOf<ABeamFarmCollectibleActor> CollectibleClass;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 QuantityPerCollectible = 1;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float SpawnIntervalSeconds = 30.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 MaxActiveCollectibles = 5;

	// ── FixedTransforms ────────────────────────────────────────────────────

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FBeamSeedData MaterialData;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FString SeedMaterialContentId;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FTransform> SpawnTransforms;

	// ── WeightedZones ──────────────────────────────────────────────────────

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamContentId> PlantContentIds;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamFarmSpawnZone> SpawnZones;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamFarmExclusionZone> ExclusionZones;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FVector2D BaseAreaCenter = FVector2D::ZeroVector;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FVector2D BaseAreaHalfExtents = FVector2D(500.f, 500.f);

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float SpawnZ = 0.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float MinSpawnSeparation = 80.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 MaxSpawnAttempts = 20;
};

// ─── Internal per-spawner runtime state ──────────────────────────────────────
// Not a USTRUCT — plain C++ struct used only inside UBeamFarmSubsystem.

struct FBeamFarmSpawnerRuntime
{
	int32 NextSpawnIndex = 0;
	TArray<TWeakObjectPtr<ABeamFarmCollectibleActor>> ActiveCollectibles;
};

// ─── Internal per-slot grow state ────────────────────────────────────────────
// Tracks growing slots so UBeamFarmSubsystem can centrally poll grow completion.

struct FBeamFarmSlotGrowState
{
	TWeakObjectPtr<AFarmSlotActor> SlotActor;
	float PlantedWorldSeconds = 0.f;
	float GrowDurationSeconds = 0.f;
};

UCLASS()
class BEAMPROJ_BEAMFARM_API UBeamFarmSubsystem : public UGameInstanceSubsystem
{
	GENERATED_BODY()

public:
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;
	virtual void Deinitialize() override;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BeamFarm")
	FString UserSlotName = TEXT("Player0");

	// ─── Backend calls ──────────────────────────────────────────────────────

	void PlantSeed(const FString& SeedContentId, const FString& SlotId, const FOnBeamFarmCallResult& OnResult);
	void CollectHarvest(const FString& SlotId, const FOnBeamFarmCallResult& OnResult);

	void RegisterGroundItem(const FBeamFarmGroundItemParams& Params, const FOnBeamFarmCallResult& OnResult);
	void CollectGroundItem(const FString& GroundItemId, const FOnBeamFarmCallResult& OnResult);

	// Fetches active ground items for a spawner from the backend, then spawns actors at their
	// saved positions. Called automatically by StartSpawner before the spawn timer begins.
	void GetGroundItems(const FString& SpawnerId, TFunction<void(bool, TArray<UGroundItemEntry*>)> OnComplete);

	// Applies modifier items to an existing plant item, changing its properties according to
	// the content-defined deltas. Each entry in ModifierContentIds consumes one unit of that
	// modifier currency.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	void MutateWithModifiers(const FString& PlantItemContentId, int64 PlantItemInstanceId, const TArray<FString>& ModifierContentIds);

	// ─── Slot grow tracking ─────────────────────────────────────────────────
	// Called by AFarmSlotActor so the subsystem tick can centrally check grow
	// completion and call MarkReadyToHarvest() when the duration has elapsed.

	void NotifySlotPlanted(const FString& SlotId, AFarmSlotActor* SlotActor, float GrowDurationSeconds);
	void NotifySlotCleared(const FString& SlotId);

	// ─── Slot actor registry ─────────────────────────────────────────────────
	// AFarmSlotActor registers itself in BeginPlay so the subsystem can restore
	// slot states from the backend after the Beamable user signs in.

	void RegisterSlotActor(const FString& SlotId, AFarmSlotActor* Actor);
	void UnregisterSlotActor(const FString& SlotId);

	// ─── Farming selection state ────────────────────────────────────────────────

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	EFarmingInteractionState FarmingState = EFarmingInteractionState::Idle;

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	FBeamSeedData SelectedCrop;

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	FString SelectedCropContentId;

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void SetSelectedCrop(const FBeamSeedData& SeedData);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	bool SetSelectedCropBySeedId(const FString& SeedItemContentId);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void ClearSelectedCrop();

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Farming")
	bool HasSelectedCrop() const;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Slot")
	FOnBeamFarmSlotShouldPlant OnSlotShouldPlant;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Slot")
	FOnBeamFarmSlotShouldHarvest OnSlotShouldHarvest;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Slot")
	FOnBeamFarmSlotShouldCancelPlant OnSlotShouldCancelPlant;

	// ─── Farming interaction ────────────────────────────────────────────────

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void HandleSlotInteraction(const FBeamFarmInteractionRequest& Request);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	bool FindSeedData(const FString& SeedContentId, FBeamSeedData& OutData);

	bool ResolveRandomPlantData(const TArray<FBeamContentId>& PlantContentIds, FBeamPlantData& OutData, FString& OutContentId);

	// ─── Content helpers ────────────────────────────────────────────────────

	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	TArray<FBeamPlantData> GetAllPlants();

	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	bool FindPlantBySeedId(const FString& PlantContentId, FBeamPlantData& OutData);

	// ─── Collectible spawner management ────────────────────────────────────
	// Called by UFarmCollectibleSpawner in BeginPlay / EndPlay. The component is
	// a data holder; the subsystem owns all timer and actor lifecycle behavior.

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void RegisterSpawner(const FBeamFarmSpawnConfig& Config);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void UnregisterSpawner(const FString& SpawnerId);

	// Starts the spawn timer for an already-registered spawner (e.g. after calling StopSpawner).
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void StartSpawner(const FString& SpawnerId);

	// Pauses spawning without unregistering (ActiveCollectibles remain alive).
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void StopSpawner(const FString& SpawnerId);

	// Force-spawns one collectible for the given spawner, ignoring the MaxActiveCollectibles cap.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void SpawnCollectibleForSpawner(const FString& SpawnerId);

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Spawner")
	FOnBeamFarmSpawnerCollectibleSpawned OnSpawnerCollectibleSpawned;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Spawner")
	FOnBeamFarmSpawnerCollectibleCollected OnSpawnerCollectibleCollected;
	
	// ─── Delivery ───────────────────────────────────────────────────────────

	// Fetches the player's active delivery orders from the server, auto-filling up
	// to MaxActiveOrders if needed.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void GetDeliveryOrders();

	// Explicitly asks the server to fill the player's delivery order slots up to
	// MaxActiveOrders. Useful on first login or after consuming orders rapidly.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void FillDeliveryOrders();

	// Attempts to fulfil the given order using the specified inventory item instance.
	// ItemInstanceId is the Beamable item instance ID (int64) obtained from the
	// player's inventory.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void DeliverOrder(const FString& OrderId, int64 ItemInstanceId);

	// ─── Research ───────────────────────────────────────────────────────────

	// Begins researching the specified item. Research parameters (cost, duration, output)
	// are read from the plant's itemplant content — no separate project needed.
	// Deducts research points and writes state as item properties (new instance ID assigned).
	// Refresh inventory after success.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Research")
	void StartResearch(int64 ItemInstanceId, const FString& ItemContentId);

	// Collects completed research for the specified item instance, granting the output reward.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Research")
	void CollectResearch(int64 ItemInstanceId, const FString& ItemContentId);

	// Property key constants — use these to filter inventory items that are currently in research.
	// An item is in research when it has the "research_started_at" property set.
	UFUNCTION(BlueprintPure, Category = "BeamFarm|Research")
	static FString GetResearchStartedAtKey() { return TEXT("research_started_at"); }

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Research")
	static FString GetResearchDurationKey() { return TEXT("research_duration_secs"); }

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Research")
	static FString GetResearchOutputContentIdKey() { return TEXT("research_output_content_id"); }

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Research")
	static FString GetResearchOutputQuantityKey() { return TEXT("research_output_quantity"); }

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Research")
	static FString GetResearchOutputTypeKey() { return TEXT("research_output_type"); }

	// ─── Player level ───────────────────────────────────────────────────────

	// Last fetched level data. Valid after the first successful GetPlayerLevel call.
	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Level")
	FBeamFarmPlayerLevelData CachedPlayerLevel;

	// Fetches the player's level and XP from the backend and updates CachedPlayerLevel.
	// Broadcasts OnPlayerLevelUp if the new level is higher than the cached one.
	// Also broadcasts OnPlayerLevelRefreshed after every successful fetch.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Level")
	void RefreshPlayerLevel(const FOnPlayerLevelRefreshed& OnComplete);

	// Broadcast after every successful RefreshPlayerLevel call.
	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Level")
	FOnBeamFarmPlayerLevelUp OnPlayerLevelUp;

private:
	UPROPERTY()
	TObjectPtr<UBeamBeamFarmMsApi> BeamFarmMsApi;

	UPROPERTY()
	TObjectPtr<UBeamContentSubsystem> ContentSubsystem;

	// Spawn config keyed by SpawnerId. UPROPERTY so TSubclassOf<> inside is GC-safe.
	UPROPERTY()
	TMap<FString, FBeamFarmSpawnConfig> SpawnerConfigs;

	// Runtime state (active actors + round-robin index) per spawner. Plain C++ — uses weak ptrs.
	TMap<FString, FBeamFarmSpawnerRuntime> SpawnerRuntimes;

	// Timer handle per spawner. Cleared on UnregisterSpawner / StopSpawner.
	TMap<FString, FTimerHandle> SpawnTimers;

	// Growing slot registry — polled every second by GrowCheckTimerHandle.
	TMap<FString, FBeamFarmSlotGrowState> GrowingSlots;
	FTimerHandle GrowCheckTimerHandle;

	// True once the Beamable user has signed in and the API is usable.
	bool bUserReady = false;

	// Spawner IDs that arrived before the user was ready; flushed in HandleUserReady.
	TArray<FString> PendingStartSpawnerIds;

	// Slot actors that registered themselves in BeginPlay, keyed by SlotId.
	TMap<FString, TWeakObjectPtr<AFarmSlotActor>> SlotActors;

	FDelegateHandle UserReadyHandle;

	UBeamBeamFarmMsApi* GetApi();
	UBeamContentSubsystem* GetContentSub();

	void SetFarmingState(EFarmingInteractionState NewState);

	// Fired by UBeamRuntime when the user has finished signing in.
	void HandleUserReady(const FUserSlot& Slot);

	void OnSpawnTimer(FString SpawnerId);
	void StartSpawnTimer(const FString& SpawnerId);
	void RestoreGroundItemsForSpawner(const FString& SpawnerId, const TArray<UGroundItemEntry*>& SavedItems);
	void CheckGrowingSlots();

	bool TryPickSpawnPointForSpawner(const FString& SpawnerId, FVector& OutLocation);

	// Fetches slot states from the backend and restores slot actor visuals + grow timers.
	void GetSlotStates(const TArray<FString>& SlotIds, TFunction<void(bool, TArray<USlotStateEntry*>)> OnComplete);
	void RestoreSlotStates();

	UFUNCTION()
	void HandleCollectiblePickedUp(ABeamFarmCollectibleActor* Collectible, APawn* Collector);
};
