// Copyright Beamable, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Farming/FarmTypes.h"
#include "BeamPlantData.h"
#include "BeamSeedData.h"
#include "BeamBackend/SemanticTypes/BeamContentId.h"
#include "Collectible/BeamFarmCollectibleActor.h"
#include "AutoGen/SubSystems/BeamBeamFarmMsApi.h"
#include "BeamFarmSubsystem.generated.h"

class UBeamContentSubsystem;

DECLARE_DELEGATE_TwoParams(FOnBeamFarmCallResult, bool /*bSuccess*/, const FString& /*PayloadOrError*/);

// ─── Mutation delegates ───────────────────────────────────────────────────────

// Fired when MutateWithModifiers completes — carries the updated item properties.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmMutationCompleted, const FBeamFarmMutationResult&, Result);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmMutationFailed, const FString&, Error);

// ─── Delivery delegates ───────────────────────────────────────────────────────

// Fired when GetDeliveryOrders completes — carries the full list of active orders.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmDeliveryOrdersReceived,
                                            const TArray<FBeamDeliveryOrderInfo>&, Orders);

// Fired when DeliverOrder completes successfully.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmDeliveryCompleted,
                                               const FString&, OrderId,
                                               const FString&, RewardCurrencyId,
                                               int32, RewardAmount);

// Fired when DeliverOrder or GetDeliveryOrders fails.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnBeamFarmDeliveryFailed,
                                             const FString&, OrderId,
                                             const FString&, ErrorMessage);

// ─── Slot interaction delegates (AFarmSlotActor subscribes to these) ──────────

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSlotShouldPlant,
                                               const FString&, SlotId,
                                               const FBeamSeedData&, SeedData,
                                               const FBeamPlantData&, PlantData);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmSlotShouldHarvest, const FString&, SlotId);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmSlotShouldCancelPlant, const FString&, SlotId);

// ─── Farming state delegate ───────────────────────────────────────────────────

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBeamFarmFarmingStateChanged, EFarmingInteractionState, NewState);

// ─── Farming result delegates ─────────────────────────────────────────────────

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnBeamFarmSeedConsumed, const FString&, SeedContentId, int32, Quantity);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmItemsHarvested, const FString&, SlotId, const FString&, ItemContentId, int32, Quantity);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnBeamFarmPlantFailed, const FString&, SlotId, const FString&, ErrorMessage);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnBeamFarmCollectFailed, const FString&, SlotId, const FString&, ErrorMessage);

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnBeamFarmNoCropSelected);

// ─── Collectible spawner delegates (UFarmCollectibleSpawner subscribes, filtered by SpawnerId) ──

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSpawnerCollectibleSpawned,
                                               const FString&, SpawnerId,
                                               ABeamFarmCollectibleActor*, Collectible,
                                               const FTransform&, SpawnTransform);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBeamFarmSpawnerCollectibleCollected,
                                               const FString&, SpawnerId,
                                               APawn*, Collector,
                                               const FBeamFarmCollectibleInfo&, Info);

// ─── Spawn configuration ──────────────────────────────────────────────────────
// Passed from UFarmCollectibleSpawner::BeginPlay to UBeamFarmSubsystem::RegisterSpawner.
// Carries the complete designer-authored configuration for one spawner.

USTRUCT(BlueprintType)
struct BEAMPROJ_BEAMFARM_API FBeamFarmSpawnConfig
{
	GENERATED_BODY()

	// Unique identifier for this spawner. Generated by UFarmCollectibleSpawner if left empty.
	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FString SpawnerId;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	EBeamFarmSpawnMode SpawnMode = EBeamFarmSpawnMode::FixedTransforms;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TSubclassOf<ABeamFarmCollectibleActor> CollectibleClass;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 QuantityPerCollectible = 1;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float SpawnIntervalSeconds = 30.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 MaxActiveCollectibles = 5;

	// ── FixedTransforms ────────────────────────────────────────────────────

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FBeamSeedData MaterialData;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FString SeedMaterialContentId;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FTransform> SpawnTransforms;

	// ── WeightedZones ──────────────────────────────────────────────────────

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamContentId> PlantContentIds;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamFarmSpawnZone> SpawnZones;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	TArray<FBeamFarmExclusionZone> ExclusionZones;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FVector2D BaseAreaCenter = FVector2D::ZeroVector;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	FVector2D BaseAreaHalfExtents = FVector2D(500.f, 500.f);

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float SpawnZ = 0.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	float MinSpawnSeparation = 80.f;

	UPROPERTY(BlueprintReadWrite, Category = "BeamFarm|Spawner")
	int32 MaxSpawnAttempts = 20;
};

// ─── Internal per-spawner runtime state ──────────────────────────────────────
// Not a USTRUCT — plain C++ struct used only inside UBeamFarmSubsystem.

struct FBeamFarmSpawnerRuntime
{
	int32 NextSpawnIndex = 0;
	TArray<TWeakObjectPtr<ABeamFarmCollectibleActor>> ActiveCollectibles;
};

UCLASS()
class BEAMPROJ_BEAMFARM_API UBeamFarmSubsystem : public UGameInstanceSubsystem
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BeamFarm")
	FString UserSlotName = TEXT("Player0");

	// ─── Backend calls ──────────────────────────────────────────────────────

	void PlantSeed(const FString& SeedContentId, const FString& SlotId, const FOnBeamFarmCallResult& OnResult);
	void CollectHarvest(const FString& SlotId, const FOnBeamFarmCallResult& OnResult);

	void RegisterGroundItem(const FBeamFarmGroundItemParams& Params, const FOnBeamFarmCallResult& OnResult);
	void CollectGroundItem(const FString& GroundItemId, const FOnBeamFarmCallResult& OnResult);

	// Applies modifier items to an existing plant item, changing its properties according to
	// the content-defined deltas. Each entry in ModifierContentIds consumes one unit of that
	// modifier currency. Broadcasts OnMutationCompleted or OnMutationFailed when done.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	void MutateWithModifiers(const FString& PlantItemContentId, int64 PlantItemInstanceId, const TArray<FString>& ModifierContentIds);

	// ─── Farming selection state ────────────────────────────────────────────────

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	EFarmingInteractionState FarmingState = EFarmingInteractionState::Idle;

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	FBeamSeedData SelectedCrop;

	UPROPERTY(BlueprintReadOnly, Category = "BeamFarm|Farming")
	FString SelectedCropContentId;

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void SetSelectedCrop(const FBeamSeedData& SeedData);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	bool SetSelectedCropBySeedId(const FString& SeedItemContentId);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void ClearSelectedCrop();

	UFUNCTION(BlueprintPure, Category = "BeamFarm|Farming")
	bool HasSelectedCrop() const;

	// ─── Farming interaction ────────────────────────────────────────────────

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	void HandleSlotInteraction(const FBeamFarmInteractionRequest& Request);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Farming")
	bool FindSeedData(const FString& SeedContentId, FBeamSeedData& OutData);

	bool ResolveRandomPlantData(const TArray<FBeamContentId>& PlantContentIds, FBeamPlantData& OutData, FString& OutContentId);

	// ─── Content helpers ────────────────────────────────────────────────────

	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	TArray<FBeamPlantData> GetAllPlants();

	UFUNCTION(BlueprintCallable, Category = "BeamFarm")
	bool FindPlantBySeedId(const FString& PlantContentId, FBeamPlantData& OutData);

	// ─── Collectible spawner management ────────────────────────────────────
	// Called by UFarmCollectibleSpawner in BeginPlay / EndPlay. The component is
	// a data holder; the subsystem owns all timer and actor lifecycle behavior.

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void RegisterSpawner(const FBeamFarmSpawnConfig& Config);

	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void UnregisterSpawner(const FString& SpawnerId);

	// Starts the spawn timer for an already-registered spawner (e.g. after calling StopSpawner).
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void StartSpawner(const FString& SpawnerId);

	// Pauses spawning without unregistering (ActiveCollectibles remain alive).
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void StopSpawner(const FString& SpawnerId);

	// Force-spawns one collectible for the given spawner, ignoring the MaxActiveCollectibles cap.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Spawner")
	void SpawnCollectibleForSpawner(const FString& SpawnerId);

	// ─── Slot interaction delegates ─────────────────────────────────────────

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmSlotShouldPlant OnSlotShouldPlant;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmSlotShouldHarvest OnSlotShouldHarvest;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmSlotShouldCancelPlant OnSlotShouldCancelPlant;

	// ─── Farming result delegates ───────────────────────────────────────────

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmSeedConsumed OnSeedConsumed;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmItemsHarvested OnItemsHarvested;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmPlantFailed OnPlantFailed;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmCollectFailed OnCollectFailed;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmNoCropSelected OnNoCropSelected;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Farming")
	FOnBeamFarmFarmingStateChanged OnFarmingStateChanged;

	// ─── Collectible spawner delegates ──────────────────────────────────────

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Spawner")
	FOnBeamFarmSpawnerCollectibleSpawned OnSpawnerCollectibleSpawned;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Spawner")
	FOnBeamFarmSpawnerCollectibleCollected OnSpawnerCollectibleCollected;

	// ─── Mutation delegates ─────────────────────────────────────────────────

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm")
	FOnBeamFarmMutationCompleted OnMutationCompleted;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm")
	FOnBeamFarmMutationFailed OnMutationFailed;

	// ─── Delivery ───────────────────────────────────────────────────────────

	// Fetches the player's active delivery orders from the server, auto-filling up
	// to MaxActiveOrders if needed. Broadcasts OnDeliveryOrdersReceived on completion.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void GetDeliveryOrders();

	// Explicitly asks the server to fill the player's delivery order slots up to
	// MaxActiveOrders. Useful on first login or after consuming orders rapidly.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void FillDeliveryOrders();

	// Attempts to fulfil the given order using the specified inventory item instance.
	// ItemInstanceId is the Beamable item instance ID (int64) obtained from the
	// player's inventory. Broadcasts OnDeliveryCompleted or OnDeliveryFailed.
	UFUNCTION(BlueprintCallable, Category = "BeamFarm|Delivery")
	void DeliverOrder(const FString& OrderId, int64 ItemInstanceId);

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Delivery")
	FOnBeamFarmDeliveryOrdersReceived OnDeliveryOrdersReceived;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Delivery")
	FOnBeamFarmDeliveryCompleted OnDeliveryCompleted;

	UPROPERTY(BlueprintAssignable, Category = "BeamFarm|Delivery")
	FOnBeamFarmDeliveryFailed OnDeliveryFailed;

private:
	UPROPERTY()
	TObjectPtr<UBeamBeamFarmMsApi> BeamFarmMsApi;

	UPROPERTY()
	TObjectPtr<UBeamContentSubsystem> ContentSubsystem;

	// Spawn config keyed by SpawnerId. UPROPERTY so TSubclassOf<> inside is GC-safe.
	UPROPERTY()
	TMap<FString, FBeamFarmSpawnConfig> SpawnerConfigs;

	// Runtime state (active actors + round-robin index) per spawner. Plain C++ — uses weak ptrs.
	TMap<FString, FBeamFarmSpawnerRuntime> SpawnerRuntimes;

	// Timer handle per spawner. Cleared on UnregisterSpawner / StopSpawner.
	TMap<FString, FTimerHandle> SpawnTimers;

	UBeamBeamFarmMsApi* GetApi();
	UBeamContentSubsystem* GetContentSub();

	void SetFarmingState(EFarmingInteractionState NewState);

	void OnSpawnTimer(FString SpawnerId);

	bool TryPickSpawnPointForSpawner(const FString& SpawnerId, FVector& OutLocation);

	UFUNCTION()
	void HandleCollectiblePickedUp(ABeamFarmCollectibleActor* Collectible, APawn* Collector);
};
