using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Lobby;
using Beamable.Api.Autogenerated.Models;
using Beamable.Api.Autogenerated.Playerparty;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Content;
using Beamable.Common.Dependencies;
using Beamable.Server;
using Beamable.Server.Api.Leaderboards;
using Beamable.Server.Api.RealmConfig;
using Beamable.Server.Api.Stats;
using Newtonsoft.Json;
using UnityEngine;
using Lobby = Beamable.Experimental.Api.Lobbies.Lobby;

namespace Beamable.BeamballMs
{
    [FederationId("default")]
    public class DefaultFederation : IFederationId
    {
    }

    [FederationId("beamball")]
    public class BeamballFederation : IFederationId
    {
    }

    [Microservice("BeamballMs")]
    public partial class BeamballMs : Microservice, IFederatedPlayerInit<DefaultFederation>, IFederatedGameServer<BeamballFederation>
    {
        public async Promise<PlayerInitResult> CreatePlayer(Account account, Dictionary<string, string> properties)
        {
            var gamerTag = account.gamerTags[0].gamerTag;

            // Add Initial Currency and Skin
            const string defaultSkin = "items.itemskin.skin1";
            const string coinsCurrency = "currency.coins";

            // Initialize the stats and inventory that is true for ALL identities.
            var startingStats = new Dictionary<string, string>
            {
                { "player_name", "Guest User" },
                { "beamable.selected_skin", defaultSkin }
            };
            var startingInventory = new InventoryUpdateBuilder();
            startingInventory.CurrencyChange(coinsCurrency, 195);
            startingInventory.AddItem(defaultSkin, new Dictionary<string, string>());

            // Kick off tasks to fill out the appropriate starting data
            //  - Each of these functions are no-ops if the account is NOT being created with its expected identity.
            //  - This is just an example pattern for this sample; don't try to reuse it if it doesn't fit your player initialization logic.   
            await Task.WhenAll(new[]{
                CreatePlayerEmail(account, properties, startingStats, startingInventory),
                CreatePlayerSteam(account, properties, startingStats, startingInventory),
                // CreatePlayerEOS(account, properties, startingStats, startingInventory)
            });

            // Make just two requests with all the starting stats and starting inventory.
            var userAPI = AssumeNewUser(gamerTag);
            await userAPI.Services.Stats.SetStats(StatsDomainType.Client, StatsAccessType.Public, gamerTag, startingStats);
            await userAPI.Services.Inventory.Update(startingInventory);

            return new PlayerInitResult();
        }


        private async Task CreatePlayerEmail(Account account, Dictionary<string, string> properties, Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
        {
            if (account.email.HasNonEmptyValue)
            {
                var emailSplited = account.email.GetOrThrow().Split("@");
                if (emailSplited.Length > 0) outStartingStats["player_name"] =  emailSplited[0];
            }

            await Task.CompletedTask;
        }


        public async Promise<ServerInfo> CreateGameServer(Api.Autogenerated.Models.Lobby lobby)
        {
            var serverInfo = new ServerInfo();

            var isDynamicMatch = lobby.matchType.Value.id.Value.Contains("dynamic_match");

            var playerTeams = new Dictionary<string, string>();

            // If this is a dynamic match, assign players to teams here.
            // TODO: It is not considering the Party for the teams in the dynamic match.
            if (isDynamicMatch)
            {
                var lobbyPlayers = lobby.players.GetOrElse([]);
                var teamsContent = new string[] { "TeamA", "TeamB" };

                int teamIndex = 0;

                foreach (var player in lobbyPlayers)
                {
                    playerTeams.Add(player.playerId, teamsContent[teamIndex]);
                    teamIndex = (teamIndex + 1) % teamsContent.Length;
                }
            }

            // Use this function to parallelize: creating the lobby in your Orchestrator, preparing your lobby's Global Data and PlayerData dictionaries.
            await lobby.PrepareLobbyAsDedicatedServer(serverInfo,
                async l =>
                {
                    // IF the lobby is NOT a fake lobby from playmode, you should be provisioning a server.
                    var connInfo = new ServerInfo();
                    if (!l.IsLobbyFromEditorPlayMode())
                    {
                        var realmConfig = await Services.RealmConfig.GetRealmConfigSettings();

                        var gamerTags = lobby.players.Value.Select(p => long.Parse(p.playerId)).ToArray();

                        var assumedFakeLeader = AssumeNewUser(gamerTags.First());

                        string region = await lobby.GetBestRegionFromLobby(assumedFakeLeader.Services.Stats);

                        // Create the Hathora Room
                        var hathoraRoom = await CreateHathoraGameServer(realmConfig, l.lobbyId.Value, region);

                        // Start polling until its active or the initialization timed out.
                        var pollingInterval = TimeSpan.FromSeconds(1);
                        var startedAt = DateTime.Now;

                        // MaxWaitTime cannot be more than 2 minutes as the current Beamable-enforced timeout is set to 2 minutes.
                        var maxWaitTime = TimeSpan.FromSeconds(60);

                        // Spin for up-to-2-minutes and checking every "PollingInterval" for the connection to become active.
                        while (hathoraRoom.status != "active" && (DateTime.Now - startedAt).TotalSeconds < (maxWaitTime).TotalSeconds)
                        {
                            BeamableLogger.Log($"Room {l.lobbyId.Value} status: {hathoraRoom.status}");
                            await Task.Delay(pollingInterval);
                            hathoraRoom = await PollHathoraGameServer(realmConfig, l.lobbyId.Value);
                        }

                        // It took to long to provision the server.
                        if (hathoraRoom.status != "active")
                        {
                            BeamableLogger.LogError($"Failed to provision game server in time for room. ROOM_ID={l.lobbyId.Value}, LAST_HATHORA_CONN_UPDATE={JsonUtility.ToJson(hathoraRoom)}");
                            throw new MicroserviceException(503, "FAILED_TO_PROVISION_GAME_SERVER_BEFORE_TIMEOUT", JsonUtility.ToJson(hathoraRoom));
                        }

                        // Set the hathora room information as the connection string for this lobby --- the Unreal SDK has utilities to read these properties.
                        // You can always pass them via your own properties.
                        connInfo.SetConnectionString(hathoraRoom.exposedPort.host, hathoraRoom.exposedPort.port.ToString());
                    }

                    return connInfo;
                },
                _ =>
                {
                    // For this specific game, we don't need any global data computed here, but you could compute a map to play in or randomized objects or really anything.
                    return Task.FromResult(new ServerInfo());
                },
                async lp =>
                {
                    // For this game, we need to get the selected skin for each player and put them into the lobby's player data.
                    // You could compute more information such as a selected deck's information and embedded them in this dictionary.
                    // Computing things here and storing them in the lobby is a tradeoff:
                    //   - it allows the game-server to avoid fetching things once it boots up, but it increases the size of the lobby data structure.
                    //   - for most cases, this is a fine trade-off to make; but, think about your own case's specifics as you decided.
                    var data = new Dictionary<string, string>();
                    var existingSkinData = lp.tags.GetOrElse([]).FirstOrDefault(t => t.name.GetOrElse("") == "beamable.selected_skin");
                    if (existingSkinData == null)
                    {
                        var gamerTag = long.Parse(lp.playerId.Value);
                        var selectedSkin = await Services.Stats.GetStat(StatsDomainType.Client, StatsAccessType.Public, gamerTag, "beamable.selected_skin");
                        if (!string.IsNullOrEmpty(selectedSkin))
                        {
                            data["beamable.selected_skin"] = selectedSkin;
                        }
                    }

                    if (isDynamicMatch)
                    {
                        data["team"] = playerTeams[lp.playerId.Value];
                    }


                    return data;
                });

            // After the lobby is provisioned and wait until the service is ready to notify clients that the match was made.
            // When clients receive this notification, they will be ready to connect.
            await lobby.WaitForGameServerReady(Provider.GetService<IBeamLobbyApi>());

            return serverInfo;
        }

        [ServerCallable]
        public async Task<MatchResult> ProcessMatchResult(string winnerId, string lobbyId)
        {
            BeamableLogger.Log("Creating match result for lobby " + lobbyId);

            var beamLobbyApi = Provider.GetService<IBeamLobbyApi>();
            if (!Guid.TryParse(lobbyId, out var lobbyGuid)) throw new MicroserviceException(500, "INVALID_LOBBY_ID", $"Provided Lobby ID was invalid. INVALID={lobbyId}.");

            // We can just fetch the lobby here and check if the winner is in it.
            Api.Autogenerated.Models.Lobby lobby = await beamLobbyApi.Get(lobbyGuid);
            var lobbyPlayers = lobby.players.GetOrElse([]);
            if (lobbyPlayers.All(lp => lp.playerId.Value != winnerId))
            {
                throw new MicroserviceException(500,
                    "WINNER_GAMERTAG_NOT_IN_LOBBY",
                    $"The provided winner's gamertag is not in the lobby. WINNER_ID={winnerId}, LOBBY_PLAYERS={string.Join(",", lobby.players.Value.Select(lp => lp.playerId.Value))}");
            }

            // Create the fake match result and set it in the lobby data
            var result = new MatchResult()
            {
                PerPlayerMatchResults = new Dictionary<string, PerPlayerMatchResult>()
            };
            var updates = new List<Task>();
            foreach (var player in lobbyPlayers)
            {
                // Only the winner will get rewards --- obviously, in games where there is a in-match ranking (1st, 2nd, etc...) this would look different.
                var gamerTag = long.Parse(player.playerId.Value);
                var wasWinner = gamerTag.ToString().Equals(winnerId);
                if (wasWinner)
                {
                    // Compute the amount of rewards to give
                    // This would usually be defined in a subclass of the "game_types" content type.
                    var rng = new Random();
                    var rankedPoints = rng.Next(50, 100);
                    var coins = rng.Next(10, 25);

                    // Effectively give the rewards to the winning player.
                    using (var newUser = AssumeNewUser(gamerTag))
                    {
                        updates.Add(newUser.Services.Leaderboards.SetScore("leaderboards.global", rankedPoints).TaskFromPromise());
                        updates.Add(newUser.Services.Inventory.AddCurrency("currency.coins", coins).TaskFromPromise());
                    }

                    // Add this to the return object of this callable --- this is used in clients to display who wins and what.
                    result.PerPlayerMatchResults.Add(player.playerId.Value, new PerPlayerMatchResult() { Won = true, RankEarned = rankedPoints, CoinsEarned = coins, });
                }
                else
                {
                    // Add this to the return object of this callable --- this is used in clients to display who wins and what.
                    result.PerPlayerMatchResults.Add(player.playerId.Value, new PerPlayerMatchResult() { Won = false, RankEarned = 0, CoinsEarned = 0, });
                }
            }

            // Wait for all the score setting and inventory updating requests to finish.
            try
            {
                await Task.WhenAll(updates);
            }
            catch (Exception e)
            {
                BeamableLogger.LogError(e);
                throw;
            }

            // We also set the resulting properties into the lobby so that the game server can replicate these out to clients once it gets the response from this call.
            return result;
        }

        /// <summary>
        /// Utility function defining defaults and keys for the "hathora_integration" realm-config namespace.
        /// These must be correctly set up in your realm for this microservice to work. 
        /// </summary>
        private static HathoraRealmConfig GetHathoraRealmConfig(RealmConfig config)
        {
            const string kNamespaceHathoraIntegration = "hathora_integration";
            const string kKeyAppID = "app_id";
            const string kKeyDevToken = "dev_token";
            const string kKeyFallbackRegion = "fallback_region";
            const string kKeyHathoraURL = "hathora_url";


            var hathoraRealmConfig = new HathoraRealmConfig
            {
                AppId = config.GetSetting(kNamespaceHathoraIntegration, kKeyAppID),
                DeveloperToken = config.GetSetting(kNamespaceHathoraIntegration, kKeyDevToken),
                FallbackRegion = config.GetSetting(kNamespaceHathoraIntegration, kKeyFallbackRegion, "Seattle"),
                HathoraURL = new Uri(config.GetSetting(kNamespaceHathoraIntegration, kKeyHathoraURL, "https://api.hathora.dev"))
            };

            return hathoraRealmConfig;
        }

        /// <summary>
        /// Takes in the roomId (in our case, the LobbyId) and calls the Hathora API based on realm-config settings and awaits for the response.
        /// </summary>
        private static async Task<HathoraConnectionInfo> CreateHathoraGameServer(RealmConfig config, string roomId, string region = null)
        {
            var hathoraRealmConfig = GetHathoraRealmConfig(config);
            var createUri = new Uri(hathoraRealmConfig.HathoraURL, $"/rooms/v2/{hathoraRealmConfig.AppId}/create?roomId={roomId}");

            var body = new HathoraCreateRoomRequest
            {
                roomConfig = "",
                region = region ?? hathoraRealmConfig.FallbackRegion
            };

            var serialized = JsonUtility.ToJson(body);
            var requestContent = new StringContent(serialized, Encoding.UTF8, "application/json");

            var http = new HttpClient() { DefaultRequestHeaders = { { "Authorization", $"Bearer {hathoraRealmConfig.DeveloperToken}" } } };
            var response = await http.PostAsync(createUri, requestContent);
            var content = await response.Content.ReadAsStringAsync();
            BeamableLogger.Log("Create Room Hathora Response: " + content);
            if (!response.IsSuccessStatusCode)
            {
                throw new Exception(content);
            }

            return JsonUtility.FromJson<HathoraConnectionInfo>(content);
        }

        /// <summary>
        /// Takes in the roomId (in our case, the LobbyId) and calls the Hathora API to get their room's connection information/state.
        /// We use this to wait until the server is provisioned before notifying players that the match is ready.
        /// </summary>
        private static async Task<HathoraConnectionInfo> PollHathoraGameServer(RealmConfig config, string roomId)
        {
            var hathoraRealmConfig = GetHathoraRealmConfig(config);
            var getUri = new Uri(hathoraRealmConfig.HathoraURL, $"/rooms/v2/{hathoraRealmConfig.AppId}/connectioninfo/{roomId}");

            var http = new HttpClient() { DefaultRequestHeaders = { { "Authorization", $"Bearer {hathoraRealmConfig.DeveloperToken}" } } };
            var response = await http.GetAsync(getUri);
            var content = await response.Content.ReadAsStringAsync();
            BeamableLogger.Log("Get ConnectionInfo Hathora Response: " + content);
            if (!response.IsSuccessStatusCode)
            {
                throw new Exception(content);
            }

            return JsonUtility.FromJson<HathoraConnectionInfo>(content);
        }
    }

    [Serializable]
    public class HathoraRealmConfig
    {
        public string AppId;
        public string DeveloperToken;
        public string FallbackRegion;
        public Uri HathoraURL;
    }

    [Serializable]
    public class HathoraCreateRoomRequest
    {
        public string roomConfig;
        public string region;
    }

    [Serializable]
    public class HathoraPortInfo
    {
        public string host;
        public string name;
        public int port;
        public string transportType;
    }

    [Serializable]
    public class HathoraConnectionInfo
    {
        public string processId;
        public string roomId;
        public string status;
        public HathoraPortInfo exposedPort;
        public List<HathoraPortInfo> additionalExposedPorts;
    }

    [Serializable]
    public class HathoraPingTimes
    {
        [JsonProperty("Los_Angeles")] public int LosAngeles;

        [JsonProperty("Chicago")] public int Chicago;

        [JsonProperty("Washington_DC")] public int WashingtonDc;

        [JsonProperty("Seattle")] public int Seattle;

        [JsonProperty("London")] public int London;

        [JsonProperty("Frankfurt")] public int Frankfurt;

        [JsonProperty("Sao_Paulo")] public int SaoPaulo;

        [JsonProperty("Tokyo")] public int Tokyo;

        [JsonProperty("Sydney")] public int Sydney;

        [JsonProperty("Singapore")] public int Singapore;

        [JsonProperty("Mumbai")] public int Mumbai;

        // create a + operator
        public static HathoraPingTimes operator +(HathoraPingTimes a, HathoraPingTimes b)
        {
            return new HathoraPingTimes
            {
                LosAngeles = a.LosAngeles + b.LosAngeles,
                Chicago = a.Chicago + b.Chicago,
                WashingtonDc = a.WashingtonDc + b.WashingtonDc,
                Seattle = a.Seattle + b.Seattle,
                London = a.London + b.London,
                Frankfurt = a.Frankfurt + b.Frankfurt,
                SaoPaulo = a.SaoPaulo + b.SaoPaulo,
                Tokyo = a.Tokyo + b.Tokyo,
                Sydney = a.Sydney + b.Sydney,
                Singapore = a.Singapore + b.Singapore,
                Mumbai = a.Mumbai + b.Mumbai
            };
        }

        public static HathoraPingTimes operator /(HathoraPingTimes a, int b)
        {
            return new HathoraPingTimes
            {
                LosAngeles = a.LosAngeles / b,
                Chicago = a.Chicago / b,
                WashingtonDc = a.WashingtonDc / b,
                Seattle = a.Seattle / b,
                London = a.London / b,
                Frankfurt = a.Frankfurt / b,
                SaoPaulo = a.SaoPaulo / b,
                Tokyo = a.Tokyo / b,
                Sydney = a.Sydney / b,
                Singapore = a.Singapore / b,
                Mumbai = a.Mumbai / b
            };
        }

        public List<KeyValuePair<string, int>> GetSortedPingTimes()
        {
            var pings = new List<KeyValuePair<string, int>>
            {
                new KeyValuePair<string, int>("Los_Angeles", LosAngeles),
                new KeyValuePair<string, int>("Chicago", Chicago),
                new KeyValuePair<string, int>("Washington_DC", WashingtonDc),
                new KeyValuePair<string, int>("Seattle", Seattle),
                new KeyValuePair<string, int>("London", London),
                new KeyValuePair<string, int>("Frankfurt", Frankfurt),
                new KeyValuePair<string, int>("Sao_Paulo", SaoPaulo),
                new KeyValuePair<string, int>("Tokyo", Tokyo),
                new KeyValuePair<string, int>("Sydney", Sydney),
                new KeyValuePair<string, int>("Singapore", Singapore),
                new KeyValuePair<string, int>("Mumbai", Mumbai),
            };

            // Sort the list by ping value
            pings.Sort((firstPair, nextPair) => { return firstPair.Value.CompareTo(nextPair.Value); });

            return pings;
        }
    }

    [Serializable]
    public class MatchResult
    {
        public Dictionary<string, PerPlayerMatchResult> PerPlayerMatchResults;
    }

    [Serializable]
    public class PerPlayerMatchResult
    {
        public bool Won;
        public int RankEarned;
        public int CoinsEarned;
    }
}