using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Dependencies;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using UnityEngine;
using SecurityTokenValidationException = System.IdentityModel.Tokens.SecurityTokenValidationException;

namespace Beamable.BeamballMs;

[FederationId(Id)]
public class EpicOnlineServicesId : IFederationId
{
    public const string Id = "eos";
}

public partial class BeamballMs : IFederatedLogin<EpicOnlineServicesId>
{
    /// <summary>
    /// Base URI for all Epic Online Services API endpoints.
    /// </summary>
    private const string EOS_BaseUri = "https://api.epicgames.dev";

    /// <summary>
    /// Namespace key used to retrieve EOS-specific configuration from Beamable realm config.
    /// </summary>
    private const string EOS_RealmConfigNamespace = "eos_integration";

    /// <summary>
    /// Realm config key for Epic Application ID - identifies your Epic Games application.
    /// Used to validate the "appid" claim in JWT tokens.
    /// </summary>
    private const string EOS_RealmConfigKey_ApplicationId = "applicationId";

    /// <summary>
    /// Realm config key for Epic Deployment ID - identifies the specific deployment environment.
    /// Required for EOS configuration but not currently used in authentication flow.
    /// </summary>
    private const string EOS_RealmConfigKey_DeploymentId = "deploymentId";

    /// <summary>
    /// Realm config key for Epic Client ID - OAuth2 client identifier.
    /// Used to validate the "aud" (audience) claim in JWT tokens.
    /// </summary>
    private const string EOS_RealmConfigKey_ClientId = "clientId";

    /// <summary>
    /// Realm config key for Epic Client Secret - OAuth2 client secret.
    /// Used for server-to-server authentication when fetching player account data.
    /// </summary>
    private const string EOS_RealmConfigKey_ClientSecret = "clientSecret";

    /// <summary>
    /// Validates that all required EOS configuration settings are present in realm config during service initialization.
    /// This is called at startup to fail fast if configuration is missing or invalid.
    ///
    /// Required Configuration:
    /// - eos.applicationId: Epic Application ID from Epic Developer Portal
    /// - eos.deploymentId: Epic Deployment ID from Epic Developer Portal
    /// - eos.clientId: OAuth2 Client ID from Epic Developer Portal
    /// - eos.clientSecret: OAuth2 Client Secret from Epic Developer Portal
    ///
    /// Exceptions are logged but not rethrown to prevent service startup failure.
    /// </summary>
    public static async Task InitializeEos(IDependencyProviderScope initializer)
    {
        try
        {
            var realmConfigService = initializer.GetService<IMicroserviceRealmConfigService>();
            var config = await realmConfigService.GetRealmConfigSettings();

            var applicationId = config.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ApplicationId, string.Empty);
            if (string.IsNullOrWhiteSpace(applicationId))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{EOS_RealmConfigNamespace}.{EOS_RealmConfigKey_ApplicationId} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }

            var deploymentId = config.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_DeploymentId, string.Empty);
            if (string.IsNullOrWhiteSpace(deploymentId))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{EOS_RealmConfigNamespace}.{EOS_RealmConfigKey_DeploymentId} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }

            var clientId = config.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ClientId, string.Empty);
            if (string.IsNullOrWhiteSpace(clientId))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{EOS_RealmConfigNamespace}.{EOS_RealmConfigKey_ClientId} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }

            var clientSecret = config.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ClientSecret, string.Empty);
            if (string.IsNullOrWhiteSpace(clientSecret))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{EOS_RealmConfigNamespace}.{EOS_RealmConfigKey_ClientSecret} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }
        }
        catch (Exception ex)
        {
            BeamableLogger.LogException(ex);
            BeamableLogger.LogError("Service initialization failed. Please fix the issues before using the service.");
        }
    }

    /// <summary>
    /// Authenticates an Epic Online Services (EOS) ID token using OpenID Connect JWT validation.
    ///
    /// NuGet Package Dependencies:
    /// - Microsoft.IdentityModel.Protocols.OpenIdConnect: Retrieves OIDC configuration and JWKS from Epic's discovery endpoint
    /// - System.IdentityModel.Tokens.Jwt: Parses and validates JWT tokens
    /// - Microsoft.IdentityModel.Tokens: Provides cryptographic token validation (signature, issuer, audience, lifetime)
    ///
    /// EOS Validation Process:
    /// 1. Retrieve realm configuration (clientId, applicationId) from Beamable config
    /// 2. Fetch Epic's OpenID configuration from their .well-known endpoint to obtain signing keys (JWKS)
    /// 3. Validate the JWT token cryptographically:
    ///    - Issuer: Must be "https://api.epicgames.dev"
    ///    - Audience: Must match the configured clientId
    ///    - Signature: Verified against Epic's public keys from JWKS
    ///    - Lifetime: Token must not be expired (with 2-minute clock skew tolerance)
    /// 4. Extract and verify claims:
    ///    - "sub" (subject): The Epic Account ID
    ///    - "appid"/"application_id": Must match the configured applicationId
    /// 5. Return the Epic Account ID as the federated user identifier
    ///
    /// See: https://dev.epicgames.com/docs/epic-account-services/auth/retrieve-and-validate-id-tokens
    /// </summary>
    async Promise<FederatedAuthenticationResponse> IFederatedLogin<EpicOnlineServicesId>.Authenticate(string token, string challenge, string solution)
    {
        BeamableLogger.Log("Request for authentication via EOS started");

        try
        {
            // Get realm configuration settings
            var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();
            var expectedClientId = realmSettings.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ClientId);
            var expectedApplicationId = realmSettings.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ApplicationId);

            // Configure the OIDC configuration manager to retrieve the JWKS from Epic's endpoint
            var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                GetEosOpenIdConfigUri(),
                new OpenIdConnectConfigurationRetriever(),
                new HttpDocumentRetriever());

            // Retrieve the OpenID configuration (which contains the JWKS endpoint)
            var discoveryDocument = await configurationManager.GetConfigurationAsync();

            // Configure token validation parameters
            var validationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = "https://api.epicgames.dev/epic/oauth/v1",
                ValidateAudience = true,
                ValidAudience = expectedClientId,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true,
                IssuerSigningKeys = discoveryDocument.SigningKeys,
                ClockSkew = TimeSpan.FromMinutes(2) // Allow 2 minutes clock skew
            };

            // Validate the JWT token
            var tokenHandler = new JwtSecurityTokenHandler();
            _ = tokenHandler.ValidateToken(token, validationParameters, out var validatedToken);

            // Extract claims from the validated token
            var jwtToken = (JwtSecurityToken)validatedToken;

            // Get the Epic Account ID from the token's subject claim
            var accountId = jwtToken.Subject;
            if (string.IsNullOrEmpty(accountId))
            {
                throw new MicroserviceException(400, "AuthenticationError", "Token does not contain a valid account ID (sub claim).");
            }

            // Verify the application_id claim matches our configuration
            // See https://dev.epicgames.com/docs/epic-account-services/auth/retrieve-and-validate-id-tokens for JWT claims structure
            var appIdClaim = jwtToken.Claims.FirstOrDefault(c => c.Type == "appid" || c.Type == "application_id");
            if (appIdClaim != null && appIdClaim.Value != expectedApplicationId)
            {
                throw new MicroserviceException(403, "AuthenticationError", "Token's ApplicationId did not match configured ApplicationId in realm config.");
            }

            BeamableLogger.Log($"Successfully authenticated Epic Account ID: {accountId}");

            // Return the validated Epic Account ID
            return new FederatedAuthenticationResponse()
            {
                user_id = accountId
            };
        }
        catch (SecurityTokenValidationException ex)
        {
            BeamableLogger.LogError($"JWT validation failed: {ex.Message}");
            throw new MicroserviceException(401, "AuthenticationError", $"Invalid JWT token: {ex.Message}");
        }
        catch (MicroserviceException)
        {
            // Re-throw MicroserviceExceptions as-is
            throw;
        }
        catch (Exception ex)
        {
            BeamableLogger.LogError($"Authentication failed: {ex.Message}");
            throw new MicroserviceException(500, "AuthenticationError", $"Failed to authenticate with EOS: {ex.Message}");
        }
    }

    /// <summary>
    /// Called in <see cref="IFederatedPlayerInit{T}.CreatePlayer"/> to initialize accounts that are created through Epic
    /// with data from Epic Games.
    ///
    /// This runs only once per account (during creation via SignUp operations AFTER authenticate).
    ///
    /// Please read Epic's docs here about how to get account information:
    /// https://dev.epicgames.com/docs/web-api-ref/authentication#fetching-accounts
    /// </summary>
    private async Task CreatePlayerEos(Account account, Dictionary<string, string> properties, Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
    {
        // If we find the Epic external identity at this time, it means this account was created via the Epic federation.
        // So, we can get the Epic realm config and make a request to get information about that user's Epic account.
        var associatedEpicIdentity = account.external.FirstOrDefault(e => e.providerNamespace == EpicOnlineServicesId.Id);
        if (associatedEpicIdentity != null)
        {
            BeamableLogger.Log("Initializing player account via Epic");

            try
            {
                var client = new HttpClient();
                var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();
                var clientId = realmSettings.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ClientId);
                var clientSecret = realmSettings.GetSetting(EOS_RealmConfigNamespace, EOS_RealmConfigKey_ClientSecret);

                // First, get a client credentials access token
                // Epic requires Basic authentication with clientId:clientSecret encoded in base64
                var tokenRequest = new HttpRequestMessage(HttpMethod.Post, GetEosReqTokenUri());
                var credentials = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{clientId}:{clientSecret}"));
                tokenRequest.Headers.Authorization = new AuthenticationHeaderValue("Basic", credentials);
                tokenRequest.Content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("grant_type", "client_credentials")
                });

                var tokenResponse = await client.SendAsync(tokenRequest);
                if (!tokenResponse.IsSuccessStatusCode)
                {
                    var errorBody = await tokenResponse.Content.ReadAsStringAsync();
                    BeamableLogger.LogError($"Failed to get access token from EOS: {tokenResponse.StatusCode} - {errorBody}");
                    throw new MicroserviceException((int)tokenResponse.StatusCode, "PlayerInitError",
                        $"Failed to get access token from EOS: {tokenResponse.ReasonPhrase}");
                }

                var tokenResponseBody = await tokenResponse.Content.ReadAsStringAsync();
                var tokenData = JsonConvert.DeserializeObject<EOSTokenResponse>(tokenResponseBody);

                // Now, use the access token to get account information
                var accountRequest = new HttpRequestMessage(HttpMethod.Get, GetEosAccountInfoUri(associatedEpicIdentity.userId));
                accountRequest.Headers.Add("Authorization", $"Bearer {tokenData.access_token}");

                var accountResponse = await client.SendAsync(accountRequest);
                if (accountResponse.IsSuccessStatusCode)
                {
                    var accountResponseBody = await accountResponse.Content.ReadAsStringAsync();

                    List<EpicAccountInfo> accountInfoList;
                    try
                    {
                        // Epic returns a JSON array directly, not wrapped in an object
                        accountInfoList = JsonConvert.DeserializeObject<List<EpicAccountInfo>>(accountResponseBody);
                    }
                    catch (Exception ex)
                    {
                        BeamableLogger.LogError($"Failed to deserialize Epic account info: {ex.Message}");
                        throw new MicroserviceException(500, "PlayerInitError", "Failed to deserialize response from EOS.");
                    }

                    var epicAccount = accountInfoList?.FirstOrDefault();
                    if (epicAccount == null)
                    {
                        throw new MicroserviceException(404,
                            "INVALID_EOS_USER_ID",
                            "Failed to find EOS user associated with this account. You should never see this. If you do, you likely have a bug in your Epic federation.");
                    }

                    var stats = new Dictionary<string, string>()
                    {
                        { "player_name", epicAccount.displayName ?? epicAccount.accountId },
                        { "avatar", "" }, // Epic doesn't provide avatar URLs in this API
                    };

                    // Set some beamable stats from the user's Epic profile
                    var realmGamerTag = account.gamerTags.First(g => g.projectId == Context.Pid).gamerTag;
                    await Services.Stats.SetStats(StatsDomainType.Client, StatsAccessType.Public, realmGamerTag, stats);

                    BeamableLogger.Log($"Successfully initialized Epic player: {epicAccount.displayName}");
                    return;
                }

                var errorResponseBody = await accountResponse.Content.ReadAsStringAsync();
                BeamableLogger.LogError($"Failed to get account info from EOS: {accountResponse.StatusCode} - {errorResponseBody}");
                throw new MicroserviceException((int)accountResponse.StatusCode, "PlayerInitError",
                    $"Failed to get account information from EOS: {accountResponse.ReasonPhrase}. ExternalID={associatedEpicIdentity.userId}");
            }
            catch (MicroserviceException)
            {
                throw;
            }
            catch (Exception ex)
            {
                BeamableLogger.LogError($"Error initializing Epic player: {ex.Message}");
                throw new MicroserviceException(500, "PlayerInitError", $"Failed to initialize Epic player: {ex.Message}");
            }
        }
    }

    /// <summary>
    /// See "https://dev.epicgames.com/docs/web-api-ref/authentication#requesting-an-access-token" for details (namely, "client_credentials").
    /// </summary>
    /// <returns></returns>
    private static string GetEosReqTokenUri() => $"{EOS_BaseUri}/epic/oauth/v2/token";

    /// <summary>
    /// See "https://dev.epicgames.com/docs/web-api-ref/authentication#fetching-accounts" for details.
    /// </summary>
    private static string GetEosAccountInfoUri(string accountId) => $"{EOS_BaseUri}/epic/id/v2/accounts?accountId={accountId}";

    /// <summary>
    /// OpenID Connect discovery endpoint for Epic Games OAuth.
    /// </summary>
    private static string GetEosOpenIdConfigUri() => $"{EOS_BaseUri}/epic/oauth/v1/.well-known/openid-configuration";
}

/// <summary>
/// Response model for Epic Online Services OAuth2 token endpoint.
/// Returned when requesting a client credentials access token for server-to-server API calls.
/// See: https://dev.epicgames.com/docs/web-api-ref/authentication#requesting-an-access-token
/// </summary>
[Serializable]
public class EOSTokenResponse
{
    /// <summary>
    /// The OAuth2 access token used to authenticate subsequent API requests to Epic services.
    /// </summary>
    [JsonPropertyName("access_token")]
    public string access_token { get; set; }

    /// <summary>
    /// The type of token, typically "bearer".
    /// </summary>
    [JsonPropertyName("token_type")]
    public string token_type { get; set; }

    /// <summary>
    /// Token lifetime in seconds from the time of issuance.
    /// </summary>
    [JsonPropertyName("expires_in")]
    public int expires_in { get; set; }

    /// <summary>
    /// Absolute timestamp when the token expires.
    /// </summary>
    [JsonPropertyName("expires_at")]
    public DateTime expires_at { get; set; }
}

/// <summary>
/// Detailed information about an Epic Games account.
/// Retrieved from the Epic account information API for player initialization.
/// The API returns an array of these objects directly (not wrapped in a parent object).
/// See: https://dev.epicgames.com/docs/web-api-ref/authentication#fetching-accounts
/// </summary>
[Serializable]
public class EpicAccountInfo
{
    /// <summary>
    /// Unique Epic Account ID for the user.
    /// </summary>
    [JsonPropertyName("accountId")]
    public string accountId { get; set; }

    /// <summary>
    /// User's display name as configured in their Epic account.
    /// </summary>
    [JsonPropertyName("displayName")]
    public string displayName { get; set; }

    /// <summary>
    /// User's preferred language code (e.g., "en", "es", "fr").
    /// </summary>
    [JsonPropertyName("preferredLanguage")]
    public string preferredLanguage { get; set; }
}