using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Dependencies;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Newtonsoft.Json;
using UnityEngine;

namespace Beamable.BeamballMs;

[FederationId(Id)]
public class SteamId : IFederationId
{
    public const string Id = "steam";
}

public partial class BeamballMs : IFederatedLogin<SteamId>
{
    private const string Steam_BaseUri = "https://partner.steam-api.com";

    public static async Task InitializeSteam(IDependencyProviderScope dependencyProviderScope)
    {
        try
        {
            var realmConfigService = dependencyProviderScope.GetService<IMicroserviceRealmConfigService>();
            var config = await realmConfigService.GetRealmConfigSettings();
            var appId = config.GetSetting("steam", "appid", string.Empty);
            if (string.IsNullOrWhiteSpace(appId))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    "steam.appid is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }

            var publisherToken = config.GetSetting("steam", "key", string.Empty);
            if (string.IsNullOrWhiteSpace(publisherToken))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    "steam.key is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }
        }
        catch (Exception ex)
        {
            BeamableLogger.LogException(ex);
            BeamableLogger.LogError("Service initialization failed. Please fix the issues before using the service.");
        }
    }

    async Promise<FederatedAuthenticationResponse> IFederatedLogin<SteamId>.Authenticate(string token, string challenge, string solution)
    {
        BeamableLogger.Log("Request for authentication via Steam started");
        var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();

        // Use the user-provided token, the publisher API Key and the AppId to build the steam url.
        var publisherApiKey = realmSettings.GetSetting("steam", "key");
        var appId = realmSettings.GetSetting("steam", "appid");
        var uri = GetSteamAuthenticateUri(token, publisherApiKey, appId);

        // Make the request to steam so we can get information about the user that generated the token (Steam calls this "token" an AuthTicket).
        var client = new HttpClient();
        var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, uri));
        if (response.IsSuccessStatusCode)
        {
            var responseBody = await response.Content.ReadAsStringAsync();
            try
            {
                // Parse the response and extract the user's "Unique Id in Steam" and forward that along as the response to this function.
                var ticket = JsonConvert.DeserializeObject<SteamAuthenticateUserTicket>(responseBody);
                return new FederatedAuthenticationResponse { user_id = ticket.response.ResponseParams.steamid, };
            }
            catch (Exception)
            {
                // If an error comes back and we can't parse Steam's response, that's an error.
                throw new MicroserviceException(500, "AuthenticationError", "Failed to deserialize response from Steam.");
            }
        }

        // If the request itself fails, we just surface that error.
        Debug.Log($"Failed request, {response.StatusCode}: {response.RequestMessage}");
        throw new MicroserviceException((int)response.StatusCode, "AuthenticationError", $"Failed to connect to Steam: {response.ReasonPhrase}");
    }


    /// <summary>
    /// Called in <see cref="IFederatedPlayerInit{T}.CreatePlayer"/> to initialize accounts that are created through Steam
    /// with data in steam.
    ///
    /// This runs only once per account (during creation via SignUp operations AFTER authenticate).
    /// </summary>
    private async Task CreatePlayerSteam(Account account, Dictionary<string, string> properties, Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
    {
        // If we find the Steam external identity at this time, it means this account was created via the Steam federation.
        // So, we can get the steam realm config and make a request to get information about that user's steam account.
        var associatedSteamIdentity = account.external.FirstOrDefault(e => e.providerNamespace == SteamId.Id);
        if (associatedSteamIdentity != null)
        {
            BeamableLogger.Log("Initializing player account via Steam");

            var client = new HttpClient();
            var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();
            var publisherToken = realmSettings.GetSetting("steam", "key");
            var uri = GetSteamGetPlayerSummariesUri(publisherToken, new[] { associatedSteamIdentity.userId });
            var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, uri));

            // If the request succeeds, we deserialize the steam data and fill in any custom stats our game uses.
            if (response.IsSuccessStatusCode)
            {
                var responseBody = await response.Content.ReadAsStringAsync();

                SteamGetPlayerSummaryResponse playerSummary;
                try
                {
                    playerSummary = JsonConvert.DeserializeObject<SteamGetPlayerSummaryResponse>(responseBody);
                }
                catch (Exception)
                {
                    throw new MicroserviceException(500, "PlayerInitError", "Failed to deserialize response from Steam.");
                }

                var p = playerSummary.response.Players.FirstOrDefault();
                if (p == null)
                {
                    throw new MicroserviceException(404,
                        "INVALID_STEAM_USER_ID",
                        "Failed to find steam user associated with this account. You should never see this. If you do, you likely have a bug in your steam federation.");
                }

                outStartingStats["player_name"] = p.personaname;
                outStartingStats["avatar"] = p.avatar;
                outStartingStats["avatar_medium"] = p.avatarmedium;
                outStartingStats["avatar_full"] = p.avatarfull;

                return;
            }

            Debug.Log($"Failed request, {response.StatusCode}: {response.RequestMessage}");
            throw new MicroserviceException((int)response.StatusCode, "PlayerInitError",
                $"Failed to connect to Steam: {response.ReasonPhrase}. ExternalID={associatedSteamIdentity.userId}");
        }
    }

    /// <summary>
    /// See "https://partner.steamgames.com/doc/webapi/isteamuserauth" for details. 
    /// </summary>
    private static string GetSteamAuthenticateUri(string ticket, string publisherToken, string appId) => $"{Steam_BaseUri}/ISteamUserAuth/AuthenticateUserTicket/v1/?key={publisherToken}&appid={appId}&ticket={ticket}";

    /// <summary>
    /// See "https://partner.steamgames.com/doc/webapi/isteamuser" for details.
    /// </summary>
    private static string GetSteamGetPlayerSummariesUri(string publisherToken, string[] userIds) => $"{Steam_BaseUri}/ISteamUser/GetPlayerSummaries/v2/?key={publisherToken}&steamids={string.Join(",", userIds)}";
    
}

/// <summary>
/// Class declaration to parse Steam's <see cref="BeamballMs.GetSteamAuthenticateUri"/>'s response.
/// See "https://partner.steamgames.com/doc/webapi/isteamuserauth" for details.
/// </summary>
[Serializable]
public class SteamAuthenticateUserTicket
{
    public SteamResponse response { get; set; }

    [Serializable]
    public class SteamResponse
    {
        [JsonProperty(PropertyName = "params")]
        public SteamResponseParams ResponseParams { get; set; }
    }

    [Serializable]
    public class SteamResponseParams
    {
        public string result { get; set; }
        public string steamid { get; set; }
        public string ownersteamid { get; set; }
        public bool vacbanned { get; set; }
        public bool publisherbanned { get; set; }
    }
}

/// <summary>
/// Class declaration to parse Steam's <see cref="BeamballMs.GetSteamGetPlayerSummariesUri"/>'s response.
/// See "https://partner.steamgames.com/doc/webapi/isteamuser" for details.
/// </summary>
[Serializable]
public class SteamGetPlayerSummaryResponse
{
    public Body response { get; set; }


    [Serializable]
    public class Body
    {
        [JsonProperty(PropertyName = "players")]
        public Player[] Players { get; set; }
    }

    [Serializable]
    public class Player
    {
        public string steamid { get; set; }
        public string personaname { get; set; }
        public string avatar { get; set; }
        public string avatarmedium { get; set; }
        public string avatarfull { get; set; }
    }
}