using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Dependencies;
using Beamable.Server;
using Beamable.Server.Api.Notifications;
using Beamable.Server.Api.RealmConfig;
using Beamable.Server.Api.Stats;
using Discord;
using Discord.WebSocket;
using UnityEngine;
using EmptyResponse = Beamable.Common.Api.EmptyResponse;

namespace Beamable.BeamballMs;

[FederationId(Id)]
public class DiscordId : IFederationId
{
    public const string Id = "discord";
}

public partial class BeamballMs : IFederatedLogin<DiscordId>
{
    public const string DiscordWhitelistedStatKey = "matchmaking_discord_whitelisted";

    [Serializable]
    public class DiscordWhitelistedInfo
    {
        public bool matchmaking_discord_whitelisted;
    }

    [ConfigureServices]
    public static void ConfigureDiscord(IServiceBuilder builder)
    {
        builder.Builder.AddSingleton<DiscordBot>();
    }

    /// <summary>
    /// Validates Discord realm configuration and connects the <see cref="DiscordBot"/> to Discord's gateway.
    /// Invoked from <see cref="Program"/>'s service initializer alongside the other platform integrations.
    /// </summary>
    public static async Task InitializeDiscord(IDependencyProviderScope scope)
    {
        try
        {
            var discordBot = scope.GetService<DiscordBot>();
            await discordBot.Connect();
        }
        catch (Exception ex)
        {
            BeamableLogger.LogException(ex);
            BeamableLogger.LogError("Discord initialization failed. Please fix the issues before using Discord federated login.");
        }
    }

    async Promise<FederatedAuthenticationResponse> IFederatedLogin<DiscordId>.Authenticate(string token, string challenge, string solution)
    {
        var discordUserFromToken = await DiscordRequests.GetDiscordUserFromToken(token);
        if (discordUserFromToken == null) throw new UnauthorizedAccessException($"Invalid Discord Token");
        return new FederatedAuthenticationResponse { user_id = discordUserFromToken.id, };
    }


    /// <summary>
    /// Called in <see cref="IFederatedPlayerInit{T}.CreatePlayer"/> to initialize accounts that are created through Discord
    /// with data from Discord.
    ///
    /// This runs only once per account (during creation via SignUp operations AFTER authenticate).
    ///
    /// Retrieves player profile information from Discord's Guild Member API and populates initial stats
    /// including display name and avatar URL. The bot token configured in the "discord_integration" realm config
    /// namespace is used to query the guild member endpoint — the bot must share the configured guild with the user.
    ///
    /// See: https://discord.com/developers/docs/resources/guild#get-guild-member
    /// </summary>
    private async Task CreatePlayerDiscord(Account account, Dictionary<string, string> properties, Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
    {
        // If we find the Discord external identity at this time, it means this account was created via the Discord federation.
        // So, we can get the Discord realm config and make a request to get information about that user's Discord account.
        var associatedDiscordIdentity = account.external?.FirstOrDefault(e => e.providerNamespace == DiscordId.Id);
        if (associatedDiscordIdentity != null)
        {
            BeamableLogger.Log("Initializing player account via Discord");

            try
            {
                var discordRealmConfig = await DiscordRequests.GetDiscordRealmConfig(Services.RealmConfig);
                if (string.IsNullOrWhiteSpace(discordRealmConfig.BotToken) || string.IsNullOrWhiteSpace(discordRealmConfig.GuildId))
                {
                    BeamableLogger.LogWarning("Discord bot token or guild id not configured; skipping Discord player init.");
                    return;
                }

                var discordGuildUser = await DiscordRequests.GetGuildUserById(
                    discordRealmConfig.BotToken, discordRealmConfig.GuildId, associatedDiscordIdentity.userId);

                if (discordGuildUser?.user == null)
                {
                    throw new MicroserviceException(404,
                        "INVALID_DISCORD_USER_ID",
                        $"Failed to find Discord user associated with this account. You should never see this. If you do, you likely have a bug in your Discord federation. ExternalID={associatedDiscordIdentity.userId}");
                }

                // Fill out public stats
                var discordUser = discordGuildUser.user;
                outStartingStats["player_name"] = !string.IsNullOrWhiteSpace(discordUser.global_name)
                    ? discordUser.global_name
                    : discordUser.username;
                outStartingStats["avatar"] = GetDiscordAvatarUrl(discordUser);


                // Set a private stat
                var gamerTag = account.gamerTags.First(gta => gta.projectId == Context.Pid).gamerTag;
                var isWhitelisted = IsDiscordUserWhitelistedForMatchmaking(discordGuildUser, discordRealmConfig);
                Log.Warning("Attaching [Discord UserId = {UserId}] to [GamerTag = {BeamableId}].{Whitelist}", associatedDiscordIdentity.userId, gamerTag, isWhitelisted ? $"User Whitelisted." : "User Not Whitelisted");
                await using var requestingUser = AssumeNewUser(gamerTag);
                await requestingUser.Services.Stats.SetStats(StatsDomainType.Game, StatsAccessType.Private, gamerTag, new() { { DiscordWhitelistedStatKey, $"{isWhitelisted}" }, });

                BeamableLogger.Log($"Successfully initialized Discord player: {discordUser.username}");
            }
            catch (MicroserviceException)
            {
                throw;
            }
            catch (Exception ex)
            {
                BeamableLogger.LogError($"Error initializing Discord player: {ex.Message}");
                throw new MicroserviceException(500, "PlayerInitError", $"Failed to initialize Discord player: {ex.Message}");
            }
        }
    }

    [ClientCallable, SwaggerCategory("discord")]
    public async Task<bool> UpdateFromDiscord()
    {
        var discordRealmConfig = await DiscordRequests.GetDiscordRealmConfig(Services.RealmConfig);
        var gamerTag = Context.UserId;

        var beamableUser = await Services.Auth.GetUser(gamerTag);
        var discordUserId = beamableUser.external.FirstOrDefault(identity => identity.providerNamespace == DiscordId.Id)?.userId;

        if (string.IsNullOrEmpty(discordUserId))
            return false;

        var discordGuildUser = await DiscordRequests.GetGuildUserById(discordRealmConfig.BotToken, discordRealmConfig.GuildId, discordUserId);
        var isWhitelisted = IsDiscordUserWhitelistedForMatchmaking(discordGuildUser, discordRealmConfig);
        Log.Warning("Updating User Matchmaking Whitelist State [GamerTag = {BeamableId}].{Whitelist}", gamerTag, isWhitelisted ? $"User Whitelisted." : "User Not Whitelisted");

        await Services.Stats.SetStats(StatsDomainType.Game, StatsAccessType.Private, gamerTag, new()
        {
            { DiscordWhitelistedStatKey, $"{isWhitelisted}" }
        });
        await Services.Notifications.NotifyUser(gamerTag, isWhitelisted);

        return isWhitelisted;
    }

    [ClientCallable, SwaggerCategory("discord")]
    public async Task<DiscordWhitelistedInfo> UpdateUserWhitelistedStatus()
    {
        var whitelistedStat = await Services.Stats.GetStat(StatsDomainType.Game, StatsAccessType.Private, Context.UserId, DiscordWhitelistedStatKey);
        Debug.Log($"{Context.UserId} whitelistedStat: {whitelistedStat}");
        var isWhitelisted = !string.IsNullOrWhiteSpace(whitelistedStat) && whitelistedStat.Equals("true", StringComparison.InvariantCultureIgnoreCase);
        return new DiscordWhitelistedInfo() { matchmaking_discord_whitelisted = isWhitelisted };
    }

    private static bool IsDiscordUserWhitelistedForMatchmaking(DiscordGuildUser discordGuildUser, DiscordRealmConfig discordRealmConfig)
    {
        return discordGuildUser?.roles != null && discordGuildUser.roles.Intersect(discordRealmConfig.RoleIds).Any();
    }

    /// <summary>
    /// Builds the CDN URL for a Discord user's avatar from the avatar hash returned by Discord's API.
    /// Returns an empty string when the user has no custom avatar set.
    /// See: https://discord.com/developers/docs/reference#image-formatting
    /// </summary>
    private static string GetDiscordAvatarUrl(DiscordUser user)
    {
        if (string.IsNullOrEmpty(user?.avatar) || string.IsNullOrEmpty(user.id))
            return string.Empty;
        return $"https://cdn.discordapp.com/avatars/{user.id}/{user.avatar}.png";
    }
}

public class DiscordBot
{
    private readonly IBeamableRequester _beamableRequester;
    private readonly IMicroserviceRealmConfigService _beamableConfigService;
    private readonly IMicroserviceStatsApi _beamableStatsService;
    private readonly IMicroserviceNotificationsApi _notificationsApi;
    private readonly DiscordSocketClient _discordClient;

    public DiscordBot(IBeamableRequester requester, IMicroserviceRealmConfigService realmConfigService,
        IMicroserviceStatsApi statsService, IMicroserviceNotificationsApi notificationsApi)
    {
        _beamableRequester = requester;
        _beamableConfigService = realmConfigService;
        _beamableStatsService = statsService;
        _notificationsApi = notificationsApi;

        _discordClient = new DiscordSocketClient(
            new DiscordSocketConfig
            {
                AlwaysDownloadUsers = true,
                GatewayIntents = GatewayIntents.Guilds | GatewayIntents.GuildMembers,
            }
        );

        _discordClient.Log += OnLog; // Debug purposes
        _discordClient.Ready += OnReady;
        _discordClient.Disconnected += OnDisconnected;
        _discordClient.GuildMemberUpdated += OnGuildMemberUpdated;
    }

    private Task OnDisconnected(Exception arg)
    {
        BeamableLogger.LogException(arg);
        return Task.CompletedTask;
    }

    public async Task Connect()
    {
        if (_discordClient.ConnectionState == ConnectionState.Disconnected)
        {
            var discordRealmConfig = await DiscordRequests.GetDiscordRealmConfig(_beamableConfigService);
            var botToken = discordRealmConfig.BotToken;
            var rolesConfig = discordRealmConfig.RoleIds;
            if (string.IsNullOrEmpty(botToken))
            {
                BeamableLogger.LogWarning("Discord Bot Token not configured. Connection Aborted!");
                return;
            }

            if (rolesConfig.Count == 0)
            {
                BeamableLogger.LogWarning("Discord Roles whitelist is empty. Connection Aborted!");
                return;
            }

            await _discordClient.LoginAsync(TokenType.Bot, botToken);
            await _discordClient.StartAsync();
            await _discordClient.SetStatusAsync(UserStatus.Online);
            await _discordClient.SetGameAsync("status");
        }
    }

    private Task OnReady()
    {
        BeamableLogger.Log($"Connected to discord servers: {string.Join(", ", _discordClient.Guilds)}");
        return Task.CompletedTask;
    }

    // Debug Logging of received messages
    private Task OnLog(LogMessage msg)
    {
        BeamableLogger.Log($"{msg}\n");
        return Task.CompletedTask;
    }

    private async Task OnGuildMemberUpdated(Cacheable<SocketGuildUser, ulong> cachedUser, SocketGuildUser postUpdateUser)
    {
        BeamableLogger.Log("Role has changed!");
        if (cachedUser.HasValue)
        {
            if (cachedUser.Value.Roles.Count != postUpdateUser.Roles.Count)
            {
                var roles = postUpdateUser.Roles.Select(role => role.Name);
                // Roles of the user has changed
                BeamableLogger.Log($"Role has changed for user: {postUpdateUser.Id}");
                BeamableLogger.Log($"Roles: {string.Join(",", roles)}");

                var config = await DiscordRequests.GetDiscordRealmConfig(_beamableConfigService);
                var hasAccess = postUpdateUser.Roles.Any(role => config.RoleIds.Contains(role.Id.ToString()));

                await UpdateAccess(cachedUser.Value, hasAccess);
            }
        }
    }

    private async Task UpdateAccess(SocketGuildUser discordUser, bool hasAccess)
    {
        var discordUserId = discordUser.Id.ToString();
        try
        {
            var account = await DiscordRequests.GetBeamableAccountFromDiscordId(_beamableRequester, discordUserId);
            var gamerTagAssociation = account.gamerTags.FirstOrDefault(association => association.projectId == _beamableRequester.Pid);

            // No gamer tag found for this user in this realm.
            if (gamerTagAssociation == null)
                return;

            await _beamableStatsService.SetStats("game", "private", "player", gamerTagAssociation.gamerTag,
                new Dictionary<string, string>
                {
                    { BeamballMs.DiscordWhitelistedStatKey, hasAccess.ToString() }
                }
            );
            await _notificationsApi.NotifyUser(gamerTagAssociation.gamerTag, hasAccess);
            var discordRealmConfig = await DiscordRequests.GetDiscordRealmConfig(_beamableConfigService);
            if (discordRealmConfig.NotifyChannel == 0)
                return;

            var channel = await _discordClient.GetChannelAsync(discordRealmConfig.NotifyChannel);
            if (channel is IMessageChannel messageChannel)
            {
                await messageChannel.SendMessageAsync($"{discordUser.Mention} Updated matchmaking status: {(hasAccess ? "access gained" : "access denied")}");
            }

            BeamableLogger.Log($"Updated Access for Beamable PlayerId '{gamerTagAssociation.gamerTag}', Discord UserId '{discordUserId}' to '{hasAccess}'."
            );
        }
        catch (WebsocketRequesterException ex) when (ex.Status == 404)
        {
            // Account Not Found
            BeamableLogger.Log($"No Beamable account found for Discord UserId '{discordUserId}'.");
        }
    }
}

public static class DiscordRequests
{
    [Serializable]
    private class GetAccountRequest
    {
        public ExternalAccount external;

        public GetAccountRequest(string providerService, string providerNamespace, string userId)
        {
            external = new ExternalAccount
            {
                providerService = providerService,
                providerNamespace = providerNamespace,
                userId = userId
            };
        }
    }

    public static Promise<EmptyResponse> NotifyUser(this IMicroserviceNotificationsApi api, long gamerTag,
        bool isWhitelisted)
    {
        var value = JsonUtility.ToJson(new BeamballMs.DiscordWhitelistedInfo
            { matchmaking_discord_whitelisted = isWhitelisted });
        BeamableLogger.Log($"Notify player {gamerTag} that whitelisted value is: {value}");
        return api.NotifyPlayer(gamerTag, "matchmaking_refresh",
            new BeamballMs.DiscordWhitelistedInfo { matchmaking_discord_whitelisted = isWhitelisted });
    }

    public static Promise<BeamableAccount> GetBeamableAccountFromDiscordId(IBeamableRequester beamableRequester,
        string discordUserId)
    {
        return beamableRequester.Request<BeamableAccount>(
            Method.GET,
            "/basic/accounts",
            new GetAccountRequest(nameof(BeamballMs), DiscordId.Id, discordUserId),
            includeAuthHeader: false);
    }

    public static async Task<DiscordGuildUser> GetGuildUserById(string botToken, string guildId, string userId)
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Add("Authorization", $"Bot {botToken}");
        var response = await httpClient.GetAsync($"https://discord.com/api/v10/guilds/{guildId}/members/{userId}");

        var asStr = await response.Content.ReadAsStringAsync();
        Log.Warning("Discord Get Current Guild User Raw Response = {RawResponse}", asStr);

        if (!response.IsSuccessStatusCode)
            return null;

        try
        {
            var discordGuildUser = JsonUtility.FromJson<DiscordGuildUser>(asStr);
            return discordGuildUser;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public static async Task<DiscordGuild> GetGuildInfo(string botToken, string guildId)
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Add("Authorization", $"Bot {botToken}");
        var response = await httpClient.GetAsync($"https://discord.com/api/v10/guilds/{guildId}");

        var asStr = await response.Content.ReadAsStringAsync();
        Log.Warning("Discord Get Current Guild User Raw Response = {RawResponse}", asStr);

        if (!response.IsSuccessStatusCode)
            return null;

        try
        {
            var discordGuildUser = JsonUtility.FromJson<DiscordGuild>(asStr);
            return discordGuildUser;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public static async Task<DiscordUser> GetDiscordUserFromToken(string token)
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
        var response = await httpClient.GetAsync("https://discord.com/api/v10/users/@me");

        var asStr = await response.Content.ReadAsStringAsync();
        Log.Warning("Discord Raw Response = {RawResponse}", asStr);

        // If we failed to get a valid user with the given token, we fail the verification
        if (!response.IsSuccessStatusCode) return null;

        // We ensure that the response is formatted as expected and that we can parse the data we need from it.
        // If we can't, we fail the request.
        try
        {
            var discordUser = JsonUtility.FromJson<DiscordUser>(asStr);
            return discordUser;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public static async Task<DiscordRealmConfig> GetDiscordRealmConfig(IMicroserviceRealmConfigService realmConfigService)
    {
        var realmConfig = await realmConfigService.GetRealmConfigSettings();
        var discordRealmConfig = realmConfig.GetNamespace("discord_integration");
        var notifyChannelSetting = discordRealmConfig.GetSetting("notify_channel");
        return new DiscordRealmConfig
        {
            BotToken = discordRealmConfig.GetSetting("bot_token"),
            GuildId = discordRealmConfig.GetSetting("guild_id"),
            NotifyChannel = ulong.TryParse(notifyChannelSetting, out var value) ? value : 0,
            RoleIds = discordRealmConfig.GetSetting("matchmaking_roles_whitelist")?.Trim().Split(",").ToHashSet() ??
                      [],
        };
    }
}

[Serializable]
public class DiscordUser
{
    public string id;
    public string username;
    public string global_name;
    public string avatar;
    public string discriminator;
    public int public_flags;
    public int flags;
    public string banner;
    public string accent_color;
    public string locale;
    public bool mfa_enabled;
    public int premium_type;
    public string avatar_decoration;
    public string email;
    public bool verified;
}

public class DiscordRealmConfig
{
    public string BotToken;
    public string GuildId;
    public ulong NotifyChannel;
    public HashSet<string> RoleIds;
}

[Serializable]
public class DiscordGuildUser
{
    public DiscordUser user;
    public string[] roles;
}

[Serializable]
public class DiscordGuildRole
{
    public string id;
    public string name;
}

[Serializable]
public class BeamableAccount
{
    public GamerTagAssociation[] gamerTags;
}

[Serializable]
public class ExternalAccount
{
    public string providerService;
    public string providerNamespace;
    public string userId;
}

[Serializable]
public class DiscordGuild
{
    public string id;
    public string name;
    public string icon;
    public string description;
    public string splash;
    public long approximate_member_count;
    public long approximate_presence_count;
    public string[] features;
    public DiscordRole[] roles;
}

[Serializable]
public class DiscordRole
{
    public string id;
    public string name;
    public string permissions;
    public long position;
    public long color;
    public bool hoist;
}