using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Dependencies;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Newtonsoft.Json;
using UnityEngine;

namespace Beamable.BeamballMs;

[FederationId(Id)]
public class SteamId : IFederationId
{
    public const string Id = "steam";
}

public partial class BeamballMs : IFederatedLogin<SteamId>
{
    /// <summary>
    /// Base URI for all Steam Partner Web API endpoints.
    /// </summary>
    private const string Steam_BaseUri = "https://partner.steam-api.com";

    /// <summary>
    /// Namespace key used to retrieve Steam-specific configuration from Beamable realm config.
    /// </summary>
    private const string Steam_RealmConfigNamespace = "steam_integration";

    /// <summary>
    /// Realm config key for Steam App ID - identifies your Steam application.
    /// </summary>
    private const string Steam_RealmConfigKey_AppId = "appid";

    /// <summary>
    /// Realm config key for Steam Publisher Web API Key - used for server-to-server authentication.
    /// </summary>
    private const string Steam_RealmConfigKey_Key = "key";

    /// <summary>
    /// Validates that all required Steam configuration settings are present in realm config during service initialization.
    /// This is called at startup to fail fast if configuration is missing or invalid.
    ///
    /// Required Configuration:
    /// - steam_integration.appid: Steam App ID from Steamworks Partner portal
    /// - steam_integration.key: Publisher Web API Key from Steamworks Partner portal
    ///
    /// Exceptions are logged but not rethrown to prevent service startup failure.
    /// </summary>
    public static async Task InitializeSteam(IDependencyProviderScope dependencyProviderScope)
    {
        try
        {
            var realmConfigService = dependencyProviderScope.GetService<IMicroserviceRealmConfigService>();
            var config = await realmConfigService.GetRealmConfigSettings();
            var appId = config.GetSetting(Steam_RealmConfigNamespace, Steam_RealmConfigKey_AppId, string.Empty);
            if (string.IsNullOrWhiteSpace(appId))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{Steam_RealmConfigNamespace}.{Steam_RealmConfigKey_AppId} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }

            var publisherToken = config.GetSetting(Steam_RealmConfigNamespace, Steam_RealmConfigKey_Key, string.Empty);
            if (string.IsNullOrWhiteSpace(publisherToken))
            {
                throw new MicroserviceException((int)HttpStatusCode.BadRequest, "ConfigurationError",
                    $"{Steam_RealmConfigNamespace}.{Steam_RealmConfigKey_Key} is not defined in realm config. Please apply the configuration and restart the service to make it operational.");
            }
        }
        catch (Exception ex)
        {
            BeamableLogger.LogException(ex);
            BeamableLogger.LogError("Service initialization failed. Please fix the issues before using the service.");
        }
    }

    /// <summary>
    /// Authenticates a Steam user by validating their Auth Session Ticket using the Steam Partner Web API.
    ///
    /// Steam Authentication Process:
    /// 1. Retrieve realm configuration (publisherApiKey, appId) from Beamable config
    /// 2. Use the AuthenticateUserTicket API endpoint to validate the user's session ticket
    /// 3. Parse the response to extract the user's Steam ID (unique identifier)
    /// 4. Return the Steam ID as the federated user identifier
    ///
    /// The token parameter contains an Auth Session Ticket generated by the Steam client SDK.
    /// This ticket is validated against Steam's servers to ensure the user owns the game
    /// and has a valid active session.
    ///
    /// See: https://partner.steamgames.com/doc/webapi/isteamuserauth
    /// </summary>
    async Promise<FederatedAuthenticationResponse> IFederatedLogin<SteamId>.Authenticate(string token, string challenge, string solution)
    {
        BeamableLogger.Log("Request for authentication via Steam started");
        var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();

        // Use the user-provided token, the publisher API Key and the AppId to build the steam url.
        var publisherApiKey = realmSettings.GetSetting(Steam_RealmConfigNamespace, Steam_RealmConfigKey_Key);
        var appId = realmSettings.GetSetting(Steam_RealmConfigNamespace, Steam_RealmConfigKey_AppId);
        var uri = GetSteamAuthenticateUri(token, publisherApiKey, appId);

        // Make the request to steam so we can get information about the user that generated the token (Steam calls this "token" an AuthTicket).
        var client = new HttpClient();
        var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, uri));
        if (response.IsSuccessStatusCode)
        {
            var responseBody = await response.Content.ReadAsStringAsync();
            try
            {
                // Parse the response and extract the user's "Unique Id in Steam" and forward that along as the response to this function.
                var ticket = JsonConvert.DeserializeObject<SteamAuthenticateUserTicket>(responseBody);
                return new FederatedAuthenticationResponse { user_id = ticket.response.ResponseParams.steamid, };
            }
            catch (Exception)
            {
                // If an error comes back and we can't parse Steam's response, that's an error.
                throw new MicroserviceException(500, "AuthenticationError", "Failed to deserialize response from Steam.");
            }
        }

        // If the request itself fails, we just surface that error.
        Debug.Log($"Failed request, {response.StatusCode}: {response.RequestMessage}");
        throw new MicroserviceException((int)response.StatusCode, "AuthenticationError", $"Failed to connect to Steam: {response.ReasonPhrase}");
    }


    /// <summary>
    /// Called in <see cref="IFederatedPlayerInit{T}.CreatePlayer"/> to initialize accounts that are created through Steam
    /// with data from Steam.
    ///
    /// This runs only once per account (during creation via SignUp operations AFTER authenticate).
    ///
    /// Retrieves player profile information from Steam's GetPlayerSummaries API and populates
    /// initial stats including display name and avatar URLs. This enriches the Beamable account
    /// with Steam profile data for display in-game.
    ///
    /// See: https://partner.steamgames.com/doc/webapi/isteamuser
    /// </summary>
    private async Task CreatePlayerSteam(Account account, Dictionary<string, string> properties, Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
    {
        // If we find the Steam external identity at this time, it means this account was created via the Steam federation.
        // So, we can get the steam realm config and make a request to get information about that user's steam account.
        var associatedSteamIdentity = account.external?.FirstOrDefault(e => e.providerNamespace == SteamId.Id);
        if (associatedSteamIdentity != null)
        {
            BeamableLogger.Log("Initializing player account via Steam");

            var client = new HttpClient();
            var realmSettings = await Services.RealmConfig.GetRealmConfigSettings();
            var publisherToken = realmSettings.GetSetting(Steam_RealmConfigNamespace, Steam_RealmConfigKey_Key);
            var uri = GetSteamGetPlayerSummariesUri(publisherToken, new[] { associatedSteamIdentity.userId });
            var response = await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, uri));

            // If the request succeeds, we deserialize the steam data and fill in any custom stats our game uses.
            if (response.IsSuccessStatusCode)
            {
                var responseBody = await response.Content.ReadAsStringAsync();

                SteamGetPlayerSummaryResponse playerSummary;
                try
                {
                    playerSummary = JsonConvert.DeserializeObject<SteamGetPlayerSummaryResponse>(responseBody);
                }
                catch (Exception)
                {
                    throw new MicroserviceException(500, "PlayerInitError", "Failed to deserialize response from Steam.");
                }

                var p = playerSummary.response.Players.FirstOrDefault();
                if (p == null)
                {
                    throw new MicroserviceException(404,
                        "INVALID_STEAM_USER_ID",
                        "Failed to find steam user associated with this account. You should never see this. If you do, you likely have a bug in your steam federation.");
                }

                outStartingStats["player_name"] = p.personaname;
                outStartingStats["avatar"] = p.avatar;
                outStartingStats["avatar_medium"] = p.avatarmedium;
                outStartingStats["avatar_full"] = p.avatarfull;

                return;
            }

            Debug.Log($"Failed request, {response.StatusCode}: {response.RequestMessage}");
            throw new MicroserviceException((int)response.StatusCode, "PlayerInitError",
                $"Failed to connect to Steam: {response.ReasonPhrase}. ExternalID={associatedSteamIdentity.userId}");
        }
    }

    /// <summary>
    /// Constructs the Steam Partner Web API URL for authenticating user session tickets.
    /// This endpoint validates that a user's Auth Session Ticket is valid and returns their Steam ID.
    /// See: https://partner.steamgames.com/doc/webapi/isteamuserauth
    /// </summary>
    private static string GetSteamAuthenticateUri(string ticket, string publisherToken, string appId) => $"{Steam_BaseUri}/ISteamUserAuth/AuthenticateUserTicket/v1/?key={publisherToken}&appid={appId}&ticket={ticket}";

    /// <summary>
    /// Constructs the Steam Partner Web API URL for retrieving player profile summaries.
    /// Returns basic profile information including display name and avatar URLs for the specified Steam IDs.
    /// See: https://partner.steamgames.com/doc/webapi/isteamuser
    /// </summary>
    private static string GetSteamGetPlayerSummariesUri(string publisherToken, string[] userIds) => $"{Steam_BaseUri}/ISteamUser/GetPlayerSummaries/v2/?key={publisherToken}&steamids={string.Join(",", userIds)}";
    
}

/// <summary>
/// Response model for Steam's AuthenticateUserTicket API endpoint.
/// Returned when validating an Auth Session Ticket to authenticate a Steam user.
/// Contains the validated user's Steam ID and account status information.
/// See: https://partner.steamgames.com/doc/webapi/isteamuserauth
/// </summary>
[Serializable]
public class SteamAuthenticateUserTicket
{
    public SteamResponse response { get; set; }

    [Serializable]
    public class SteamResponse
    {
        [JsonProperty(PropertyName = "params")]
        public SteamResponseParams ResponseParams { get; set; }
    }

    /// <summary>
    /// Contains authentication result data including the user's Steam ID and ban status.
    /// </summary>
    [Serializable]
    public class SteamResponseParams
    {
        /// <summary>
        /// Result status of the authentication attempt (typically "OK" for successful validation).
        /// </summary>
        public string result { get; set; }

        /// <summary>
        /// The authenticated user's unique Steam ID (SteamID64 format).
        /// </summary>
        public string steamid { get; set; }

        /// <summary>
        /// Steam ID of the game owner (matches steamid for owned games, differs for family shared games).
        /// </summary>
        public string ownersteamid { get; set; }

        /// <summary>
        /// Indicates if the user has a VAC (Valve Anti-Cheat) ban on their account.
        /// </summary>
        public bool vacbanned { get; set; }

        /// <summary>
        /// Indicates if the user has been banned by the game publisher.
        /// </summary>
        public bool publisherbanned { get; set; }
    }
}

/// <summary>
/// Response model for Steam's GetPlayerSummaries API endpoint.
/// Returned when requesting player profile information for one or more Steam users.
/// Contains basic profile data including display names and avatar URLs.
/// See: https://partner.steamgames.com/doc/webapi/isteamuser
/// </summary>
[Serializable]
public class SteamGetPlayerSummaryResponse
{
    public Body response { get; set; }

    [Serializable]
    public class Body
    {
        [JsonProperty(PropertyName = "players")]
        public Player[] Players { get; set; }
    }

    /// <summary>
    /// Contains basic Steam user profile information.
    /// </summary>
    [Serializable]
    public class Player
    {
        /// <summary>
        /// The player's unique Steam ID (SteamID64 format).
        /// </summary>
        public string steamid { get; set; }

        /// <summary>
        /// The player's current display name on Steam.
        /// </summary>
        public string personaname { get; set; }

        /// <summary>
        /// URL to the player's small (32x32) avatar image.
        /// </summary>
        public string avatar { get; set; }

        /// <summary>
        /// URL to the player's medium (64x64) avatar image.
        /// </summary>
        public string avatarmedium { get; set; }

        /// <summary>
        /// URL to the player's full-size (184x184) avatar image.
        /// </summary>
        public string avatarfull { get; set; }
    }
}