using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Lobby;
using Beamable.Api.Autogenerated.Models;
using Beamable.Api.Autogenerated.Playerparty;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Content;
using Beamable.Common.Dependencies;
using Beamable.Experimental.Api.Lobbies;
using Beamable.Server;
using Beamable.Server.Api.Leaderboards;
using Beamable.Server.Api.RealmConfig;
using Beamable.Server.Api.Stats;
using Newtonsoft.Json;
using UnityEngine;
using Lobby = Beamable.Experimental.Api.Lobbies.Lobby;

namespace Beamable.BeamballMs
{
    [FederationId("default")]
    public class DefaultFederation : IFederationId
    {
    }

    [FederationId("beamball")]
    public class BeamballFederation : IFederationId
    {
    }

    [Microservice("BeamballMs")]
    public partial class BeamballMs : Microservice, IFederatedPlayerInit<DefaultFederation>,
        IFederatedGameServer<BeamballFederation>
    {
        public async Promise<PlayerInitResult> CreatePlayer(Account account, Dictionary<string, string> properties)
        {
            var gamerTag = account.gamerTags[0].gamerTag;

            // Add Initial Currency and Skin
            const string defaultSkin = "items.itemskin.skin1";
            const string coinsCurrency = "currency.coins";

            // Initialize the stats and inventory that is true for ALL identities.
            var startingStats = new Dictionary<string, string>
            {
                { "player_name", "Guest User" },
                { "beamable.selected_skin", defaultSkin }
            };
            var startingInventory = new InventoryUpdateBuilder();
            startingInventory.CurrencyChange(coinsCurrency, 195);
            startingInventory.AddItem(defaultSkin, new Dictionary<string, string>());

            // Kick off tasks to fill out the appropriate starting data
            //  - Each of these functions are no-ops if the account is NOT being created with its expected identity.
            //  - This is just an example pattern for this sample; don't try to reuse it if it doesn't fit your player initialization logic.   
            await Task.WhenAll(new[]
            {
                CreatePlayerEmail(account, properties, startingStats, startingInventory),
                CreatePlayerSteam(account, properties, startingStats, startingInventory),
                CreatePlayerEos(account, properties, startingStats, startingInventory),
            });

            // Make just two requests with all the starting stats and starting inventory.
            var userAPI = AssumeNewUser(gamerTag);
            await userAPI.Services.Stats.SetStats(StatsDomainType.Client, StatsAccessType.Public, gamerTag,
                startingStats);
            await userAPI.Services.Inventory.Update(startingInventory);

            return new PlayerInitResult();
        }


        private async Task CreatePlayerEmail(Account account, Dictionary<string, string> properties,
            Dictionary<string, string> outStartingStats, InventoryUpdateBuilder outStartingInventory)
        {
            if (account.email.HasNonEmptyValue)
            {
                var emailSplited = account.email.GetOrThrow().Split("@");
                if (emailSplited.Length > 0) outStartingStats["player_name"] = emailSplited[0];
            }

            await Task.CompletedTask;
        }


        public async Promise<ServerInfo> CreateGameServer(Api.Autogenerated.Models.Lobby lobby)
        {
            var serverInfo = new ServerInfo();

            var isDynamicMatch = lobby.matchType.Value.id.Value.Contains("dynamic_match");

            var playerTeams = new Dictionary<string, string>();

            // If this is a dynamic match, assign players to teams here.
            // TODO: It is not considering the Party for the teams in the dynamic match.
            if (isDynamicMatch)
            {
                var lobbyPlayers = lobby.players.GetOrElse([]);
                var teamsContent = new string[] { "TeamA", "TeamB" };

                int teamIndex = 0;

                foreach (var player in lobbyPlayers)
                {
                    playerTeams.Add(player.playerId, teamsContent[teamIndex]);
                    teamIndex = (teamIndex + 1) % teamsContent.Length;
                }
            }

            // Use this function to parallelize: creating the lobby in your Orchestrator, preparing your lobby's Global Data and PlayerData dictionaries.
            await lobby.PrepareLobbyAsDedicatedServer(serverInfo,
                async l =>
                {
                    // IF the lobby is NOT a fake lobby from playmode, you should be provisioning a server.
                    var connInfo = new ServerInfo();
                    if (!l.IsLobbyFromEditorPlayMode())
                    {
                        var realmConfig = await Services.RealmConfig.GetRealmConfigSettings();

                        var gamerTags = lobby.players.Value.Select(p => long.Parse(p.playerId)).ToArray();

                        var assumedFakeLeader = AssumeNewUser(gamerTags.First());
                        // get the ping times for each player
                        var tasks = new List<Promise<Dictionary<string, string>>>(gamerTags.Length);
                        tasks.AddRange(gamerTags.Select(tag => assumedFakeLeader.Services.Stats.GetFilteredStats(StatsDomainType.Client, StatsAccessType.Public, tag, new string[] { "beam.edgegap.location" })));
                        var pingStats = await Promise.Sequence(tasks);

                        List<EdgegapLocation> edgegapLocations = new List<EdgegapLocation>();

                        if (pingStats.Count != 0)
                        {
                            foreach (var ping in pingStats)
                            {
                                if (ping.TryGetValue("beam.edgegap.location", out var value))
                                {
                                    var locationSplit = value.Split(";");

                                    edgegapLocations.Add(new EdgegapLocation()
                                    {
                                        longitude = double.Parse(locationSplit[0]),
                                        latitude = double.Parse(locationSplit[1])
                                    });
                                }
                            }
                        }


                        // Create the Edgegap Room
                        var edgegapRoom = await CreateEdgegapServer(realmConfig, l.lobbyId.Value, edgegapLocations);

                        // Start polling until its active or the initialization timed out.
                        var pollingInterval = TimeSpan.FromSeconds(1);
                        var startedAt = DateTime.Now;

                        // MaxWaitTime cannot be more than 2 minutes as the current Beamable-enforced timeout is set to 2 minutes.
                        var maxWaitTime = TimeSpan.FromSeconds(60);

                        // Spin for up-to-2-minutes and checking every "PollingInterval" for the connection to become active.
                        while (edgegapRoom.status != "Ready" &&
                               (DateTime.Now - startedAt).TotalSeconds < (maxWaitTime).TotalSeconds)
                        {
                            BeamableLogger.Log($"Room {l.lobbyId.Value} status: {edgegapRoom.status}");
                            await Task.Delay(pollingInterval);
                            edgegapRoom = await PollEdgegapGameServer(realmConfig, edgegapRoom.request_id);

                            if (edgegapRoom.status == "Error")
                            {
                                throw new Exception("Error On Edgegap Room Provisioning");
                            }
                        }

                        // It took to long to provision the server.
                        if (edgegapRoom.status != "Ready")
                        {
                            BeamableLogger.LogError(
                                $"Failed to provision game server in time for room. ROOM_ID={l.lobbyId.Value}, LAST_EDGEGAP_CONN_UPDATE={JsonUtility.ToJson(edgegapRoom)}");
                            throw new MicroserviceException(503, "FAILED_TO_PROVISION_GAME_SERVER_BEFORE_TIMEOUT",
                                JsonUtility.ToJson(edgegapRoom));
                        }

                        connInfo.globalData.Add("edgegap_request_id", edgegapRoom.request_id);

                        // Set the edgegap room information as the connection string for this lobby --- the Unreal SDK has utilities to read these properties.
                        // You can always pass them via your own properties.
                        connInfo.SetConnectionString(edgegapRoom.ip, edgegapRoom.port.ToString());
                    }

                    return connInfo;
                },
                _ =>
                {
                    // For this specific game, we don't need any global data computed here, but you could compute a map to play in or randomized objects or really anything.
                    return Task.FromResult(new ServerInfo());
                },
                async lp =>
                {
                    // For this game, we need to get the selected skin for each player and put them into the lobby's player data.
                    // You could compute more information such as a selected deck's information and embedded them in this dictionary.
                    // Computing things here and storing them in the lobby is a tradeoff:
                    //   - it allows the game-server to avoid fetching things once it boots up, but it increases the size of the lobby data structure.
                    //   - for most cases, this is a fine trade-off to make; but, think about your own case's specifics as you decided.
                    var data = new Dictionary<string, string>();
                    var existingSkinData = lp.tags.GetOrElse([])
                        .FirstOrDefault(t => t.name.GetOrElse("") == "beamable.selected_skin");
                    if (existingSkinData == null)
                    {
                        var gamerTag = long.Parse(lp.playerId.Value);
                        var selectedSkin = await Services.Stats.GetStat(StatsDomainType.Client, StatsAccessType.Public,
                            gamerTag, "beamable.selected_skin");
                        if (!string.IsNullOrEmpty(selectedSkin))
                        {
                            data["beamable.selected_skin"] = selectedSkin;
                        }
                    }

                    if (isDynamicMatch)
                    {
                        data["team"] = playerTeams[lp.playerId.Value];
                    }


                    return data;
                });

            // After the lobby is provisioned and wait until the service is ready to notify clients that the match was made.
            // When clients receive this notification, they will be ready to connect.
            await lobby.WaitForGameServerReady(Provider.GetService<IBeamLobbyApi>());

            return serverInfo;
        }

        [ServerCallable]
        public async Task<MatchResult> ProcessMatchResult(List<BeamballTeamInfo> teamInfos, string lobbyId)
        {
            BeamableLogger.Log("Creating match result for lobby " + lobbyId);

            var beamLobbyApi = Provider.GetService<IBeamLobbyApi>();
            if (!Guid.TryParse(lobbyId, out var lobbyGuid))
                throw new MicroserviceException(500, "INVALID_LOBBY_ID",
                    $"Provided Lobby ID was invalid. INVALID={lobbyId}.");

            Api.Autogenerated.Models.Lobby lobby = await beamLobbyApi.Get(lobbyGuid);
            var lobbyPlayers = lobby.players.GetOrElse([]);

            // Calculate total life for each team
            var teamLifeTotals = teamInfos.ToDictionary(
                team => team.TeamName,
                team => team.Players.Sum(p => p.Life)
            );

            // Determine match outcome
            string winningTeam = null;
            bool isDraw = false;

            if (teamLifeTotals.Count == 2)
            {
                var teams = teamLifeTotals.ToList();
                if (teams[0].Value == teams[1].Value)
                {
                    isDraw = true;
                }
                else
                {
                    winningTeam = teams[0].Value > teams[1].Value ? teams[0].Key : teams[1].Key;
                }
            }

            // Create match result
            var result = new MatchResult()
            {
                PerPlayerMatchResults = new Dictionary<string, PerPlayerMatchResult>()
            };

            var updates = new List<Task>();

            foreach (var player in lobbyPlayers)
            {
                var gamerTag = long.Parse(player.playerId.Value);

                // Find player's team
                var playerTeam = teamInfos.FirstOrDefault(t => t.Players.Any(p => p.GamerTag == player.playerId.Value));

                bool isWinner = !isDraw && playerTeam != null && playerTeam.TeamName == winningTeam;

                if (isWinner)
                {
                    var rng = new Random();
                    var rankedPoints = rng.Next(50, 100);
                    var coins = rng.Next(10, 25);

                    var newUser = AssumeNewUser(gamerTag);

                    updates.Add(newUser.Services.Leaderboards.SetScore("leaderboards.global", rankedPoints)
                        .TaskFromPromise());
                    updates.Add(newUser.Services.Inventory.AddCurrency("currency.coins", coins).TaskFromPromise());


                    result.PerPlayerMatchResults.Add(player.playerId.Value,
                        new PerPlayerMatchResult()
                        {
                            MatchResult = BeamballMatchResultEnum.Win, RankEarned = rankedPoints, CoinsEarned = coins
                        });
                }
                else
                {
                    if (isDraw)
                    {
                        result.PerPlayerMatchResults.Add(player.playerId.Value,
                            new PerPlayerMatchResult()
                                { MatchResult = BeamballMatchResultEnum.Draw, RankEarned = 0, CoinsEarned = 0 });
                    }
                    else
                    {
                        result.PerPlayerMatchResults.Add(player.playerId.Value,
                            new PerPlayerMatchResult()
                                { MatchResult = BeamballMatchResultEnum.Lose, RankEarned = 0, CoinsEarned = 0 });
                    }
                }
            }

            try
            {
                await Task.WhenAll(updates);
            }
            catch (Exception e)
            {
                BeamableLogger.LogError(e);
                throw;
            }

            // Remove all players from lobby

            List<Task> removeLobbyTaskList = new List<Task>();
            foreach (var player in lobbyPlayers)
            {
                removeLobbyTaskList.Add(beamLobbyApi.Delete(lobbyGuid, new RemoveFromLobby()
                {
                    playerId = player.playerId.Value
                }).TaskFromPromise());
            }

            await Task.WhenAll(removeLobbyTaskList);

            // Delete Server after the end of the match
            var realmConfig = await Services.RealmConfig.GetRealmConfigSettings();

            if (lobby.data.Value.TryGetValue("edgegap_request_id", out var requestId))
            {
                await DeleteEdgegapServer(realmConfig, requestId);
            }

            return result;
        }

        /// <summary>
        /// Utility function defining defaults and keys for the "edgegap_integration" realm-config namespace.
        /// These must be correctly set up in your realm for this microservice to work. 
        /// </summary>
        private static EdgegapRealmConfig GetEdgegapRealmConfig(RealmConfig config)
        {
            const string kNamespaceEdgegapIntegration = "edgegap_integration";
            const string kKeyAppKey = "app_key";
            const string kKeyAppName = "app_name";
            const string kKeyAppVersion = "app_version";
            const string kKeyFallbackRegion = "fallback_region";
            const string kKeyEdgegapURL = "edgegap_url";


            var edgegapRealmConfig = new EdgegapRealmConfig()
            {
                AppName = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppName),
                AppKey = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppKey),
                AppVersion = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppVersion),
                FallbackRegion = config.GetSetting(kNamespaceEdgegapIntegration, kKeyFallbackRegion, "Seattle"),
                EdgegapURL = new Uri(config.GetSetting(kNamespaceEdgegapIntegration, kKeyEdgegapURL,
                    "https://api.edgegap.com"))
            };

            return edgegapRealmConfig;
        }

        public static async Task<bool> DeleteEdgegapServer(RealmConfig config,
            string requestId)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);

            var url = "https://api.edgegap.com/v1/stop/" + requestId;


            var http = new HttpClient();
            http.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("token", edgegapRealmConfig.AppKey);

            var response = await http.DeleteAsync(
                url
            );

            await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                return false;

            return true;
        }

        public static async Task<EdgegapConnectionInfo> CreateEdgegapServer(RealmConfig config,
            string lobbyId, List<EdgegapLocation> edgegapLocations)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);

            var url = "https://api.edgegap.com/v2/deployments";

            var body = new EdgegapCreateDeploymentRequestV2
            {
                application = edgegapRealmConfig.AppName,
                version = edgegapRealmConfig.AppVersion,

                // required in v2
                users = edgegapLocations.Select(item => new EdgegapUser()
                {
                    user_type = "geo_coordinates",
                    user_data = new EdgegapUserData
                    {
                        latitude = (float)item.latitude,
                        longitude = (float)item.longitude
                    }
                }).ToArray(),

                environment_variables = new[]
                {
                    new EdgegapEnvVar
                    {
                        key = "BEAMABLE_DEDICATED_SERVER_INSTANCE_LOBBY_ID",
                        value = lobbyId,
                        is_hidden = false
                    }
                }
            };

            var json = JsonConvert.SerializeObject(body);

            var http = new HttpClient();
            http.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("token", edgegapRealmConfig.AppKey);

            var response = await http.PostAsync(
                url,
                new StringContent(json, Encoding.UTF8, "application/json")
            );

            var content = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                throw new Exception(content);

            return JsonConvert.DeserializeObject<EdgegapConnectionInfo>(content);
        }

        //Takes in the requestId and calls the Edgegap API to get their connection information/state.
        /// We use this to wait until the server is provisioned before notifying players that the match is ready.
        private static async Task<EdgegapConnectionInfo> PollEdgegapGameServer(
            RealmConfig config,
            string requestId)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);

            var getUri = new Uri(
                edgegapRealmConfig.EdgegapURL,
                $"v1/status/{requestId}"
            );

            var http = new HttpClient();

            http.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("token", edgegapRealmConfig.AppKey);

            var response = await http.GetAsync(getUri);
            var content = await response.Content.ReadAsStringAsync();

            BeamableLogger.Log("Get ConnectionInfo Edgegap Response: " + content);

            if (!response.IsSuccessStatusCode)
            {
                return new EdgegapConnectionInfo()
                {
                    request_id = requestId,
                    status = "Error",
                    ip = "",
                    port = 0
                };
            }

            var deployment =
                JsonConvert.DeserializeObject<EdgegapDeploymentStatusResponse>(content);

            string ip = "";
            int port = 0;

            if (deployment?.ports != null &&
                deployment.ports.TryGetValue("gameport", out var gamePort))
            {
                ip = gamePort.link.Split(":")[0];
                port = int.Parse(gamePort.link.Split(":")[1]);
            }

            return new EdgegapConnectionInfo
            {
                request_id = requestId,
                status = deployment?.current_status_label,
                ports = deployment?.ports,
                ip = ip,
                port = port
            };
        }
    }

    [Serializable]
    public class EdgegapRealmConfig
    {
        public string AppName;
        public string AppKey;
        public string AppVersion;
        public string FallbackRegion;
        public Uri EdgegapURL;
    }

    [Serializable]
    public class BeamballTeamInfo
    {
        public string TeamName;
        public List<BeamballPlayerInfo> Players;
    }

    [Serializable]
    public class BeamballPlayerInfo
    {
        public string GamerTag;
        public int Life;
    }

    [Serializable]
    public enum BeamballMatchResultEnum
    {
        Win,
        Lose,
        Draw
    }

    [Serializable]
    public class MatchResult
    {
        public Dictionary<string, PerPlayerMatchResult> PerPlayerMatchResults;
    }

    [Serializable]
    public class PerPlayerMatchResult
    {
        public BeamballMatchResultEnum MatchResult;
        public int RankEarned;
        public int CoinsEarned;
    }

    public class EdgegapCreateDeploymentRequestV2
    {
        public string application;
        public string version;
        public EdgegapUser[] users;
        public EdgegapEnvVar[] environment_variables;
    }

    public class EdgegapUser
    {
        public string user_type;
        public EdgegapUserData user_data;
    }

    public class EdgegapUserData
    {
        // public string ip_address;
        public float latitude;
        public float longitude;
    }

    public class EdgegapEnvVar
    {
        public string key;
        public string value;
        public bool is_hidden;
    }

    public class EdgegapConnectionInfo
    {
        public string request_id;
        public string status;

        public Dictionary<string, EdgegapPort> ports;

        public string ip;
        public int port;

        public bool IsReady => status == "READY";
    }

    public class EdgegapDeploymentStatusResponse
    {
        public string request_id { get; set; }
        public string fqdn { get; set; }
        public string app_name { get; set; }
        public string app_version { get; set; }

        public string current_status { get; set; }
        public string current_status_label { get; set; }

        public bool running { get; set; }

        public bool error { get; set; }

        public string public_ip { get; set; }
        public bool whitelisting_active { get; set; }

        public Dictionary<string, EdgegapPort> ports { get; set; }

        public string command { get; set; }
        public string arguments { get; set; }

        public int max_duration { get; set; }

        public string last_status { get; set; }
        public string last_status_label { get; set; }

        public EdgegapLocation location { get; set; }
    }

    public class EdgegapPort
    {
        public string protocol { get; set; }
        public string name { get; set; }
        public bool tls_upgrade { get; set; }
        public string link { get; set; }
        public string proxy { get; set; }
    }

    public class EdgegapLocation
    {
        public string city { get; set; }
        public string country { get; set; }
        public string continent { get; set; }
        public string administrative_division { get; set; }
        public string timezone { get; set; }

        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}