using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Lobby;
using Beamable.Common;
using Beamable.Common.Api.Stats;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Newtonsoft.Json;
using UnityEngine;

namespace Beamable.BeamballMs
{
    [FederationId("beamball")]
    public class BeamballFederation : IFederationId
    {
    }
    
    public partial class BeamballMs :  IFederatedGameServer<BeamballFederation> {
        
        public const string EdgegapLocationStatKey = "beam.edgegap.location";
        
        public async Promise<ServerInfo> CreateGameServer(Api.Autogenerated.Models.Lobby lobby)
        {
            var serverInfo = new ServerInfo();

            var isDynamicMatch = lobby.matchType.Value.id.Value.Contains("dynamic_match");

            var playerTeams = new Dictionary<string, string>();

            // If this is a dynamic match, assign players to teams here.
            if (isDynamicMatch)
            {
                var lobbyPlayers = lobby.players.GetOrElse([]);
                var teamsContent = new string[] { "TeamA", "TeamB" };

                int teamIndex = 0;

                foreach (var player in lobbyPlayers)
                {
                    playerTeams.Add(player.playerId, teamsContent[teamIndex]);
                    teamIndex = (teamIndex + 1) % teamsContent.Length;
                }
            }

            // Use this function to parallelize: creating the lobby in your Orchestrator, preparing your lobby's Global Data and PlayerData dictionaries.
            await lobby.PrepareLobbyAsDedicatedServer(serverInfo,
                async l =>
                {
                    // IF the lobby is NOT a fake lobby from playmode, you should be provisioning a server.
                    var connInfo = new ServerInfo();
                    if (!l.IsLobbyFromEditorPlayMode())
                    {
                        var realmConfig = await Services.RealmConfig.GetRealmConfigSettings();

                        var gamerTags = lobby.players.Value.Select(p => long.Parse(p.playerId)).ToArray();

                        var assumedFakeLeader = AssumeNewUser(gamerTags.First());
                        // get the ping times for each player
                        var tasks = new List<Promise<Dictionary<string, string>>>(gamerTags.Length);
                        tasks.AddRange(gamerTags.Select(tag =>
                            assumedFakeLeader.Services.Stats.GetFilteredStats(StatsDomainType.Client,
                                StatsAccessType.Private, tag, new string[] { EdgegapLocationStatKey })));
                        var pingStats = await Promise.Sequence(tasks);

                        List<EdgegapLocation> edgegapLocations = new List<EdgegapLocation>();

                        if (pingStats.Count != 0)
                        {
                            foreach (var ping in pingStats)
                            {
                                if (ping.TryGetValue(EdgegapLocationStatKey, out var value))
                                {
                                    var locationSplit = value.Split(";");

                                    edgegapLocations.Add(new EdgegapLocation()
                                    {
                                        longitude = double.Parse(locationSplit[0]),
                                        latitude = double.Parse(locationSplit[1])
                                    });
                                }
                            }
                        }


                        // Create the Edgegap Room
                        var edgegapRoom = await CreateEdgegapServer(realmConfig, l.lobbyId.Value, edgegapLocations);

                        // Start polling until its active or the initialization timed out.
                        var pollingInterval = TimeSpan.FromSeconds(1);
                        var startedAt = DateTime.Now;

                        // MaxWaitTime cannot be more than 2 minutes as the current Beamable-enforced timeout is set to 2 minutes.
                        var maxWaitTime = TimeSpan.FromSeconds(60);

                        // Spin for up-to-2-minutes and checking every "PollingInterval" for the connection to become active.
                        while (edgegapRoom.status != "Ready" &&
                               (DateTime.Now - startedAt).TotalSeconds < (maxWaitTime).TotalSeconds)
                        {
                            BeamableLogger.Log($"Room {l.lobbyId.Value} status: {edgegapRoom.status}");
                            await Task.Delay(pollingInterval);
                            edgegapRoom = await PollEdgegapGameServer(realmConfig, edgegapRoom.request_id);

                            if (edgegapRoom.status == "Error")
                            {
                                throw new Exception("Error On Edgegap Room Provisioning");
                            }
                        }

                        // It took to long to provision the server.
                        if (edgegapRoom.status != "Ready")
                        {
                            BeamableLogger.LogError(
                                $"Failed to provision game server in time for room. ROOM_ID={l.lobbyId.Value}, LAST_EDGEGAP_CONN_UPDATE={JsonUtility.ToJson(edgegapRoom)}");
                            throw new MicroserviceException(503, "FAILED_TO_PROVISION_GAME_SERVER_BEFORE_TIMEOUT",
                                JsonUtility.ToJson(edgegapRoom));
                        }

                        connInfo.globalData.Add("edgegap_request_id", edgegapRoom.request_id);

                        // Set the edgegap room information as the connection string for this lobby --- the Unreal SDK has utilities to read these properties.
                        // You can always pass them via your own properties.
                        connInfo.SetConnectionString(edgegapRoom.ip, edgegapRoom.port.ToString());
                    }

                    return connInfo;
                },
                _ =>
                {
                    // For this specific game, we don't need any global data computed here, but you could compute a map to play in or randomized objects or really anything.
                    return Task.FromResult(new ServerInfo());
                },
                async lp =>
                {
                    // For this game, we need to get the selected skin for each player and put them into the lobby's player data.
                    // You could compute more information such as a selected deck's information and embedded them in this dictionary.
                    // Computing things here and storing them in the lobby is a tradeoff:
                    //   - it allows the game-server to avoid fetching things once it boots up, but it increases the size of the lobby data structure.
                    //   - for most cases, this is a fine trade-off to make; but, think about your own case's specifics as you decided.
                    var data = new Dictionary<string, string>();
                    var existingSkinData = lp.tags.GetOrElse([])
                        .FirstOrDefault(t => t.name.GetOrElse("") == "beamable.selected_skin");
                    if (existingSkinData == null)
                    {
                        var gamerTag = long.Parse(lp.playerId.Value);
                        var selectedSkin = await Services.Stats.GetStat(StatsDomainType.Client, StatsAccessType.Public,
                            gamerTag, "beamable.selected_skin");
                        if (!string.IsNullOrEmpty(selectedSkin))
                        {
                            data["beamable.selected_skin"] = selectedSkin;
                        }
                    }

                    if (isDynamicMatch)
                    {
                        data["team"] = playerTeams[lp.playerId.Value];
                    }


                    return data;
                });

            // After the lobby is provisioned and wait until the service is ready to notify clients that the match was made.
            // When clients receive this notification, they will be ready to connect.
            await lobby.WaitForGameServerReady(Provider.GetService<IBeamLobbyApi>());

            return serverInfo;
        }
        
        /// <summary>
        /// The SetEdgegapLocation function is a utility function that players can call to set their location information in their stats.
        /// This is used to send Edgegap the player's location so they can pick the best region to host the server.
        /// </summary>
        /// <param name="latitude"></param>
        /// <param name="longitude"></param>
        [ClientCallable]
        public async Task SetEdgegapLocation(float latitude, float longitude)
        {
            await Services.Stats.SetStats(StatsDomainType.Client, StatsAccessType.Private, Context.UserId, new Dictionary<string, string>()
            {
                {EdgegapLocationStatKey, $"{latitude};{longitude}"}
            });
        }
        
        /// <summary>
        /// Utility function defining defaults and keys for the "edgegap_integration" realm-config namespace.
        /// These must be correctly set up in your realm for this microservice to work. 
        /// </summary>
        private static EdgegapRealmConfig GetEdgegapRealmConfig(RealmConfig config)
        {
            const string kNamespaceEdgegapIntegration = "edgegap_integration";
            const string kKeyAppKey = "app_key";
            const string kKeyAppName = "app_name";
            const string kKeyAppVersion = "app_version";
            const string kKeyEdgegapURL = "edgegap_url";


            var edgegapRealmConfig = new EdgegapRealmConfig()
            {
                AppName = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppName),
                AppKey = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppKey),
                AppVersion = config.GetSetting(kNamespaceEdgegapIntegration, kKeyAppVersion),
                EdgegapURL = new Uri(config.GetSetting(kNamespaceEdgegapIntegration, kKeyEdgegapURL,
                    "https://api.edgegap.com"))
            };

            return edgegapRealmConfig;
        }
        
        /// <summary>
        /// We are using the Edgegap "stop" endpoint to delete the server that was provisioned for this lobby.
        /// You can check more in the documentation https://docs.edgegap.com/docs/api/dedicated-servers#delete-v1-stop-request_id
        /// </summary>
        /// <param name="config"></param>
        /// <param name="requestId"></param>
        /// <returns></returns>
        public static async Task<bool> DeleteEdgegapServer(RealmConfig config,
            string requestId)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);

            var url = "https://api.edgegap.com/v1/stop/" + requestId;
            
            
            var http = new HttpClient();
            http.DefaultRequestHeaders.Add("Authorization", edgegapRealmConfig.AppKey);

            var response = await http.DeleteAsync(
                url
            );

            await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                return false;

            return true;
        }

        /// <summary>
        /// This is the function that creates the Edgegap server for a given lobby.
        /// It takes in the lobby's location information to pass it to Edgegap so they can pick the best region to host the server.
        /// You can check more in the documentation https://docs.edgegap.com/docs/api/dedicated-servers#post-deployments
        /// </summary>
        /// <param name="config"></param>
        /// <param name="lobbyId"></param>
        /// <param name="edgegapLocations"></param>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        public static async Task<EdgegapConnectionInfo> CreateEdgegapServer(RealmConfig config,
            string lobbyId, List<EdgegapLocation> edgegapLocations)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);
            
            var url = "https://api.edgegap.com/v2/deployments";

            var body = new EdgegapCreateDeploymentRequestV2
            {
                application = edgegapRealmConfig.AppName,
                version = edgegapRealmConfig.AppVersion,

                // required in v2
                users = edgegapLocations.Select(item => new EdgegapUser()
                {
                    user_type = "geo_coordinates",
                    user_data = new EdgegapUserData
                    {
                        latitude = (float)item.latitude,
                        longitude = (float)item.longitude
                    }
                }).ToArray(),

                environment_variables = new[]
                {
                    new EdgegapEnvVar
                    {
                        // The key is used by the game server to identify which lobby this server is for.
                        key = "BEAMABLE_DEDICATED_SERVER_INSTANCE_LOBBY_ID",
                        value = lobbyId,
                        is_hidden = false
                    }
                }
            };

            var json = JsonConvert.SerializeObject(body);

            var http = new HttpClient();
            http.DefaultRequestHeaders.Add("Authorization", edgegapRealmConfig.AppKey);
            
            var response = await http.PostAsync(
                url,
                new StringContent(json, Encoding.UTF8, "application/json")
            );

            var content = await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
                throw new Exception(content);

            return JsonConvert.DeserializeObject<EdgegapConnectionInfo>(content);
        }
        

       /// <summary>
       /// Takes in the requestId and calls the Edgegap API to get their connection information/state.
       /// We use this to wait until the server is provisioned before notifying players that the match is ready.
       /// You can check more on the documentation https://docs.edgegap.com/docs/api/dedicated-servers#get-v1-status-request_id
       /// </summary>
       /// <param name="config"></param>
       /// <param name="requestId"></param>
       /// <returns></returns>
        private static async Task<EdgegapConnectionInfo> PollEdgegapGameServer(
            RealmConfig config,
            string requestId)
        {
            var edgegapRealmConfig = GetEdgegapRealmConfig(config);

            var getUri = new Uri(
                edgegapRealmConfig.EdgegapURL,
                $"v1/status/{requestId}"
            );

            var http = new HttpClient();
            
            http.DefaultRequestHeaders.Add("Authorization", edgegapRealmConfig.AppKey);

            var response = await http.GetAsync(getUri);
            var content = await response.Content.ReadAsStringAsync();

            BeamableLogger.Log("Get ConnectionInfo Edgegap Response: " + content);

            if (!response.IsSuccessStatusCode)
            {
                return new EdgegapConnectionInfo()
                {
                    request_id = requestId,
                    status = "Error",
                    ip = "",
                    port = 0
                };
            }

            var deployment =
                JsonConvert.DeserializeObject<EdgegapDeploymentStatusResponse>(content);

            string ip = "";
            int port = 0;

            if (deployment?.ports != null &&
                deployment.ports.TryGetValue("gameport", out var gamePort))
            {
                ip = gamePort.link.Split(":")[0];
                port = int.Parse(gamePort.link.Split(":")[1]);
            }

            return new EdgegapConnectionInfo
            {
                request_id = requestId,
                status = deployment?.current_status_label,
                ports = deployment?.ports,
                ip = ip,
                port = port
            };
        }
    }
    // Serializable classes to call the Edgegap API and parse their responses. 
    // You can check more in the documentation https://docs.edgegap.com/docs/api/dedicated-servers
    
    [Serializable]
    public class EdgegapRealmConfig
    {
        public string AppName;
        public string AppKey;
        public string AppVersion;
        public Uri EdgegapURL;
    }
    
    public class EdgegapCreateDeploymentRequestV2
    {
        public string application;
        public string version;
        public EdgegapUser[] users;
        public EdgegapEnvVar[] environment_variables;
    }
    
    public class EdgegapUser
    {
        public string user_type;
        public EdgegapUserData user_data;
    }
    
    public class EdgegapUserData
    {
        // public string ip_address;
        public float latitude;
        public float longitude;
    }
    
    public class EdgegapEnvVar
    {
        public string key;
        public string value;
        public bool is_hidden;
    }
    
    public class EdgegapConnectionInfo
    {
        public string request_id;
        public string status;

        public Dictionary<string, EdgegapPort> ports;
        
        public string ip;
        public int port;

        public bool IsReady => status == "READY";
    }
    
    public class EdgegapDeploymentStatusResponse
    {
        public string request_id { get; set; }
        public string fqdn { get; set; }
        public string app_name { get; set; }
        public string app_version { get; set; }

        public string current_status { get; set; }
        public string current_status_label { get; set; }

        public bool running { get; set; }
        
        public bool error { get; set; }

        public string public_ip { get; set; }
        public bool whitelisting_active { get; set; }

        public Dictionary<string, EdgegapPort> ports { get; set; }

        public string command { get; set; }
        public string arguments { get; set; }

        public int max_duration { get; set; }

        public string last_status { get; set; }
        public string last_status_label { get; set; }

        public EdgegapLocation location { get; set; }
    }
    
    public class EdgegapPort
    {
        public string protocol { get; set; }
        public string name { get; set; }
        public bool tls_upgrade { get; set; }
        public string link { get; set; }
        public string proxy { get; set; }
    }
    
    public class EdgegapLocation
    {
        public string city { get; set; }
        public string country { get; set; }
        public string continent { get; set; }
        public string administrative_division { get; set; }
        public string timezone { get; set; }

        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}