// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "BeamLogging.h"
#include "WebSocketsModule.h"
#include "Serialization/BeamJsonUtils.h"
#include "Subsystems/EngineSubsystem.h"
#include "Templates/Invoke.h"
#include "UserSlots/UserSlot.h"
#include "IWebSocket.h"
#include "UserSlots/BeamUserSlots.h"

#include <type_traits>

#include "BeamNotifications.generated.h"


class UBeamNotifications;
class UBeamUserSlots;
class UBeamBackend;

/**
 * Type of notification events emitted by a Beamable websocket connection.
 * Each value maps to one of the underlying UE IWebSocket callbacks (OnConnected, OnConnectionError, OnMessage, OnClosed).
 *
 * Connection-lifecycle events (Connected / ConnectionFailed / Closed) are dispatched to the per-socket connection handler
 * that was supplied to TryConnect/Connect. Per-message events (Message) are dispatched to the per-context-key handlers
 * registered via TrySubscribeForMessage.
 */
UENUM(BlueprintType)
enum ENotificationMessageType
{
	/** The websocket finished its handshake and is ready to receive messages. */
	BEAM_Connected,
	/** The websocket failed to connect (or the underlying transport reported a connection error). */
	BEAM_ConnectionFailed,
	/** The websocket received a payload from the server. The associated FNotificationMessage holds the routing key and JSON body. */
	BEAM_Message,
	/** The websocket has been closed by either side. */
	BEAM_Closed
};

/**
 * Identifies a single open websocket connection inside UBeamNotifications.
 *
 * Every websocket Beamable opens is keyed by a (NamespacedSlot, Id) pair:
 *  - NamespacedSlot is produced by UBeamUserSlots::GetNamespacedSlotId(Slot, ContextObject), so the same slot name
 *    in different PIE worlds (or under different ContextObjects) maps to distinct sockets — that is what keeps
 *    PIE clients from sharing a single websocket.
 *  - Id is the logical socket name (e.g. UBeamRuntime::DefaultNotificationChannel for the per-player notification
 *    channel that BeamRuntime opens during sign-in). Subsystems that need their own private channel can connect
 *    additional sockets under their own Ids.
 *
 * The handle is built and returned by TryConnect/Connect/TryGetHandle and is used as the key when subscribing,
 * unsubscribing, or reconnecting.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FBeamWebSocketHandle
{
	GENERATED_BODY()

	/** Owning user, namespaced by the ContextObject's world (PIE-safe). Generated by UBeamUserSlots::GetNamespacedSlotId. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FString NamespacedSlot;

	/** Logical socket name. Identical Ids on different NamespacedSlots are different sockets. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FName Id;

	FBeamWebSocketHandle() = default;

	FBeamWebSocketHandle(const FString& Owner, const FName& Id, UBeamNotifications* Socket)
		: NamespacedSlot(Owner),
		  Id(Id),
		  Socket(Socket)
	{
	}

	friend bool operator==(const FBeamWebSocketHandle& Lhs, const FBeamWebSocketHandle& RHS)
	{
		return Lhs.Id == RHS.Id && Lhs.NamespacedSlot == RHS.NamespacedSlot;
	}

	friend bool operator!=(const FBeamWebSocketHandle& Lhs, const FBeamWebSocketHandle& RHS)
	{
		return !(Lhs == RHS);
	}

private:
	/** Back-pointer to the system that owns this connection. Only kept so that the handle can identify its origin. */
	UPROPERTY()
	UBeamNotifications* Socket = nullptr;
};

/** Hash combining Id and NamespacedSlot so handles can be used as TMap keys. */
FORCEINLINE uint32 GetTypeHash(const FBeamWebSocketHandle& SocketHandle) { return HashCombine(GetTypeHash(SocketHandle.Id), GetTypeHash(SocketHandle.NamespacedSlot)); }

/**
 * Payload for ENotificationMessageType::BEAM_Connected. Echoes back the handle that just finished connecting so
 * downstream code can correlate the event with the socket without bookkeeping its own (slot, id) tuple.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FNotificationConnected
{
	GENERATED_BODY()

	/** Handle of the socket whose connection just completed. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FBeamWebSocketHandle ConnectedHandle;
};

/**
 * Payload for ENotificationMessageType::BEAM_ConnectionFailed. Reports the transport error and how many reconnect
 * attempts have been made so retry/backoff strategies can act on it.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FNotificationConnectionFailed
{
	GENERATED_BODY()

	/** Underlying error string returned by the websocket layer. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FString Error;

	/** Number of consecutive reconnect attempts the system has already made for this socket. Reset to 0 once a connection succeeds. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	int RetryCount = 0;
};

/**
 * Payload for ENotificationMessageType::BEAM_Message. Carries the routing key (Context) and a JSON body (MessageFull).
 *
 * The body is intentionally kept as a string here so the dispatcher can pick the user-supplied TMessage type at the
 * subscription site and deserialize directly into it via FBeamJsonSerializable::BeamDeserialize.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FNotificationMessage : public FBeamJsonSerializableUStruct
{
	GENERATED_BODY()

	/**
	 * Unique routing key naming the "type" of this message. Subscribers select messages by matching this key.
	 * Examples shipped with Beamable:
	 *  - "content.refresh"   — a new content manifest was published in the connected realm.
	 *  - "inventory.refresh" — the player's inventory changed and clients should re-fetch the listed scopes.
	 *  - "lobby.update"      — the lobby this player is in changed.
	 *
	 * Custom microservices emit their own keys via Services.Notifications.NotifyPlayer(playerId, "<key>", payload).
	 */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FString Context;

	/** Raw JSON body of the notification. Deserialized into a concrete TMessage type by TrySubscribeForMessage. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FString MessageFull;

	virtual void BeamSerializeProperties(TUnrealJsonSerializer& Serializer) const override
	{
		Serializer->WriteValue(TEXT("context"), Context);
		Serializer->WriteValue(TEXT("messageFull"), MessageFull);
	}

	virtual void BeamSerializeProperties(TUnrealPrettyJsonSerializer& Serializer) const override
	{
		Serializer->WriteValue(TEXT("context"), Context);
		Serializer->WriteValue(TEXT("messageFull"), MessageFull);
	}

	virtual void BeamDeserializeProperties(const TSharedPtr<FJsonObject>& Bag) override
	{
		Context = Bag->GetStringField(TEXT("context"));
		MessageFull = Bag->GetStringField(TEXT("messageFull"));
	}
};

/**
 * Payload for ENotificationMessageType::BEAM_Closed. Mirrors UE's IWebSocket::OnClosed callback parameters.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FNotificationClosed
{
	GENERATED_BODY()

	/** WebSocket close code. UBeamNotifications::UserSignOutCloseCode (9999) means we closed the socket because the user signed out. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	int32 StatusCode = 0;

	/** Human-readable reason supplied at close time. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FString Reason;

	/** True when the close handshake completed cleanly on both sides. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	bool bWasClean = false;
};

/**
 * Single union-style envelope for any notification event. EventType selects which of the *Data fields is populated.
 *
 * A real C++ tagged-union (std::variant) would be cleaner but Blueprints don't have a way to consume them, so we
 * pay the slight memory cost of inline-storing every variant and let callers branch on EventType.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FNotificationEvent
{
	GENERATED_BODY()

	/** Discriminator for which *Data field below is meaningful for this event. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	TEnumAsByte<ENotificationMessageType> EventType = BEAM_Connected;

	/** Populated only when EventType == BEAM_Connected. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FNotificationConnected ConnectedData;

	/** Populated only when EventType == BEAM_ConnectionFailed. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FNotificationConnectionFailed ConnectionFailedData;

	/** Populated only when EventType == BEAM_Closed. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FNotificationClosed ClosedData;

	/** Populated only when EventType == BEAM_Message. */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Category="Beam")
	FNotificationMessage MessageData;
};

/**
 * Single-cast delegate fired for every notification event on a given socket.
 * Used by TryConnect/Connect for connection-lifecycle handlers and internally by TrySubscribeForMessage to wrap
 * per-context-key handlers.
 */
DECLARE_DELEGATE_OneParam(FOnNotificationEvent, const FNotificationEvent&);

/**
 * Internal record bookkeeping a single (ContextKey -> Handler) pair stored in MessageEventHandlers.
 * Equality compares by ContextKey so TMultiMap lookups can find all handlers registered for a context key,
 * while still letting individual entries be removed via TryUnsubscribeFromMessage by additionally matching the
 * underlying delegate handle.
 */
USTRUCT()
struct FNotificationMessageEventHandler
{
	GENERATED_BODY()

	FNotificationMessageEventHandler() = default;

	FNotificationMessageEventHandler(const FString& Key, const FOnNotificationEvent& Delegate) : ContextKey(Key), Handler(Delegate)
	{
	}

	friend bool operator==(const FNotificationMessageEventHandler& Lhs, const FNotificationMessageEventHandler& RHS)
	{
		return Lhs.ContextKey == RHS.ContextKey;
	}

	friend bool operator!=(const FNotificationMessageEventHandler& Lhs, const FNotificationMessageEventHandler& RHS)
	{
		return !(Lhs == RHS);
	}


	/** Routing key (matches FNotificationMessage::Context). */
	FString ContextKey;
	/** Wraps the user's TMessage-typed handler in a FOnNotificationEvent so the dispatcher can call all subscribers uniformly. */
	FOnNotificationEvent Handler;
};

/** Hash by ContextKey so a TMultiMap of these can be probed efficiently. */
FORCEINLINE uint32 GetTypeHash(const FNotificationMessageEventHandler& MessageEventHandler) { return GetTypeHash(MessageEventHandler.ContextKey); }

/**
 * Convenience base type for notification message structs that don't need any payload of their own — pure "ping" events.
 * Custom message structs should usually inherit from FBeamJsonSerializableUStruct directly when they have fields.
 */
USTRUCT()
struct FBeamBaseNotificationMessage : public FBeamJsonSerializableUStruct
{
	GENERATED_BODY()
};

/**
 * Blueprint-friendly opaque wrapper around an FDelegateHandle.
 *
 * The internal FDelegateHandle is intentionally not BP-exposed — Blueprint code receives this struct as the result
 * of a Subscribe-Custom-Notification node and passes it back unmodified to the Unsubscribe node. Treat it as opaque.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FBeamDelegateHandle
{
	GENERATED_BODY()

	FBeamDelegateHandle() = default;
	explicit FBeamDelegateHandle(const FDelegateHandle& InHandle) : Handle(InHandle) {}

	FDelegateHandle Handle;
};

/**
 * Opaque payload routed to BP dynamic delegates when a custom notification carrying a USTRUCT message arrives.
 *
 * Used exclusively by the SubscribeToCustomNotification K2Node — never construct, store, or read this struct directly
 * from a BP graph. The K2Node inserts a CustomThunk (UBeamNotifications::K2_CopyNotificationStructPayload) inside the
 * generated CustomEvent body that copies Data into a typed struct pin you authored.
 *
 * Lifetime: Type and Data are valid only for the synchronous duration of the dispatch call. The buffer pointed to by
 * Data lives on the dispatcher's stack frame and is destroyed immediately after every bound handler runs — do not
 * cache it.
 */
USTRUCT(BlueprintType)
struct BEAMABLECORE_API FBeamCustomNotificationStructPayload
{
	GENERATED_BODY()

	UScriptStruct* Type = nullptr;
	void* Data = nullptr;
};

/**
 * Dynamic delegate carrying a USTRUCT message payload for the SubscribeToCustomNotification K2Node's struct mode.
 * The K2Node's expansion calls UBeamNotifications::K2_CopyNotificationStructPayload to decode Payload into the user's
 * typed wildcard struct pin before exec runs, so the Payload struct is purely an internal transport.
 */
DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnBeamCustomNotificationStructDynamic,
	FBeamCustomNotificationStructPayload, Payload, FString, Key);

/**
 * Dynamic delegate carrying a UObject message payload for the SubscribeToCustomNotification K2Node's object mode.
 * The K2Node's expansion inserts a UK2Node_DynamicCast to the picked UClass to retype Object into the user's typed pin.
 */
DECLARE_DYNAMIC_DELEGATE_TwoParams(FOnBeamCustomNotificationObjectDynamic,
	UObject*, Object, FString, Key);

/**
 * Engine subsystem that owns every Beamable websocket connection in the running process.
 *
 * --------------------------------------------------------------------------------------------------------------------
 * Responsibilities
 * --------------------------------------------------------------------------------------------------------------------
 *  - Opens, holds, and closes IWebSocket connections, keyed by (NamespacedSlot, Id) pairs (see FBeamWebSocketHandle).
 *  - Routes connection-lifecycle events (Connected/ConnectionFailed/Closed) to a single per-socket handler.
 *  - Routes per-message events to as many subscribers as want them, demultiplexed by FNotificationMessage::Context.
 *  - Handles PIE-only connection cleanup via ClearPIESockets / PlayModeHandles bookkeeping.
 *  - Tracks reconnect attempts (RetryCount) and exposes Reconnect for higher-level retry policies.
 *
 * BeamRuntime opens one socket per signed-in player on sign-in (Id == UBeamRuntime::DefaultNotificationChannel) and
 * closes it on sign-out. Game code rarely talks to UBeamNotifications directly — it goes through one of two layers
 * built on top of it.
 *
 * --------------------------------------------------------------------------------------------------------------------
 * Default path: receiving notifications a custom microservice emits to a player
 * --------------------------------------------------------------------------------------------------------------------
 *
 *  >>> If your custom C# microservice calls Services.Notifications.NotifyPlayer(playerId, "your.key", payload):       <<<
 *  >>>   - C++:        UBeamRuntime::SubscribeToCustomNotification<THandler, TMessage>(slot, "your.key", handler).    <<<
 *  >>>   - Blueprint:  drop the "Subscribe to Custom Notification" node (UK2BeamNode_SubscribeCustomNotification),    <<<
 *  >>>                 pick your message USTRUCT/UClass on the picker pin, wire the OnReceived exec + typed Message.  <<<
 *
 * Both single-call paths:
 *   - Look up the default notification socket BeamRuntime already opened for the signed-in player (no manual TryConnect).
 *   - Wire your handler to FNotificationMessage::Context == "your.key".
 *   - Deserialize the JSON payload directly into your typed message before invoking the handler.
 *
 * The C++ template additionally accepts ANY callable shape — single-cast TDelegate, multicast TMulticastDelegate
 * (Broadcast), lambda, function pointer.
 *
 * Canonical examples:
 *   - C++: UBeamableDiscord::OnUserSignedIn_Implementation subscribes to "matchmaking_refresh" emitted by
 *     BeamballMs.Discord.cs / DiscordBot.UpdateAccess and updates a cached whitelist flag from the payload.
 *   - Blueprint: a player BP drops the K2Node, picks FMyMessage as the MessageStruct, wires OnReceived → BP logic.
 *
 * Pair with UBeamRuntime::UnsubscribeToCustomNotification (C++) or the "Unsubscribe Custom Notification" node
 * (UK2BeamNode_UnsubscribeCustomNotification) on sign-out, passing back the FDelegateHandle / FBeamDelegateHandle
 * returned by the subscribe call.
 *
 * --------------------------------------------------------------------------------------------------------------------
 * Advanced path: a dedicated UEngineSubsystem wrapper (Inventory / Content recipe)
 * --------------------------------------------------------------------------------------------------------------------
 *
 * Reach for this only when SubscribeToCustomNotification isn't enough — i.e. the notification key is core to a feature
 * that needs:
 *  - A discoverable Blueprint-callable Subscribe node (UFUNCTION(BlueprintCallable)).
 *  - Both a dynamic delegate API for Blueprint and a code-path API returning FDelegateHandle.
 *  - A single header that co-locates the message struct, context-key constant, and delegate types so multiple
 *    subsystems / Blueprint graphs can share them cleanly.
 *
 * UBeamInventoryNotifications and UBeamContentNotifications are the in-sdk references. Recipe below.
 *
 * Step 1 — Define the message struct. Inherit FBeamJsonSerializableUStruct (or FBeamBaseNotificationMessage if there
 *          is no body) and implement BeamSerializeProperties / BeamDeserializeProperties for every field. Field names
 *          must match the JSON the microservice emits.
 *
 *     // Mirrors what BeamInventoryNotifications.h declares for "inventory.refresh":
 *     USTRUCT(BlueprintType)
 *     struct MYGAME_API FFooRefreshNotificationMessage : public FBeamJsonSerializableUStruct
 *     {
 *         GENERATED_BODY()
 *         UPROPERTY(BlueprintReadOnly) TArray<FString> Scopes;
 *         virtual void BeamSerializeProperties(TUnrealJsonSerializer& Serializer) const override;
 *         virtual void BeamSerializeProperties(TUnrealPrettyJsonSerializer& Serializer) const override;
 *         virtual void BeamDeserializeProperties(const TSharedPtr<FJsonObject>& Bag) override;
 *     };
 *
 * Step 2 — Declare the two delegate flavours. The CODE variant is for C++ callers (returns an FDelegateHandle they
 *          can later unsubscribe with). The DYNAMIC variant is the Blueprint-bindable counterpart.
 *
 *     DECLARE_DELEGATE_OneParam(FOnFooRefreshNotificationCode, FFooRefreshNotificationMessage);
 *     DECLARE_DYNAMIC_DELEGATE_OneParam(FOnFooRefreshNotification, FFooRefreshNotificationMessage, Evt);
 *
 * Step 3 — Declare the subsystem. It is a plain UEngineSubsystem (NOT a UBeamRuntimeSubsystem); it has no per-player
 *          state to manage, just a thin Blueprint surface area on top of TrySubscribeForMessage.
 *
 *     UCLASS(BlueprintType)
 *     class MYGAME_API UBeamFooNotifications : public UEngineSubsystem
 *     {
 *         GENERATED_BODY()
 *
 *         // Server-side context key. Must match the string passed to Services.Notifications.NotifyPlayer in your microservice.
 *         static const inline FString CTX_KEY_Foo_Refresh = TEXT("foo.refresh");
 *
 *         UPROPERTY() UBeamNotifications* Notifications;
 *         virtual void Initialize(FSubsystemCollectionBase& Collection) override;  // -> Notifications = Collection.InitializeDependency<UBeamNotifications>();
 *
 *     public:
 *         UFUNCTION(BlueprintCallable, DisplayName="Subscribe - Foo Refresh", Category="Beam", meta=(DefaultToSelf="ContextObject"))
 *         void SubscribeToFooRefresh(const FUserSlot& Slot, const FName& SocketName, const FOnFooRefreshNotification& Handler, UObject* ContextObject) const;
 *
 *         FDelegateHandle CPP_SubscribeToFooRefresh(const FUserSlot& Slot, const FName& SocketName, const FOnFooRefreshNotificationCode& Handler, UObject* ContextObject) const;
 *     };
 *
 * Step 4 — Implement both subscribe methods. They are one-liners that delegate to TrySubscribeForMessage and warn
 *          on failure (almost always means the user isn't signed in / the socket isn't open yet):
 *
 *     void UBeamFooNotifications::SubscribeToFooRefresh(const FUserSlot& Slot, const FName& SocketName, const FOnFooRefreshNotification& Handler, UObject* ContextObject) const
 *     {
 *         FDelegateHandle Handle;
 *         if (!Notifications->TrySubscribeForMessage<FOnFooRefreshNotification, FFooRefreshNotificationMessage>(Slot, SocketName, CTX_KEY_Foo_Refresh, Handler, Handle, ContextObject))
 *             UE_LOG(LogBeamNotifications, Warning, TEXT("Subscribe failed — socket not open. SLOT=%s, ID=%s"), *Slot.Name, *SocketName.ToString());
 *     }
 *     // CPP_SubscribeToFooRefresh is identical except for the delegate type and that it returns Handle.
 *
 * Step 5 — Hook it up from a UBeamRuntimeSubsystem. The standard place is OnUserSignedIn_Implementation, passing
 *          Runtime->DefaultNotificationChannel as the SocketName so the subscription rides on the channel BeamRuntime
 *          opens for every signed-in player. UBeamInventorySubsystem::OnUserSignedIn_Implementation is the canonical
 *          example — it subscribes to "inventory.refresh" and re-fetches the inventory when the notification fires.
 *
 *          Don't forget to mirror the unsubscribe in OnUserSignedOut_Implementation if you'll re-subscribe on the
 *          next sign-in (otherwise the slot's socket gets closed and your handle becomes stale anyway, but explicit
 *          cleanup keeps the bookkeeping tight).
 *
 * --------------------------------------------------------------------------------------------------------------------
 * Notes
 * --------------------------------------------------------------------------------------------------------------------
 *  - When in doubt: prefer UBeamRuntime::SubscribeToCustomNotification. It is the recommended entry point for nearly
 *    every "my microservice emits a notification, my client wants to react" scenario. The wrapper-subsystem path above
 *    is a Blueprint-and-reusability optimization, not a baseline requirement.
 *  - UBeamRuntime::SubscribeToCustomNotification is sugar over TrySubscribeForMessage that fills in the "open default
 *    notification channel" lookup for you. It accepts ANY callable shape — single-cast TDelegate, multicast
 *    TMulticastDelegate (uses .Broadcast), lambda, function pointer, etc. — see TrySubscribeForMessage below.
 *  - Verbose logging on category "LogBeamNotifications" traces every subscribe, dispatch, and message
 *    payload. Turn it on (e.g. via DefaultEngine.ini's [Core.Log] LogBeamNotifications=Verbose) when debugging.
 */
UCLASS(BlueprintType, NotBlueprintable)
class BEAMABLECORE_API UBeamNotifications : public UEngineSubsystem
{
	GENERATED_BODY()

	/**
	 * Trait — true iff `T` exposes `bool ExecuteIfBound(TArg)` callable on a const T. Used by TrySubscribeForMessage
	 * to dispatch to single-cast UE delegates (TDelegate / DECLARE_DELEGATE_*) along the "execute and warn if unbound" path.
	 * Default specialisation falls through to false_type; the partial specialisation below activates when the expression is well-formed.
	 */
	template <typename T, typename TArg, typename = void>
	struct THasExecuteIfBound : std::false_type {};

	template <typename T, typename TArg>
	struct THasExecuteIfBound<T, TArg, std::void_t<decltype(std::declval<const T&>().ExecuteIfBound(std::declval<TArg>()))>> : std::true_type {};

	/**
	 * Trait — true iff `T` exposes `Broadcast(TArg)` callable on a non-const T. Used by TrySubscribeForMessage to
	 * dispatch to multicast UE delegates (TMulticastDelegate / DECLARE_(DYNAMIC_)MULTICAST_DELEGATE_*).
	 * Non-const because TMulticastDelegate::Broadcast is non-const (the inner lambda that owns Handler is `mutable`).
	 */
	template <typename T, typename TArg, typename = void>
	struct THasBroadcast : std::false_type {};

	template <typename T, typename TArg>
	struct THasBroadcast<T, TArg, std::void_t<decltype(std::declval<T&>().Broadcast(std::declval<TArg>()))>> : std::true_type {};

	/**
	 * Two-level table of every open IWebSocket. Outer key is NamespacedSlot (PIE-namespaced user-slot id), inner key
	 * is the logical socket Id (e.g. UBeamRuntime::DefaultNotificationChannel). Owns the shared pointers — when an
	 * entry is removed and no one else holds a reference, the underlying socket is destroyed.
	 */
	TMap<FString, TMap<FName, TSharedPtr<IWebSocket>>> OpenSockets;

	/**
	 * Subset of OpenSockets that were opened during a PIE session. Used by ClearPIESockets to shut them down without
	 * touching long-lived editor-process sockets (e.g. the editor's own auth flow).
	 */
	TArray<FBeamWebSocketHandle> PlayModeHandles;

	/** One per-socket connection-lifecycle handler (Connected / ConnectionFailed / Closed). Keyed by full socket handle. */
	TMap<FBeamWebSocketHandle, FOnNotificationEvent> ConnectionEventHandlers;

	/** Many-to-one: every per-context-key message subscriber registered against a socket. Multi-map so multiple subscribers can share a key. */
	TMultiMap<FBeamWebSocketHandle, FNotificationMessageEventHandler> MessageEventHandlers;

	/**
	 * Number of consecutive failed reconnect attempts per socket. Reset to 0 when a connection succeeds; surfaced in
	 * FNotificationConnectionFailed::RetryCount so callers can implement back-off.
	 */
	TMap<FBeamWebSocketHandle, int> RetryCount;

	/** Cached UBeamUserSlots dependency, resolved in Initialize. Used to namespace slots and read auth tokens. */
	UPROPERTY()
	UBeamUserSlots* UserSlots;

	/** Cached UBeamBackend dependency, resolved in Initialize. Used to read auth/scope headers and check PIE state. */
	UPROPERTY()
	UBeamBackend* Backend;

public:
	/** UEngineSubsystem hook — resolves the UBeamUserSlots and UBeamBackend dependencies. */
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;

	/** UEngineSubsystem hook — currently a no-op. Sockets are torn down through CloseSocketsForSlot / ClearPIESockets. */
	virtual void Deinitialize() override;

	/** Close code we emit when intentionally tearing a socket down because the owning user signed out. */
	const int UserSignOutCloseCode = 9999;

	/**
	 * Open a websocket bound to the given slot, IF that slot already has user data (i.e. is signed in).
	 * @param Slot                    The user the socket should belong to. The slot's auth token is sent as the websocket Authorization header.
	 * @param SocketName              Logical name of the socket (becomes FBeamWebSocketHandle::Id). Must be unique within the slot.
	 * @param Uri                     wss:// URL of the Beamable notification endpoint (typically the realm's notification gateway).
	 * @param ExtraHeaders            Additional HTTP headers to send during the websocket handshake. Authorization and X-KS-SCOPE are added automatically.
	 * @param ConnectionEventHandler  Receives Connected / ConnectionFailed / Closed events for this socket only.
	 * @param OutHandle               Filled with the constructed handle on success.
	 * @param ContextObject           Object whose world is used to PIE-namespace the slot. Pass `this` from a UObject method.
	 * @return                        false if the slot has no signed-in user yet — caller should sign the slot in first and retry.
	 */
	bool TryConnect(const FUserSlot& Slot, const FName& SocketName, const FString& Uri, const TMap<FString, FString>& ExtraHeaders, const FOnNotificationEvent& ConnectionEventHandler,
	                FBeamWebSocketHandle& OutHandle, UObject* ContextObject);

	/**
	 * Open a websocket using already-resolved user data. Called by TryConnect after it loads the FBeamRealmUser; exposed
	 * separately so callers that already hold the user data (e.g. during sign-in itself) can skip the redundant lookup.
	 * Same parameters as TryConnect, except UserData is supplied directly. Always succeeds — registers connect/error/close
	 * handlers on the underlying IWebSocket and triggers the initial Connect call on the websocket module.
	 */
	void Connect(const FUserSlot& Slot, const FBeamRealmUser& UserData, const FName& SocketName, const FString& Uri, const TMap<FString, FString>& ExtraHeaders,
	             const FOnNotificationEvent& ConnectionEventHandler, FBeamWebSocketHandle& OutHandle, UObject* ContextObject);

	/**
	 * Look up an existing handle by (Slot, SocketName) without opening anything. Useful when a subscriber wants to check
	 * whether a socket is already open — e.g. before attempting TrySubscribeForMessage.
	 * @return false if no such socket is open under that namespaced slot.
	 */
	bool TryGetHandle(const FUserSlot& Slot, const FName& SocketName, FBeamWebSocketHandle& OutHandle, UObject* ContextObject);

	/**
	 * Close every socket belonging to the given slot (typically called by BeamRuntime during sign-out) with
	 * UserSignOutCloseCode. After this returns the slot's entry in OpenSockets is empty but still present.
	 */
	void CloseSocketsForSlot(const FUserSlot& Slot, UObject* ContextObject);

	/**
	 * Walk PlayModeHandles and close any sockets whose namespace matches the given ContextObject's PIE world.
	 * Called when a PIE session ends so editor-only handles don't leak into the next session. Editor-only paths only.
	 */
	void ClearPIESockets(UObject* ContextObject);

	/**
	 * Register a handler for messages whose FNotificationMessage::Context equals ContextKey on the (Slot, SocketName) socket.
	 *
	 * @tparam THandler  Anything that can be invoked with a single TMessage argument:
	 *                    - Single-cast UE delegate (TDelegate / DECLARE_DELEGATE_*) — dispatched via ExecuteIfBound;
	 *                      the dispatcher ensure-fires if the delegate isn't bound at message time.
	 *                    - Multicast UE delegate (TMulticastDelegate / DECLARE_(DYNAMIC_)MULTICAST_DELEGATE_*) — dispatched via Broadcast.
	 *                    - Lambda, function pointer, or other callable — dispatched via UE's `Invoke()`.
	 *                   Trait-detected at compile time; no runtime check, no virtual dispatch.
	 * @tparam TMessage  Either a struct deriving from FBeamJsonSerializableUStruct (passed as a value type) or a UObject*
	 *                   whose class implements IBeamJsonSerializableUObject (passed as a pointer). Any other type fires a static_assert.
	 *
	 * @param Slot          User the socket belongs to.
	 * @param SocketName    Logical socket Id (typically UBeamRuntime::DefaultNotificationChannel).
	 * @param ContextKey    Routing key emitted by the server. Multiple handlers can share the same key — they are all called.
	 * @param Handler       Sink receiving a freshly-deserialized TMessage on every matching notification.
	 * @param OutHandle     Returns a delegate handle suitable for TryUnsubscribeFromMessage.
	 * @param ContextObject Used to PIE-namespace the slot lookup; pass `this`.
	 * @return              true on success. Returns false (and emits a Warning log) when there is no open socket for the slot/name —
	 *                      usually means the user isn't signed in yet.
	 */
	template <typename THandler, typename TMessage>
	bool TrySubscribeForMessage(const FUserSlot& Slot, const FName& SocketName, const FString& ContextKey, THandler Handler, FDelegateHandle& OutHandle, UObject* ContextObject)
	{
		auto NamespacedSlot = UBeamUserSlots::GetNamespacedSlotId(Slot, ContextObject);
		if (OpenSockets.Contains(NamespacedSlot))
		{
			if (const auto& UserSockets = OpenSockets.FindChecked(NamespacedSlot); UserSockets.Contains(SocketName))
			{
				static_assert(TIsDerivedFrom<TMessage, FBeamJsonSerializableUStruct>::Value || TIsDerivedFrom<typename TRemovePointer<TMessage>::Type, IBeamJsonSerializableUObject>::Value,
				              "TMessage must be a subclass of either UBeamJsonSerializableUObject* (subclass) OR FBeamJsonSerializableUStruct.");

				// Make sure the Message type is a FBeamJsonSerializable
				if constexpr (TIsDerivedFrom<TMessage, FBeamJsonSerializableUStruct>::Value)
				{
					constexpr const TCHAR* DispatchKind =
						THasExecuteIfBound<THandler, TMessage&>::value ? TEXT("ExecuteIfBound") :
						THasBroadcast<THandler, TMessage&>::value ? TEXT("Broadcast") :
						TEXT("Invoke");
					UE_LOG(LogBeamNotifications, Verbose, TEXT("Subscribing notification handler. SLOT=%s, SOCKET=%s, CONTEXT=%s, MSG_KIND=Struct, DISPATCH=%s"),
					       *Slot.Name, *SocketName.ToString(), *ContextKey, DispatchKind);

					const FOnNotificationEvent EventHandler = FOnNotificationEvent::CreateLambda([Slot, SocketName, ContextKey, Handler](FNotificationEvent Evt) mutable
					{
						ensureAlways(Evt.EventType == BEAM_Message);
						ensureAlways(Evt.MessageData.Context.Equals(ContextKey));

						UE_LOG(LogBeamNotifications, Verbose, TEXT("Notification received. SLOT=%s, SOCKET=%s, CONTEXT=%s, MSG_KIND=Struct, PAYLOAD=%s"),
						       *Slot.Name, *SocketName.ToString(), *ContextKey, *Evt.MessageData.MessageFull);

						TMessage MsgData;
						MsgData.OuterOwner = GetTransientPackage();
						MsgData.BeamDeserialize(Evt.MessageData.MessageFull);

						if constexpr (THasExecuteIfBound<THandler, TMessage&>::value)
						{
							const bool bDidRun = Handler.ExecuteIfBound(MsgData);
							ensureAlwaysMsgf(bDidRun, TEXT("The notification message handler was not bound. SLOT=%s, ID=%s, CONTEXT=%s"), *Slot.Name, *SocketName.ToString(), *ContextKey);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via ExecuteIfBound. SLOT=%s, CONTEXT=%s, BOUND=%s"),
							       *Slot.Name, *ContextKey, bDidRun ? TEXT("true") : TEXT("false"));
						}
						else if constexpr (THasBroadcast<THandler, TMessage&>::value)
						{
							Handler.Broadcast(MsgData);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via Broadcast (multicast delegate). SLOT=%s, CONTEXT=%s"), *Slot.Name, *ContextKey);
						}
						else
						{
							Invoke(Handler, MsgData);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via Invoke (callable). SLOT=%s, CONTEXT=%s"), *Slot.Name, *ContextKey);
						}
					});

					OutHandle = EventHandler.GetHandle();
					MessageEventHandlers.Add(FBeamWebSocketHandle(NamespacedSlot, SocketName, this), FNotificationMessageEventHandler{ContextKey, EventHandler});
					return true;
				}

				if constexpr (TIsDerivedFrom<typename TRemovePointer<TMessage>::Type, IBeamJsonSerializableUObject>::Value)
				{
					constexpr const TCHAR* DispatchKind =
						THasExecuteIfBound<THandler, TMessage>::value ? TEXT("ExecuteIfBound") :
						THasBroadcast<THandler, TMessage>::value ? TEXT("Broadcast") :
						TEXT("Invoke");
					UE_LOG(LogBeamNotifications, Verbose, TEXT("Subscribing notification handler. SLOT=%s, SOCKET=%s, CONTEXT=%s, MSG_KIND=UObject, DISPATCH=%s"),
					       *Slot.Name, *SocketName.ToString(), *ContextKey, DispatchKind);

					const FOnNotificationEvent EventHandler = FOnNotificationEvent::CreateLambda([Slot, SocketName, ContextKey, Handler](FNotificationEvent Evt) mutable
					{
						ensureAlways(Evt.EventType == BEAM_Message);
						ensureAlways(Evt.MessageData.Context.Equals(ContextKey));

						UE_LOG(LogBeamNotifications, Verbose, TEXT("Notification received. SLOT=%s, SOCKET=%s, CONTEXT=%s, MSG_KIND=UObject, PAYLOAD=%s"),
						       *Slot.Name, *SocketName.ToString(), *ContextKey, *Evt.MessageData.MessageFull);

						TMessage MsgData = NewObject<typename TRemovePointer<TMessage>::Type>();
						MsgData->OuterOwner = GetTransientPackage();
						MsgData->BeamDeserialize(Evt.MessageData.MessageFull);

						if constexpr (THasExecuteIfBound<THandler, TMessage>::value)
						{
							const bool bDidRun = Handler.ExecuteIfBound(MsgData);
							ensureAlwaysMsgf(bDidRun, TEXT("The notification message handler was not bound. SLOT=%s, ID=%s, CONTEXT=%s"), *Slot.Name, *SocketName.ToString(), *ContextKey);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via ExecuteIfBound. SLOT=%s, CONTEXT=%s, BOUND=%s"),
							       *Slot.Name, *ContextKey, bDidRun ? TEXT("true") : TEXT("false"));
						}
						else if constexpr (THasBroadcast<THandler, TMessage>::value)
						{
							Handler.Broadcast(MsgData);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via Broadcast (multicast delegate). SLOT=%s, CONTEXT=%s"), *Slot.Name, *ContextKey);
						}
						else
						{
							Invoke(Handler, MsgData);
							UE_LOG(LogBeamNotifications, Verbose, TEXT("Dispatched via Invoke (callable). SLOT=%s, CONTEXT=%s"), *Slot.Name, *ContextKey);
						}
					});

					OutHandle = EventHandler.GetHandle();
					MessageEventHandlers.Add(FBeamWebSocketHandle(NamespacedSlot, SocketName, this), FNotificationMessageEventHandler{ContextKey, EventHandler});
					return true;
				}
			}
			else
			{
				UE_LOG(LogBeamNotifications, Warning, TEXT("TrySubscribeForMessage: socket not open for slot. SLOT=%s, SOCKET=%s, CONTEXT=%s"),
				       *Slot.Name, *SocketName.ToString(), *ContextKey);
			}
		}
		else
		{
			UE_LOG(LogBeamNotifications, Warning, TEXT("TrySubscribeForMessage: no open sockets for slot. SLOT=%s, SOCKET=%s, CONTEXT=%s"),
			       *Slot.Name, *SocketName.ToString(), *ContextKey);
		}

		return false;
	}

	/**
	 * Reflection-driven sibling of TrySubscribeForMessage<TMessage> for USTRUCT messages whose type is only known at
	 * runtime. Used by the SubscribeToCustomNotification BP K2Node — direct C++ callers should prefer the template path.
	 *
	 * Per-message dispatch path: alloca a buffer the size of MessageStruct, InitializeStruct, dispatch through the
	 * FBeamJsonSerializableUStruct vtable to deserialize the JSON payload, build a transient
	 * FBeamCustomNotificationStructPayload, ExecuteIfBound on the BP dynamic delegate, DestroyStruct.
	 *
	 * @param MessageStruct  Must derive from FBeamJsonSerializableUStruct; Subscribe fails (Warning log) otherwise.
	 * @param Handler        BP dynamic delegate — sees the transient payload + key, never the deserialized struct directly.
	 * @return               false on null/invalid MessageStruct or when the (Slot, SocketName) socket is not open.
	 */
	bool TrySubscribeForMessage_DynamicStruct(const FUserSlot& Slot, const FName& SocketName, const FString& ContextKey,
	                                          UScriptStruct* MessageStruct, const FOnBeamCustomNotificationStructDynamic& Handler,
	                                          FDelegateHandle& OutHandle, UObject* ContextObject);

	/**
	 * Reflection-driven sibling of TrySubscribeForMessage<TMessage*> for UObject messages whose UClass is only known
	 * at runtime. Used by the SubscribeToCustomNotification BP K2Node.
	 *
	 * Per-message dispatch path: NewObject<MessageClass> in the transient package, dispatch through the
	 * IBeamJsonSerializableUObject interface to deserialize the JSON payload, ExecuteIfBound with the freshly-built object.
	 *
	 * @param MessageClass  Must implement IBeamJsonSerializableUObject; Subscribe fails (Warning log) otherwise.
	 * @return              false on null/invalid MessageClass or when the (Slot, SocketName) socket is not open.
	 */
	bool TrySubscribeForMessage_DynamicObject(const FUserSlot& Slot, const FName& SocketName, const FString& ContextKey,
	                                          UClass* MessageClass, const FOnBeamCustomNotificationObjectDynamic& Handler,
	                                          FDelegateHandle& OutHandle, UObject* ContextObject);

	/**
	 * Internal CustomThunk used by the SubscribeToCustomNotification K2Node's expansion. Copies the void*'d struct
	 * buffer referenced by Payload into the BP user's typed wildcard struct pin via UScriptStruct::CopyScriptStruct.
	 * Do not call from any BP graph except the auto-generated one inside the K2Node's expansion.
	 */
	UFUNCTION(BlueprintInternalUseOnly, CustomThunk, Category="Beam|Internal",
		meta=(CustomStructureParam="OutMessage", BlueprintInternalUseOnly="true"))
	static void K2_CopyNotificationStructPayload(const FBeamCustomNotificationStructPayload& Payload,
	                                             UPARAM(ref) int32& OutMessage);
	DECLARE_FUNCTION(execK2_CopyNotificationStructPayload);

	/**
	 * Remove every registered message handler from the (Slot, SocketName) socket regardless of context key.
	 * Connection-lifecycle handlers (the one passed to TryConnect/Connect) are NOT touched.
	 * @return true if the socket was open and its handlers were cleared, false if the socket wasn't found.
	 */
	bool TryUnsubscribeAllFromSlot(const FUserSlot& Slot, const FName& SocketName, UObject* ContextObject)
	{
		auto NamespacedSlot = UBeamUserSlots::GetNamespacedSlotId(Slot, ContextObject);
		if (OpenSockets.Contains(NamespacedSlot))
		{
			if (const auto& UserSockets = OpenSockets.FindChecked(NamespacedSlot); UserSockets.Contains(SocketName))
			{
				const FBeamWebSocketHandle Key(NamespacedSlot, SocketName, this);

				TArray<FNotificationMessageEventHandler> Handlers;
				MessageEventHandlers.MultiFind(Key, Handlers);
				for (const auto& NotificationMessageEventHandler : Handlers)
				{
					MessageEventHandlers.RemoveSingle(Key, NotificationMessageEventHandler);
				}
				return true;
			}
		}

		return false;
	}

	/**
	 * Remove every handler registered for `ContextKey` on the (Slot, SocketName) socket. Useful when a feature owns
	 * a key end-to-end and wants to nuke every listener at once (e.g. shutting the feature down).
	 * @return true if the socket was open, false if the socket wasn't found. Note: returns true even if no handlers matched the key.
	 */
	bool TryUnsubscribeAllFromMessage(const FUserSlot& Slot, const FName& SocketName, const FString& ContextKey, UObject* ContextObject)
	{
		auto NamespacedSlot = UBeamUserSlots::GetNamespacedSlotId(Slot, ContextObject);
		if (OpenSockets.Contains(NamespacedSlot))
		{
			if (const auto& UserSockets = OpenSockets.FindChecked(NamespacedSlot); UserSockets.Contains(SocketName))
			{
				const FBeamWebSocketHandle Key(NamespacedSlot, SocketName, this);

				TArray<FNotificationMessageEventHandler> Handlers;
				MessageEventHandlers.MultiFind(Key, Handlers);
				for (const auto& NotificationMessageEventHandler : Handlers)
				{
					if (NotificationMessageEventHandler.ContextKey.Equals(ContextKey))
						MessageEventHandlers.RemoveSingle(Key, NotificationMessageEventHandler);
				}

				return true;
			}
		}

		return false;
	}

	/**
	 * Remove a single handler — the one whose underlying delegate handle equals `Handle` — for `ContextKey` on (Slot, SocketName).
	 * This is the "scalpel" undo that pairs with the OutHandle returned by TrySubscribeForMessage and is what
	 * UBeamRuntime::UnsubscribeToCustomNotification ultimately calls.
	 * @return true if a matching handler was found and removed.
	 */
	bool TryUnsubscribeFromMessage(const FUserSlot& Slot, const FName& SocketName, const FString& ContextKey, const FDelegateHandle& Handle, UObject* ContextObject)
	{
		auto NamespacedSlot = UBeamUserSlots::GetNamespacedSlotId(Slot, ContextObject);
		if (OpenSockets.Contains(NamespacedSlot))
		{
			if (const auto& UserSockets = OpenSockets.FindChecked(NamespacedSlot); UserSockets.Contains(SocketName))
			{
				const FBeamWebSocketHandle Key(NamespacedSlot, SocketName, this);

				TArray<FNotificationMessageEventHandler> Handlers;
				MessageEventHandlers.MultiFind(Key, Handlers);
				for (const auto& NotificationMessageEventHandler : Handlers)
				{
					if (NotificationMessageEventHandler.ContextKey.Equals(ContextKey))
					{
						if (NotificationMessageEventHandler.Handler.GetHandle() == Handle)
						{
							MessageEventHandlers.RemoveSingle(Key, NotificationMessageEventHandler);
							return true;
						}
					}
				}
			}
		}
		return false;
	}

	/**
	 * If the socket identified by `Value` is currently in a disconnected state, re-issue Connect on it. No-op if the
	 * socket is unknown or already connected. Used by higher-level reconnect/back-off policies (see UBeamConnectivityManager).
	 * Existing message-handler registrations stay intact across the reconnect.
	 */
	void Reconnect(FBeamWebSocketHandle Value);
};
