// Auto-generated by BeamableCLI - DO NOT EDIT
// Source event: menu_navigation
// Schema version: 1.0.0

#pragma once

#include "CoreMinimal.h"
#include "Analytics/BeamAnalyticsEvent.h"
#include "Runtime/BeamValidators.h"

#include "MenuNavigationEvent.generated.h"

USTRUCT(BlueprintType, meta=(BeamAnalyticsEventBase))
struct FMenuNavigationEvent : public FBeamAnalyticsEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Analytics")
	FString Current;

	FMenuNavigationEvent() { Version = TEXT("1.0.0"); }

	virtual FString GetOpCode()    const override { return TEXT("g.core"); }
	virtual FString GetCategory()  const override { return TEXT("metagame"); }
	virtual FString GetEventName() const override { return TEXT("menu_navigation"); }

	virtual void Validate(FBeamValidationContext& OutContext) const override
	{
		FBeamValidationResult CurrentResult(TEXT("Current"));
		CurrentResult.SchemaPath = TEXT("properties.current");
		OutContext.RecordResult(CurrentResult);
	}

	virtual void BeamSerializeProperties(TUnrealJsonSerializer& Serializer) const override
	{
		FBeamAnalyticsEvent::BeamSerializeProperties(Serializer);
		Serializer->WriteValue(TEXT("Current"), Current);
	}

	virtual void BeamSerializeProperties(TUnrealPrettyJsonSerializer& Serializer) const override
	{
		FBeamAnalyticsEvent::BeamSerializeProperties(Serializer);
		Serializer->WriteValue(TEXT("Current"), Current);
	}

	virtual void BeamDeserializeProperties(const TSharedPtr<FJsonObject>& Bag) override
	{
		FBeamAnalyticsEvent::BeamDeserializeProperties(Bag);
		if (Bag->HasField(TEXT("Current")))
			Current = Bag->GetStringField(TEXT("Current"));
	}
};
