// Auto-generated by BeamableCLI - DO NOT EDIT
// Source event: take_hit
// Schema version: 1.0.0

#pragma once

#include "CoreMinimal.h"
#include "Analytics/BeamAnalyticsEvent.h"
#include "Runtime/BeamValidators.h"

#include "TakeHitEvent.generated.h"

USTRUCT(BlueprintType, meta=(BeamAnalyticsEventBase))
struct FTakeHitEvent : public FBeamAnalyticsEvent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Analytics")
	int32 LifeAmount = 0;

	FTakeHitEvent() { Version = TEXT("1.0.0"); }

	virtual FString GetOpCode()    const override { return TEXT("g.core"); }
	virtual FString GetCategory()  const override { return TEXT("gameplay"); }
	virtual FString GetEventName() const override { return TEXT("take_hit"); }

	virtual void Validate(FBeamValidationContext& OutContext) const override
	{
		FBeamValidationResult LifeAmountResult(TEXT("LifeAmount"));
		LifeAmountResult.SchemaPath = TEXT("properties.life_amount");
		UBeamValidators::ValidateMinimum(LifeAmount, 0, LifeAmountResult);
		UBeamValidators::ValidateMaximum(LifeAmount, 3, LifeAmountResult);
		OutContext.RecordResult(LifeAmountResult);
	}

	virtual void BeamSerializeProperties(TUnrealJsonSerializer& Serializer) const override
	{
		FBeamAnalyticsEvent::BeamSerializeProperties(Serializer);
		Serializer->WriteValue(TEXT("LifeAmount"), LifeAmount);
	}

	virtual void BeamSerializeProperties(TUnrealPrettyJsonSerializer& Serializer) const override
	{
		FBeamAnalyticsEvent::BeamSerializeProperties(Serializer);
		Serializer->WriteValue(TEXT("LifeAmount"), LifeAmount);
	}

	virtual void BeamDeserializeProperties(const TSharedPtr<FJsonObject>& Bag) override
	{
		FBeamAnalyticsEvent::BeamDeserializeProperties(Bag);
		if (Bag->HasField(TEXT("LifeAmount")))
			LifeAmount = Bag->GetIntegerField(TEXT("LifeAmount"));
	}
};
