using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Content;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Content;
using Beamable.Common.Inventory;
using Beamable.Content;
using Beamable.Server;
using Beamable.Server.Api.Inventory;
using UnityEngine.Serialization;
using IContentApi = Beamable.Common.Api.Content.IContentApi;
using IInventoryApi = Beamable.Api.Autogenerated.Inventory.IInventoryApi;

namespace Beamable.BeamFarmMs
{
    // ══════════════════════════════════════════════════════════════════════════
    // ENUMS
    // ══════════════════════════════════════════════════════════════════════════

    public enum BeamFarmPlantPropertyType
    {
        Corrosive,
        Mutagenic,
        Radioactive
    }

    public enum GroundItemType
    {
        /// <summary>Raw material currency (plant.raw.material.*) — granted via CurrencyChange.</summary>
        RawMaterial,
        /// <summary>Harvested plant item (itemplant.*) — granted via AddItem.</summary>
        PlantItem
    }

    public enum DeliveryComparison
    {
        GreaterThan,
        LowerThan
    }

    /// <summary>
    /// What kind of reward is granted when research completes.
    /// Must match EBeamResearchOutputType in FarmTypes.h.
    /// </summary>
    public enum EResearchOutputType
    {
        /// <summary>A plant_modifier.* currency spendable in the Mutation Lab.</summary>
        PlantModifier,
        /// <summary>Any inventory item (itemplant.*, etc.).</summary>
        Item,
        /// <summary>Any Beamable currency (plant_raw_material.*, etc.).</summary>
        Currency,
    }

    // ══════════════════════════════════════════════════════════════════════════
    // PROPERTY KEY CONSTANTS
    // ══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Item property keys written to an item instance while it is under research.
    /// Clients check for StartedAt to determine if an item is in research.
    /// Must match GetResearch*Key() helpers on UBeamFarmSubsystem.
    /// </summary>
    public static class ResearchPropertyKeys
    {
        public const string StartedAt       = "research_started_at";
        public const string DurationSecs    = "research_duration_secs";
        public const string OutputContentId = "research_output_content_id";
        public const string OutputQuantity  = "research_output_quantity";
        public const string OutputType      = "research_output_type";
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS — FARMING SLOTS
    // ══════════════════════════════════════════════════════════════════════════

    [Serializable]
    public class SlotData
    {
        public long plantedAt;
        public string seedId;
        public string harvestId;
        public int growSecs;
    }

    [Serializable]
    public class SeedDataProperty
    {
        public string DisplayName;
        public string GrowingSprite;
        public float GrowTimeSeconds;
        public string HarvestItemContentId;
        public string SeedSprite;
    }

    [Serializable]
    public class SlotStateEntry
    {
        public string slotId;
        public string seedId;
        public string harvestId;
        public long   plantedAt;
        public int    growSecs;
    }

    [Serializable]
    public class GetSlotStatesResult
    {
        public bool   success;
        public List<SlotStateEntry> slots;
        public string message;
    }

    [Serializable]
    public class PlantResult
    {
        public bool success;

        /// <summary>
        /// Server-authoritative Unix timestamp (UTC seconds) at which planting was recorded.
        /// Store this on the Unreal side if you want to display a client-side grow timer.
        /// The authoritative check is done server-side in CollectHarvest.
        /// </summary>
        public long plantedAtUtcSeconds;

        public string message;
    }

    [Serializable]
    public class CollectResult
    {
        public bool success;

        /// <summary>Content ID of the harvest item that was granted to the player's inventory (itemplant.*).</summary>
        public string harvestedItemContentId;

        /// <summary>Human-readable result message, useful for debug logging in Blueprint.</summary>
        public string message;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS — GROUND COLLECTIBLES
    // ══════════════════════════════════════════════════════════════════════════

    [Serializable]
    public class GroundItemData
    {
        public string contentId;
        public int quantity;
        public string itemType; // "RawMaterial" | "PlantItem"
        public long spawnedAt;
        public float posX;
        public float posY;
        public float posZ;
        public string spawnerId;
    }

    [Serializable]
    public class GroundItemIndexEntry
    {
        public string groundItemId;
        public string spawnerId;
    }

    [Serializable]
    public class GroundItemEntry
    {
        public string groundItemId;
        public string contentId;
        public int quantity;
        public string itemType;
        public float posX;
        public float posY;
        public float posZ;
    }

    [Serializable]
    public class GetGroundItemsResult
    {
        public bool success;
        public List<GroundItemEntry> items;
        public string message;
    }

    [Serializable]
    public class RegisterGroundItemResult
    {
        public bool success;
        public string message;
    }

    [Serializable]
    public class CollectGroundItemResult
    {
        public bool success;

        /// <summary>Content ID that was granted to inventory.</summary>
        public string grantedContentId;

        /// <summary>How many units were granted.</summary>
        public int grantedQuantity;

        public string message;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS — DELIVERY
    // ══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// A single property rule an item must satisfy to fulfil a delivery order.
    /// Stored inside DeliveryOrderContent and returned to the client inside DeliveryOrderInfo.
    ///
    /// Rules:
    ///   comparison = "GreaterThan"  →  item property value  >  value
    ///   comparison = "LowerThan"    →  item property value  &lt;  value
    ///
    /// If the item is missing the property, its effective value is 0.
    /// </summary>
    [Serializable]
    public class DeliveryRequirement
    {
        /// <summary>
        /// Name of the plant property to check.
        /// Must match one of the BeamFarmPlantPropertyType enum names:
        /// "Corrosive", "Mutagenic", "Radioactive".
        /// </summary>
        [FormerlySerializedAs("PropertyName")] public string propertyName;

        /// <summary>"GreaterThan" or "LowerThan" — matches DeliveryComparison enum names.</summary>
        [FormerlySerializedAs("Comparison")] public string comparison;

        /// <summary>Threshold value for the comparison.</summary>
        [FormerlySerializedAs("Value")] public int value;
    }

    [Serializable]
    public class ActiveDeliveryOrder
    {
        /// <summary>Content ID of the delivery_order.* assigned to this player.</summary>
        public string orderId;

        /// <summary>Unix timestamp (UTC seconds) when this order was assigned.</summary>
        public long assignedAt;
    }

    /// <summary>Full order description returned to the Unreal client by GetDeliveryOrders.</summary>
    [Serializable]
    public class DeliveryOrderInfo
    {
        public string orderId;
        public string displayName;
        public string requiredItemContentId;
        public List<DeliveryRequirement> requirements;
        public string rewardCurrencyId;
        public int rewardAmount;
    }

    [Serializable]
    public class GetDeliveryOrdersResult
    {
        public bool success;
        public List<DeliveryOrderInfo> orders;
        public string message;
    }

    [Serializable]
    public class FillDeliveryOrdersResult
    {
        public bool success;
        public int ordersAdded;
        public int totalOrders;
        public string message;
    }

    [Serializable]
    public class DeliverOrderResult
    {
        public bool success;
        public string orderId;
        public string rewardCurrencyId;
        public int rewardAmount;
        public string message;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS — MODIFIERS
    // ══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// A single property change entry within a ModifierItemContent.
    /// PropertyName must match a BeamFarmPlantPropertyType enum name:
    ///   "Corrosive", "Mutagenic", "Radioactive"
    /// Delta may be positive (increase) or negative (decrease).
    /// The final property value is clamped to [0, 10]; a result of 0 removes the property.
    /// </summary>
    [Serializable]
    public class ModifierPropertyDelta
    {
        [JsonPropertyName("PropertyName")]
        public string PropertyName;

        /// <summary>Signed change to apply to the property. Positive = increase, negative = decrease.</summary>
        [JsonPropertyName("Delta")]
        public int Delta;
    }

    [Serializable]
    public class MutateWithModifiersResult
    {
        public bool success;

        /// <summary>Final properties of the modified plant item after all modifiers are applied.</summary>
        public Dictionary<string, string> newProperties;

        public string message;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS — RESEARCH
    // ══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Mirrors FBeamPlantData in BeamPlantData.h.
    /// Must be declared so Beamable can deserialize the nested PlantData object;
    /// the microservice itself only needs the research fields, but omitting this
    /// class causes the content parse to fail for the whole object.
    /// </summary>
    [Serializable]
    public class PlantData
    {
        public string DisplayName          = string.Empty;
        public string ReadyToHarvestSprite = string.Empty;
    }

    [Serializable]
    public class StartResearchResult
    {
        public bool   success;

        /// <summary>Server UTC timestamp (seconds) at which research started.</summary>
        public long   startedAtUtcSeconds;

        /// <summary>How many research_points were deducted.</summary>
        public int    pointsSpent;

        public string message;
    }

    [Serializable]
    public class CollectResearchResult
    {
        public bool   success;

        /// <summary>Content ID of the reward granted to the player.</summary>
        public string outputContentId;

        /// <summary>How many units were granted.</summary>
        public int    outputQuantity;

        /// <summary>Serialized ResearchOutputType name: "PlantModifier", "Item", or "Currency".</summary>
        public string outputType;

        public string message;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // CONTENT TYPES
    // ══════════════════════════════════════════════════════════════════════════

    [System.Serializable]
    public class BeamSeedData
    {
        /// <summary>Display name shown in UI (e.g., "Wheat Seed", "Corn Seed")</summary>
        [JsonPropertyName("DisplayName")]
        public string DisplayName;

        /// <summary>Time in seconds for the seed to grow from planting to harvest</summary>
        [JsonPropertyName("GrowTimeSeconds")]
        public float GrowTimeSeconds = 30f;

        /// <summary>Soft path to the sprite shown in the player's inventory</summary>
        [JsonPropertyName("SeedSprite")]
        public string SeedSprite;

        /// <summary>Soft path to the sprite shown on the farm slot while the seed is growing</summary>
        [JsonPropertyName("GrowingSprite")]
        public string GrowingSprite;

        /// <summary>Content ID of the plant item the player receives when harvesting</summary>
        [JsonPropertyName("HarvestItemContentId")]
        public string HarvestItemContentId;
    }

    [Serializable]
    [ContentType("plant_raw_material")]
    public class SeedContent : CurrencyContent
    {
        public BeamSeedData SeedData;
    }

    /// <summary>
    /// Template for a single delivery order.
    /// Content type ID: "delivery_order"
    ///
    /// Example content IDs: "delivery_order.corrosive_demand", "delivery_order.high_energy_spore"
    ///
    /// Unreal integration:
    ///   Create matching content entries in the Beamable content browser.
    ///   The Unreal client receives the resolved data as FBeamDeliveryOrderInfo
    ///   via GetDeliveryOrders — no C++ content class is required on the client side.
    /// </summary>
    [Serializable]
    [ContentType("delivery_order")]
    public class DeliveryOrderContent : ContentObject
    {
        /// <summary>Human-readable name shown in the delivery panel UI.</summary>
        [FormerlySerializedAs("DisplayName")] public string displayName;

        /// <summary>
        /// Content ID of the plant item type the player must deliver (itemplant.*).
        /// Example: "itemplant.green_spore"
        /// </summary>
        [FormerlySerializedAs("RequiredItemContentId")] public string requiredItemContentId;

        /// <summary>
        /// Property rules the delivered item instance must all satisfy.
        /// An empty list means any instance of requiredItemContentId is accepted.
        /// </summary>
        [FormerlySerializedAs("Requirements")] public List<DeliveryRequirement> requirements;

        /// <summary>
        /// Beamable currency content ID granted as reward.
        /// Example: "currency_crystals"
        /// </summary>
        [FormerlySerializedAs("RewardCurrencyId")] public string rewardCurrencyId;

        /// <summary>Amount of rewardCurrencyId granted on successful delivery.</summary>
        [FormerlySerializedAs("RewardAmount")] public int rewardAmount;
    }

    /// <summary>
    /// Pool configuration — controls which orders can appear and how many run concurrently.
    /// Content type ID: "delivery_order_config"
    ///
    /// Publish a single entry with content ID "delivery_order_config.default".
    /// The server fetches this when filling player order slots.
    /// </summary>
    [Serializable]
    [ContentType("delivery_order_config")]
    public class DeliveryOrderPoolConfig : ContentObject
    {
        /// <summary>How many active delivery orders a player should always have available.</summary>
        [FormerlySerializedAs("MaxActiveOrders")] public int maxActiveOrders = 3;

        /// <summary>
        /// Full content IDs of all possible delivery orders to draw from.
        /// Example: ["delivery_order.corrosive_demand", "delivery_order.radioactive_harvest"]
        /// </summary>
        [FormerlySerializedAs("OrderPool")] public List<string> orderPool;
    }

    /// <summary>
    /// Content type for plant modifier items (plant_modifier.*).
    ///
    /// Each modifier item is a Beamable currency — players accumulate them and spend
    /// one unit per application in the mutation lab.
    ///
    /// Each modifier defines one or more property deltas applied atomically to a plant
    /// item instance via <see cref="BeamFarmMs.MutateWithModifiers"/>.
    ///
    /// Example content IDs:
    ///   plant_modifier.corrosive_boost      — adds +3 Corrosive
    ///   plant_modifier.mutagenic_inhibitor  — adds -2 Mutagenic
    ///   plant_modifier.radioactive_surge    — adds +5 Radioactive
    /// </summary>
    [Serializable]
    [ContentType("plant_modifier")]
    public class ModifierItemContent : CurrencyContent
    {
        /// <summary>Soft object path to the PaperSprite shown in inventory and mutation lab UI.</summary>
        [JsonPropertyName("ItemIcon")]
        public string ItemIcon;

        /// <summary>Human-readable name shown in inventory and mutation lab (e.g. "Corrosive Boost").</summary>
        [JsonPropertyName("DisplayName")]
        public string DisplayName;

        /// <summary>Flavour/tooltip text shown when inspecting this modifier in the mutation lab UI.</summary>
        [JsonPropertyName("Description")]
        public string Description;

        [JsonPropertyName("PropertyModifiers")]
        public List<ModifierPropertyDelta> PropertyModifiers;
    }

    /// <summary>
    /// Represents the research-relevant fields of an itemplant content object.
    /// Beamable deserializes only the declared fields; all other plant fields are ignored.
    ///
    /// These fields are authored in the Beamable content browser on the itemplant entry
    /// that corresponds to the item the player wants to research.
    /// </summary>
    [Serializable]
    [ContentType("itemplant")]
    public class PlantItemContent : ItemContent
    {
        public PlantData PlantData = new PlantData();

        /// <summary>How many research_points the player must spend to start research.</summary>
        public int ResearchPointsCost = 10;

        /// <summary>How long (seconds) the research takes. Server-authoritative.</summary>
        public float ResearchDurationSeconds = 60f;

        /// <summary>
        /// What kind of reward is granted when research completes.
        /// Serialized as the enum name: "PlantModifier", "Item", or "Currency".
        /// </summary>
        public EResearchOutputType ResearchOutputType = EResearchOutputType.PlantModifier;

        /// <summary>Content ID of the reward (plant_modifier.*, itemplant.*, plant_raw_material.*, etc.).</summary>
        public string ResearchOutputContentId;

        /// <summary>How many units of ResearchOutputContentId are granted on completion.</summary>
        public int ResearchOutputQuantity = 1;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // MICROSERVICE IMPLEMENTATION
    // ══════════════════════════════════════════════════════════════════════════

    public partial class BeamFarmMs
    {
        // ──────────────────────────────────────────────────────────────────────
        // CONSTANTS
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>Stat key for storing slot data as JSON.</summary>
        private static string SlotDataKey(string slotId) => $"farm_{slotId}_data";

        /// <summary>Stat key for storing a registered ground item record as JSON.</summary>
        private static string GroundItemKey(string groundItemId) => $"ground_item_{groundItemId}";

        /// <summary>
        /// Stat key that stores the player's active delivery order list as JSON.
        /// Value: JSON-serialised List&lt;ActiveDeliveryOrder&gt;
        /// </summary>
        private const string DeliveryActiveOrdersStatKey = "delivery_active_orders";

        /// <summary>
        /// Content ID of the singleton DeliveryOrderPoolConfig.
        /// Publish one entry in the Beamable content browser with this exact ID.
        /// </summary>
        private const string DeliveryPoolConfigContentId = "delivery_order_config.global";

        /// <summary>
        /// Content ID of the research_points currency players spend to start research.
        /// Create a matching "currency.research_points" entry in the Beamable content browser.
        /// </summary>
        private const string ResearchPointsCurrencyId = "currency.research_points";

        // ══════════════════════════════════════════════════════════════════════
        // PLANTING
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Called when the player plants a seed on a farm slot.
        ///
        /// Validates that the caller owns at least one unit of the seed currency and deducts it.
        /// Records the planting time and slot metadata as private game stats so that
        /// <see cref="CollectHarvest"/> can perform authoritative timing validation.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. Override UFarmingComponent::OnSeedConsumed in your Blueprint subclass.
        ///   2. Inside the event, call the auto-generated BeamFarmMsPlantSeed node.
        ///   3. Pass the following arguments:
        ///        seedContentId        → FarmingComponent.SelectedCropContentId
        ///        slotId               → the Slot actor's AFarmSlotActor::SlotId property
        ///   4. On success, store PlantResult.plantedAtUtcSeconds locally if you want
        ///      to display a client-side countdown timer.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsPlantSeed node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<PlantResult> PlantSeed(string seedContentId, string slotId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(seedContentId))
                return PlantFail("seedContentId must not be empty.");

            if (string.IsNullOrWhiteSpace(slotId))
                return PlantFail("slotId must not be empty.");

            // ── Seed ownership check ──────────────────────────────────────────
            var inventory = await Services.Inventory.GetCurrent("currency");

            var seedCurrency = inventory.currencies
                .FirstOrDefault(c => c.Key == seedContentId);

            if (seedCurrency.Value < 1)
                return PlantFail($"Player does not own any '{seedContentId}'.");

            var seedContent = await Services.Content.GetContent<SeedContent>(new ContentRef(typeof(SeedContent), seedContentId));

            // ── Extract SeedData from content ─────────────────────
            if (seedContent == null)
                return PlantFail($"No content found for seed '{seedContentId}'.");

            BeamSeedData seedData = seedContent.SeedData;
            try
            { ;
                if (seedData == null)
                    return PlantFail($"Failed to parse SeedData for seed '{seedContentId}'.");
            }
            catch (Exception ex)
            {
                return PlantFail($"Invalid SeedData format: {ex.Message}");
            }

            if (string.IsNullOrEmpty(seedData.HarvestItemContentId))
                return PlantFail($"SeedData missing HarvestItemContentId for seed '{seedContentId}'.");

            if (seedData.GrowTimeSeconds <= 0f)
                return PlantFail($"SeedData has invalid GrowTimeSeconds ({seedData.GrowTimeSeconds}) for seed '{seedContentId}'.");

            // ── Reject if slot already has an active planting ─────────────────
            string existingPlantJson = await GetSlotStat(SlotDataKey(slotId));
            if (!string.IsNullOrEmpty(existingPlantJson))
            {
                try
                {
                    var existingData = Newtonsoft.Json.JsonConvert.DeserializeObject<SlotData>(existingPlantJson);
                    if (existingData?.plantedAt > 0)
                        return PlantFail($"Slot '{slotId}' already has an active planting. Collect it first.");
                }
                catch
                {
                    // Corrupted data, allow overwriting
                }
            }

            // ── Consume the seed from inventory ───────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.CurrencyChange(seedContentId, -1);
            await Services.Inventory.Update(updateBuilder);

            // ── Record planting state as a single JSON stat ───────────────────
            long plantedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            int growSecs = Math.Max(1, (int)Math.Ceiling(seedData.GrowTimeSeconds));

            var slotData = new SlotData
            {
                plantedAt = plantedAt,
                seedId    = seedContentId,
                harvestId = seedData.HarvestItemContentId,
                growSecs  = growSecs
            };

            string slotDataJson = Newtonsoft.Json.JsonConvert.SerializeObject(slotData);
            await SetSlotStat(SlotDataKey(slotId), slotDataJson);

            return new PlantResult
            {
                success             = true,
                plantedAtUtcSeconds = plantedAt,
                message             = $"Planted '{seedContentId}' in slot '{slotId}'. Ready in {growSecs}s."
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // COLLECTING / HARVESTING
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Called when the player harvests a fully-grown crop from a farm slot.
        ///
        /// Reads the planting record written by <see cref="PlantSeed"/> and validates:
        ///   1. A planting record exists for the given slot.
        ///   2. The grow time has fully elapsed (server clock — cannot be spoofed by the client).
        ///
        /// On success:
        ///   • One harvest item (itemplant.*) is added to the player's Beamable inventory.
        ///   • The planting stats for the slot are cleared, making the slot available to plant again.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. Override UFarmingComponent::OnItemsHarvested in your Blueprint subclass.
        ///   2. Inside the event, call the auto-generated BeamFarmMsCollectHarvest node.
        ///   3. Pass the following arguments:
        ///        slotId → the Slot actor's AFarmSlotActor::SlotId property
        ///   4. On success, use CollectResult.harvestedItemContentId to update
        ///      any local inventory display (the Beamable SDK will also push an
        ///      inventory update event automatically).
        ///   5. On failure (e.g. crop not ready yet), show appropriate feedback to the player.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsCollectHarvest node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<CollectResult> CollectHarvest(string slotId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(slotId))
                return CollectFail("slotId must not be empty.");

            // ── Load planting data ────────────────────────────────────────────
            string slotDataJson = await GetSlotStat(SlotDataKey(slotId));

            if (string.IsNullOrEmpty(slotDataJson))
                return CollectFail($"No active planting found for slot '{slotId}'. Call PlantSeed first.");

            // ── Parse and validate the planting record ────────────────────────
            SlotData slotData;
            try
            {
                slotData = Newtonsoft.Json.JsonConvert.DeserializeObject<SlotData>(slotDataJson);
                if (slotData == null || slotData.plantedAt <= 0)
                    return CollectFail($"No active planting found for slot '{slotId}'. Call PlantSeed first.");
            }
            catch
            {
                return CollectFail("Corrupted planting data — please contact support.");
            }

            if (slotData.growSecs <= 0)
                return CollectFail("Corrupted grow time record — please contact support.");

            if (string.IsNullOrEmpty(slotData.harvestId))
                return CollectFail("No harvest item configured for this slot — please contact support.");

            // ── Timing check (server-authoritative) ───────────────────────────
            long readyAt = slotData.plantedAt + slotData.growSecs;
            long nowUtc  = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            if (nowUtc < readyAt)
            {
                long remaining = readyAt - nowUtc;
                return CollectFail($"Crop in slot '{slotId}' is not ready yet. {remaining}s remaining.");
            }

            // ── Grant harvest item to inventory ───────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();

            Dictionary<string, string> plantProperties = GeneratePlantProperties();

            updateBuilder.AddItem(slotData.harvestId, plantProperties);

            await Services.Inventory.Update(updateBuilder);

            // ── Clear planting data ───────────────────────────────────────────
            await SetSlotStat(SlotDataKey(slotId), string.Empty);

            return new CollectResult
            {
                success                = true,
                harvestedItemContentId = slotData.harvestId,
                message                = $"Harvested '{slotData.harvestId}' from slot '{slotId}'."
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // SLOT STATE QUERY
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Returns the active planting state for each supplied slotId that currently has a crop growing.
        /// Called on session restore to let the Unreal client reconstruct Growing/ReadyToHarvest slot visuals.
        /// Slots with no active planting are silently omitted from the result.
        /// </summary>
        [ClientCallable]
        public async Task<GetSlotStatesResult> GetSlotStates(List<string> slotIds)
        {
            if (slotIds == null || slotIds.Count == 0)
                return new GetSlotStatesResult { success = true, slots = new List<SlotStateEntry>(), message = "No slot IDs provided." };

            var results = new List<SlotStateEntry>();
            foreach (var slotId in slotIds)
            {
                if (string.IsNullOrWhiteSpace(slotId)) continue;

                string json = await GetSlotStat(SlotDataKey(slotId));
                if (string.IsNullOrEmpty(json)) continue;

                try
                {
                    var data = Newtonsoft.Json.JsonConvert.DeserializeObject<SlotData>(json);
                    if (data == null || data.plantedAt <= 0) continue;

                    results.Add(new SlotStateEntry
                    {
                        slotId    = slotId,
                        seedId    = data.seedId,
                        harvestId = data.harvestId,
                        plantedAt = data.plantedAt,
                        growSecs  = data.growSecs,
                    });
                }
                catch { }
            }

            return new GetSlotStatesResult
            {
                success = true,
                slots   = results,
                message = $"Found {results.Count} active slot(s).",
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // GROUND COLLECTIBLES
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Registers a collectible item when it appears in the world so the server can
        /// later validate that the player collected a legitimate item and prevent duplication.
        ///
        /// Call this from the Blueprint implementations of:
        ///   • UFarmCollectibleSpawner::OnCollectibleSpawned    (itemType = "RawMaterial")
        ///   • UFarmPlantCollectibleSpawner::OnPlantCollectibleSpawned (itemType = "PlantItem")
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. On spawn, generate a unique ID via the Blueprint MakeGuid node.
        ///      Store it in a BlueprintReadWrite property on the collectible actor.
        ///   2. Call BeamFarmMsRegisterGroundItem with:
        ///        groundItemId  → the generated GUID string
        ///        contentId     → MaterialData.ContentId  (seeds)  or  Plant.ContentId  (plants)
        ///        quantity      → QuantityPerCollectible from the spawner component
        ///        itemType      → "RawMaterial" for seeds | "PlantItem" for plants
        ///   3. On failure, optionally destroy the collectible actor to keep the world in sync.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsRegisterGroundItem node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<RegisterGroundItemResult> RegisterGroundItem(
            string groundItemId, string contentId, int quantity, string itemType,
            float posX, float posY, float posZ, string spawnerId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(groundItemId))
                return RegGroundFail("groundItemId must not be empty.");

            if (string.IsNullOrWhiteSpace(contentId))
                return RegGroundFail("contentId must not be empty.");

            if (quantity <= 0)
                return RegGroundFail($"quantity must be positive (got {quantity}).");

            if (itemType != nameof(GroundItemType.RawMaterial) && itemType != nameof(GroundItemType.PlantItem))
                return RegGroundFail($"itemType must be '{nameof(GroundItemType.RawMaterial)}' or '{nameof(GroundItemType.PlantItem)}' (got '{itemType}').");

            // ── Reject duplicate registrations ────────────────────────────────
            var groundItemKey = GroundItemKey(groundItemId);
            string existing = await GetSlotStat(groundItemKey);
            if (!string.IsNullOrEmpty(existing))
                return RegGroundFail($"Ground item '{groundItemId}' is already registered.");

            // ── Persist the ground item record ────────────────────────────────
            var data = new GroundItemData
            {
                contentId = contentId,
                quantity  = quantity,
                itemType  = itemType,
                spawnedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
                posX      = posX,
                posY      = posY,
                posZ      = posZ,
                spawnerId = spawnerId ?? string.Empty,
            };

            await SetSlotStat(groundItemKey,
                Newtonsoft.Json.JsonConvert.SerializeObject(data));

            // ── Maintain global index of active ground item IDs ───────────────
            const string indexKey = "ground_item_ids";
            string indexJson = await GetSlotStat(indexKey);
            var index = string.IsNullOrEmpty(indexJson)
                ? new List<GroundItemIndexEntry>()
                : Newtonsoft.Json.JsonConvert.DeserializeObject<List<GroundItemIndexEntry>>(indexJson)
                  ?? new List<GroundItemIndexEntry>();

            index.Add(new GroundItemIndexEntry { groundItemId = groundItemId, spawnerId = spawnerId ?? string.Empty });
            await SetSlotStat(indexKey, Newtonsoft.Json.JsonConvert.SerializeObject(index));

            return new RegisterGroundItemResult
            {
                success = true,
                message = $"Registered ground item '{groundItemId}' ({contentId} x{quantity}, type={itemType})."
            };
        }

        /// <summary>
        /// Validates and fulfils a ground item collection, granting the item to the
        /// player's Beamable inventory. Clears the registration record before granting
        /// to prevent double-collection.
        ///
        /// Call this from the Blueprint implementations of:
        ///   • UFarmCollectibleSpawner::OnCollectibleCollected
        ///   • UFarmPlantCollectibleSpawner::OnPlantCollectibleCollected
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. In OnCollectibleCollected / OnPlantCollectibleCollected, read the
        ///      groundItemId from the collectible actor's BlueprintReadWrite property.
        ///   2. Call BeamFarmMsCollectGroundItem with that groundItemId.
        ///   3. On success, use CollectGroundItemResult.grantedContentId and
        ///      grantedQuantity to update local UI. The Beamable SDK will also push
        ///      an inventory update event automatically.
        ///   4. On failure, log the message for debugging. Do NOT re-grant inventory
        ///      client-side on failure.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsCollectGroundItem node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<CollectGroundItemResult> CollectGroundItem(string groundItemId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(groundItemId))
                return CollectGroundFail("groundItemId must not be empty.");

            // ── Load registration record ──────────────────────────────────────
            string statKey = GroundItemKey(groundItemId);
            string json    = await GetSlotStat(statKey);

            if (string.IsNullOrEmpty(json))
                return CollectGroundFail($"No registered ground item found for '{groundItemId}'. Was it already collected?");

            // ── Parse record ──────────────────────────────────────────────────
            GroundItemData data;
            try
            {
                data = Newtonsoft.Json.JsonConvert.DeserializeObject<GroundItemData>(json);
                if (data == null || string.IsNullOrEmpty(data.contentId))
                    return CollectGroundFail("Corrupted ground item data — please contact support.");
            }
            catch
            {
                return CollectGroundFail("Corrupted ground item data — please contact support.");
            }

            // ── Clear first to prevent double-collection ──────────────────────
            await SetSlotStat(statKey, string.Empty);

            // ── Remove from global index ──────────────────────────────────────
            const string indexKey = "ground_item_ids";
            string indexJson = await GetSlotStat(indexKey);
            if (!string.IsNullOrEmpty(indexJson))
            {
                try
                {
                    var index = Newtonsoft.Json.JsonConvert.DeserializeObject<List<GroundItemIndexEntry>>(indexJson)
                                ?? new List<GroundItemIndexEntry>();
                    index.RemoveAll(e => e.groundItemId == groundItemId);
                    await SetSlotStat(indexKey, Newtonsoft.Json.JsonConvert.SerializeObject(index));
                }
                catch { }
            }

            // ── Grant to inventory ────────────────────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();

            if (data.itemType == nameof(GroundItemType.RawMaterial))
            {
                updateBuilder.CurrencyChange(data.contentId, data.quantity);
            }
            else
            {
                for (int i = 0; i < data.quantity; i++)
                    updateBuilder.AddItem(data.contentId, new Dictionary<string, string>());
            }

            await Services.Inventory.Update(updateBuilder);

            return new CollectGroundItemResult
            {
                success          = true,
                grantedContentId = data.contentId,
                grantedQuantity  = data.quantity,
                message          = $"Collected '{data.contentId}' x{data.quantity} from ground item '{groundItemId}'."
            };
        }

        /// <summary>
        /// Returns all ground items that were previously registered for a given spawner
        /// and have not yet been collected. Called on spawner startup to restore items
        /// that existed when the player last left the session.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///   Called automatically by UBeamFarmSubsystem::StartSpawner. You do not
        ///   need to call this manually.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<GetGroundItemsResult> GetGroundItems(string spawnerId)
        {
            const string indexKey = "ground_item_ids";
            string indexJson = await GetSlotStat(indexKey);

            if (string.IsNullOrEmpty(indexJson))
                return new GetGroundItemsResult { success = true, items = new List<GroundItemEntry>(), message = "No active ground items." };

            List<GroundItemIndexEntry> index;
            try
            {
                index = Newtonsoft.Json.JsonConvert.DeserializeObject<List<GroundItemIndexEntry>>(indexJson)
                        ?? new List<GroundItemIndexEntry>();
            }
            catch
            {
                return new GetGroundItemsResult { success = true, items = new List<GroundItemEntry>(), message = "Corrupted index — treating as empty." };
            }

            var matching = string.IsNullOrWhiteSpace(spawnerId)
                ? index
                : index.Where(e => e.spawnerId == spawnerId).ToList();

            var results = new List<GroundItemEntry>();
            foreach (var entry in matching)
            {
                string json = await GetSlotStat(GroundItemKey(entry.groundItemId));
                if (string.IsNullOrEmpty(json)) continue;

                try
                {
                    var data = Newtonsoft.Json.JsonConvert.DeserializeObject<GroundItemData>(json);
                    if (data == null) continue;

                    results.Add(new GroundItemEntry
                    {
                        groundItemId = entry.groundItemId,
                        contentId    = data.contentId,
                        quantity     = data.quantity,
                        itemType     = data.itemType,
                        posX         = data.posX,
                        posY         = data.posY,
                        posZ         = data.posZ,
                    });
                }
                catch { }
            }

            return new GetGroundItemsResult
            {
                success = true,
                items   = results,
                message = $"Found {results.Count} active ground item(s) for spawner '{spawnerId}'."
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // DELIVERY
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Returns the player's active delivery orders, auto-filling up to MaxActiveOrders
        /// if the player currently has fewer than the configured target.
        ///
        /// Call this when the delivery panel opens or when refreshing after a delivery.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///   1. Call UBeamFarmSubsystem::GetDeliveryOrders() from Blueprint.
        ///   2. Bind to UBeamFarmSubsystem::OnDeliveryOrdersReceived.
        ///   3. In the delegate, call UBeamFarmDeliveryWidget::HandleDeliveryOrdersReceived
        ///      (wired automatically by UBeamFarmDeliveryWidget::NativeConstruct).
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<GetDeliveryOrdersResult> GetDeliveryOrders()
        {
            // Always attempt to fill before returning so the player sees a full slate.
            await FillDeliveryOrdersInternal();

            List<ActiveDeliveryOrder> activeOrders = await LoadActiveOrders();
            if (activeOrders.Count == 0)
            {
                return new GetDeliveryOrdersResult
                {
                    success = true,
                    orders  = new List<DeliveryOrderInfo>(),
                    message = "No delivery orders available. Ensure 'delivery_order_config.default' is published."
                };
            }

            var orderInfos = new List<DeliveryOrderInfo>();
            foreach (var active in activeOrders)
            {
                try
                {
                    var content = await Services.Content.GetContent<DeliveryOrderContent>(
                        new ContentRef(typeof(DeliveryOrderContent), active.orderId));

                    if (content == null) continue;

                    orderInfos.Add(new DeliveryOrderInfo
                    {
                        orderId               = active.orderId,
                        displayName           = content.displayName ?? active.orderId,
                        requiredItemContentId = content.requiredItemContentId,
                        requirements          = content.requirements ?? new List<DeliveryRequirement>(),
                        rewardCurrencyId      = content.rewardCurrencyId,
                        rewardAmount          = content.rewardAmount
                    });
                }
                catch
                {
                    // Skip orders whose content has been unpublished; they'll be pruned on next fill.
                }
            }

            return new GetDeliveryOrdersResult
            {
                success = true,
                orders  = orderInfos,
                message = $"Loaded {orderInfos.Count} delivery order(s)."
            };
        }

        /// <summary>
        /// Ensures the player always has MaxActiveOrders delivery orders available.
        /// Picks random, non-duplicate orders from the pool configured in
        /// "delivery_order_config.default".
        ///
        /// This is also called automatically by GetDeliveryOrders and DeliverOrder,
        /// so most clients never need to call it explicitly.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///   Call UBeamFarmSubsystem::FillDeliveryOrders() on first login or after
        ///   a session gap to make sure the player's slate is fresh.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<FillDeliveryOrdersResult> FillDeliveryOrders()
        {
            int added = await FillDeliveryOrdersInternal();
            List<ActiveDeliveryOrder> after = await LoadActiveOrders();

            return new FillDeliveryOrdersResult
            {
                success     = true,
                ordersAdded = added,
                totalOrders = after.Count,
                message     = $"Added {added} order(s). Total active: {after.Count}."
            };
        }

        private async Task<int> FillDeliveryOrdersInternal()
        {
            // Load pool configuration
            DeliveryOrderPoolConfig poolConfig;
            try
            {
                poolConfig = await Services.Content.GetContent<DeliveryOrderPoolConfig>(
                    new ContentRef(typeof(DeliveryOrderPoolConfig), DeliveryPoolConfigContentId));
            }
            catch
            {
                return 0; // Config not published — nothing to fill
            }

            if (poolConfig?.orderPool == null || poolConfig.orderPool.Count == 0)
                return 0;

            List<ActiveDeliveryOrder> activeOrders = await LoadActiveOrders();
            int needed = poolConfig.maxActiveOrders - activeOrders.Count;
            if (needed <= 0) return 0;

            // Build the set of order IDs that are already active
            var activeIds = new HashSet<string>(activeOrders.Select(o => o.orderId));

            // Available candidates: pool entries not currently active
            var available = poolConfig.orderPool
                .Where(id => !string.IsNullOrWhiteSpace(id) && !activeIds.Contains(id))
                .ToList();

            if (available.Count == 0) return 0;

            // Fisher-Yates shuffle for unbiased random selection
            var rng = new Random();
            for (int i = available.Count - 1; i > 0; i--)
            {
                int j = rng.Next(i + 1);
                (available[i], available[j]) = (available[j], available[i]);
            }

            int toAdd = Math.Min(needed, available.Count);
            long now  = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            for (int i = 0; i < toAdd; i++)
            {
                activeOrders.Add(new ActiveDeliveryOrder
                {
                    orderId    = available[i],
                    assignedAt = now
                });
            }

            await SaveActiveOrders(activeOrders);
            return toAdd;
        }

        /// <summary>
        /// Validates that the given item instance satisfies the order's requirements,
        /// removes the item from the player's inventory, grants the reward currency, and
        /// removes the completed order from the active list (triggering an auto-refill).
        ///
        /// Validation steps (in order):
        ///   1. orderId is in the player's active order list.
        ///   2. itemInstanceId exists in the player's inventory.
        ///   3. Item's contentId matches the order's requiredItemContentId.
        ///   4. Each DeliveryRequirement passes (GreaterThan / LowerThan on item properties).
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///   1. In UBeamFarmDeliveryWidget::ConfirmDelivery, the widget calls
        ///      UBeamFarmSubsystem::DeliverOrder(OrderId, ItemInstanceId).
        ///   2. The subsystem fires OnDeliveryCompleted or OnDeliveryFailed.
        ///   3. The widget handles both via its delegate bindings in NativeConstruct.
        ///
        /// ItemInstanceId:
        ///   Beamable item instance IDs are int64 (long). Expose them from the
        ///   Beamable inventory response in Blueprint and pass to SelectItemForDelivery.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<DeliverOrderResult> DeliverOrder(string orderId, long itemInstanceId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(orderId))
                return DeliverFail(orderId, "orderId must not be empty.");

            // ── Verify order is active for this player ────────────────────────
            List<ActiveDeliveryOrder> activeOrders = await LoadActiveOrders();
            if (!activeOrders.Any(o => o.orderId == orderId))
                return DeliverFail(orderId, $"Order '{orderId}' is not in your active delivery orders.");

            // ── Load order content ────────────────────────────────────────────
            DeliveryOrderContent orderContent;
            try
            {
                orderContent = await Services.Content.GetContent<DeliveryOrderContent>(
                    new ContentRef(typeof(DeliveryOrderContent), orderId));
            }
            catch (Exception ex)
            {
                return DeliverFail(orderId, $"Failed to load order content '{orderId}': {ex.Message}");
            }

            if (orderContent == null)
                return DeliverFail(orderId, $"Order content '{orderId}' not found. Was it unpublished?");

            if (string.IsNullOrWhiteSpace(orderContent.requiredItemContentId))
                return DeliverFail(orderId, $"Order '{orderId}' has no requiredItemContentId configured.");

            if (string.IsNullOrWhiteSpace(orderContent.rewardCurrencyId))
                return DeliverFail(orderId, $"Order '{orderId}' has no rewardCurrencyId configured.");

            // ── Find the item instance in the player's inventory ──────────────
            // Items are grouped by contentId: Dictionary<string, List<ItemView>>
            var inventory = await Services.Inventory.GetCurrent("items");

            ItemView itemInstance = null;
            if (inventory?.items != null &&
                inventory.items.TryGetValue(orderContent.requiredItemContentId, out var itemGroup))
            {
                itemInstance = itemGroup?.FirstOrDefault(i => i.id == itemInstanceId);
            }

            if (itemInstance == null)
                return DeliverFail(orderId,
                    $"Item instance {itemInstanceId} of type '{orderContent.requiredItemContentId}' " +
                    "not found in your inventory. Make sure you selected the correct item.");

            // ── Validate property requirements ────────────────────────────────
            if (orderContent.requirements != null)
            {
                foreach (var req in orderContent.requirements)
                {
                    if (string.IsNullOrWhiteSpace(req.propertyName)) continue;

                    string propertyValue = "";
                    if (!itemInstance.properties.TryGetValue(req.propertyName, out propertyValue))
                    {
                        return DeliverFail(orderId,
                            $"Item property '{req.propertyName}' = property does exist to satisfy: " +
                            $"{req.comparison} {req.value}.");
                    }

                    int propValue = 0;
                    if (!string.IsNullOrEmpty(propertyValue))
                        int.TryParse(propertyValue, out propValue);

                    bool passes = req.comparison == nameof(DeliveryComparison.GreaterThan)
                        ? propValue > req.value
                        : propValue < req.value;

                    if (!passes)
                        return DeliverFail(orderId,
                            $"Item property '{req.propertyName}' = {propValue} does not satisfy: " +
                            $"{req.comparison} {req.value}.");
                }
            }

            // ── All checks passed — execute the delivery ──────────────────────
            // Delete item first, then grant currency in one atomic inventory update.
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.DeleteItem(itemInstance.contentId, itemInstanceId);
            updateBuilder.CurrencyChange(orderContent.rewardCurrencyId, orderContent.rewardAmount);
            await Services.Inventory.Update(updateBuilder);

            // ── Remove order from active list and refill ──────────────────────
            activeOrders.RemoveAll(o => o.orderId == orderId);
            await SaveActiveOrders(activeOrders);

            // Refill asynchronously so the player's slate stays at MaxActiveOrders.
            await FillDeliveryOrdersInternal();

            return new DeliverOrderResult
            {
                success          = true,
                orderId          = orderId,
                rewardCurrencyId = orderContent.rewardCurrencyId,
                rewardAmount     = orderContent.rewardAmount,
                message          = $"Delivered '{orderContent.requiredItemContentId}' for order '{orderId}'. " +
                                   $"Rewarded {orderContent.rewardAmount} of '{orderContent.rewardCurrencyId}'."
            };
        }

        private async Task<List<ActiveDeliveryOrder>> LoadActiveOrders()
        {
            string json = await GetSlotStat(DeliveryActiveOrdersStatKey);
            if (string.IsNullOrEmpty(json))
                return new List<ActiveDeliveryOrder>();

            try
            {
                return Newtonsoft.Json.JsonConvert.DeserializeObject<List<ActiveDeliveryOrder>>(json)
                    ?? new List<ActiveDeliveryOrder>();
            }
            catch
            {
                return new List<ActiveDeliveryOrder>();
            }
        }

        private async Task SaveActiveOrders(List<ActiveDeliveryOrder> orders)
        {
            string json = Newtonsoft.Json.JsonConvert.SerializeObject(orders);
            await SetSlotStat(DeliveryActiveOrdersStatKey, json);
        }

        // ══════════════════════════════════════════════════════════════════════
        // MODIFIERS (MUTATION LAB)
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Applies one or more modifier items to an existing plant item instance, changing
        /// its properties according to each modifier's defined deltas. Each modifier content
        /// ID in the list consumes one unit of that modifier currency — pass the same ID
        /// multiple times to apply it more than once.
        ///
        /// Property values are clamped to [0, 10]. A property reduced to 0 is removed.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. In your mutation lab widget or UBeamFarmSubsystem, call the auto-generated
        ///      BeamFarmMsMutateWithModifiers Blueprint node.
        ///   2. Pass:
        ///        plantItemContentId  → the itemplant.* content ID of the item to modify
        ///        plantItemInstanceId → the int64 instance ID from the inventory response
        ///        modifierContentIds  → array of plant_modifier.* content IDs to consume
        ///   3. On success, use MutateWithModifiersResult.newProperties to refresh your UI.
        ///      The Beamable SDK will also push an inventory update automatically.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsMutateWithModifiers node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<MutateWithModifiersResult> MutateWithModifiers(
            string plantItemContentId,
            long plantItemInstanceId,
            List<string> modifierContentIds)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(plantItemContentId))
                return ModifyFail("plantItemContentId must not be empty.");

            if (plantItemInstanceId <= 0)
                return ModifyFail("plantItemInstanceId must be a valid positive instance ID.");

            if (modifierContentIds == null || modifierContentIds.Count == 0)
                return ModifyFail("At least one modifier content ID must be provided.");

            foreach (var id in modifierContentIds)
            {
                if (string.IsNullOrWhiteSpace(id))
                    return ModifyFail("modifierContentIds must not contain empty entries.");
            }

            // ── Load player inventory (items + currencies in one call) ─────────
            var inventory = await Services.Inventory.GetCurrent("items,currency");

            // ── Find the target plant item instance ───────────────────────────
            ItemView plantItem = null;
            if (inventory?.items != null &&
                inventory.items.TryGetValue(plantItemContentId, out var itemGroup))
            {
                plantItem = itemGroup?.FirstOrDefault(i => i.id == plantItemInstanceId);
            }

            if (plantItem == null)
                return ModifyFail(
                    $"Plant item instance {plantItemInstanceId} (contentId='{plantItemContentId}') not found in inventory.");

            // ── Count how many of each modifier are required ───────────────────
            var requiredCounts = modifierContentIds
                .GroupBy(id => id)
                .ToDictionary(g => g.Key, g => g.Count());

            // ── Verify the player owns enough modifier currency ────────────────
            foreach (var (modId, needed) in requiredCounts)
            {
                long owned = inventory.currencies != null &&
                    inventory.currencies.TryGetValue(modId, out var ownedVal) ? ownedVal : 0;

                if (owned < needed)
                    return ModifyFail(
                        $"Insufficient '{modId}': need {needed}, have {owned}.");
            }

            // ── Load each unique modifier content definition ───────────────────
            var modifierContents = new Dictionary<string, ModifierItemContent>();
            foreach (var modId in requiredCounts.Keys)
            {
                ModifierItemContent modContent;
                try
                {
                    modContent = await Services.Content.GetContent<ModifierItemContent>(
                        new ContentRef(typeof(ModifierItemContent), modId));
                }
                catch (Exception ex)
                {
                    return ModifyFail($"Failed to load modifier content '{modId}': {ex.Message}");
                }

                if (modContent == null)
                    return ModifyFail($"Modifier content '{modId}' not found. Was it unpublished?");

                modifierContents[modId] = modContent;
            }

            // ── Apply modifier deltas to current item properties ──────────────
            var newProps = plantItem.properties != null
                ? new Dictionary<string, string>(plantItem.properties)
                : new Dictionary<string, string>();

            foreach (var modId in modifierContentIds)
            {
                var modContent = modifierContents[modId];
                if (modContent.PropertyModifiers == null) continue;

                foreach (var delta in modContent.PropertyModifiers)
                {
                    if (string.IsNullOrWhiteSpace(delta.PropertyName)) continue;

                    newProps.TryGetValue(delta.PropertyName, out var currentStr);
                    int current = int.TryParse(currentStr, out var parsed) ? parsed : 0;
                    int updated = Math.Max(0, Math.Min(10, current + delta.Delta));

                    if (updated == 0)
                        newProps.Remove(delta.PropertyName);
                    else
                        newProps[delta.PropertyName] = updated.ToString();
                }
            }

            // ── Build inventory update: delete plant, re-add with new props,
            //    and consume modifier currencies ─────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.DeleteItem(plantItemContentId, plantItemInstanceId);
            updateBuilder.AddItem(plantItemContentId, newProps);

            foreach (var (modId, count) in requiredCounts)
                updateBuilder.CurrencyChange(modId, -count);

            await Services.Inventory.Update(updateBuilder);

            return new MutateWithModifiersResult
            {
                success       = true,
                newProperties = newProps,
                message       = $"Applied {modifierContentIds.Count} modifier(s) to '{plantItemContentId}' instance {plantItemInstanceId}."
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // RESEARCH LAB
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Spends research_points and marks an item as under research by writing
        /// research state directly into the item's properties.
        ///
        /// Research parameters (cost, duration, output) are read directly from the
        /// itemplant content associated with itemContentId — no separate project content needed.
        ///
        /// Because Beamable item properties are updated by deleting the item and re-adding
        /// it with the merged property set, the item receives a new instance ID after this call.
        /// The client should refresh its inventory to pick up the updated item.
        ///
        /// Items in research carry the following properties (see ResearchPropertyKeys):
        ///   research_started_at          — Unix timestamp (seconds)
        ///   research_duration_secs       — duration in seconds
        ///   research_output_content_id   — reward content ID
        ///   research_output_quantity     — reward quantity
        ///   research_output_type         — "PlantModifier" | "Item" | "Currency"
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file.
        /// </summary>
        [ClientCallable]
        public async Task<StartResearchResult> StartResearch(long itemInstanceId, string itemContentId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (itemInstanceId <= 0)
                return ResearchStartFail("itemInstanceId must be a valid positive instance ID.");

            if (string.IsNullOrWhiteSpace(itemContentId))
                return ResearchStartFail("itemContentId must not be empty.");

            // ── Load inventory (items + currency in one call) ─────────────────
            var inventory = await Services.Inventory.GetCurrent("items,currency");

            // ── Find the item instance ────────────────────────────────────────
            ItemView itemInstance = null;
            if (inventory?.items != null &&
                inventory.items.TryGetValue(itemContentId, out var itemGroup))
            {
                itemInstance = itemGroup?.FirstOrDefault(i => i.id == itemInstanceId);
            }

            if (itemInstance == null)
                return ResearchStartFail(
                    $"Item instance {itemInstanceId} (contentId='{itemContentId}') not found in inventory.");

            // ── Reject if item is already under research ──────────────────────
            if (itemInstance.properties != null &&
                itemInstance.properties.ContainsKey(ResearchPropertyKeys.StartedAt))
            {
                return ResearchStartFail(
                    $"Item {itemInstanceId} is already under research. Collect it first.");
            }

            // ── Load and validate the plant content ───────────────────────────
            PlantItemContent plant;
            try
            {
                plant = await Services.Content.GetContent<PlantItemContent>(
                    new ContentRef(typeof(PlantItemContent), itemContentId));
            }
            catch (Exception ex)
            {
                return ResearchStartFail($"Failed to load plant content '{itemContentId}': {ex.Message}");
            }

            if (plant == null)
                return ResearchStartFail($"Plant content '{itemContentId}' not found. Was it unpublished?");

            if (string.IsNullOrWhiteSpace(plant.ResearchOutputContentId))
                return ResearchStartFail($"Plant '{itemContentId}' has no ResearchOutputContentId configured.");

            if (plant.ResearchDurationSeconds <= 0f)
                return ResearchStartFail($"Plant '{itemContentId}' has an invalid ResearchDurationSeconds.");

            if (plant.ResearchOutputQuantity <= 0)
                return ResearchStartFail($"Plant '{itemContentId}' has an invalid ResearchOutputQuantity.");

            int cost = Math.Max(0, plant.ResearchPointsCost);

            // ── Validate research_points balance ──────────────────────────────
            if (cost > 0)
            {
                long owned = inventory.currencies != null &&
                    inventory.currencies.TryGetValue(ResearchPointsCurrencyId, out var pts) ? pts : 0L;

                if (owned < cost)
                    return ResearchStartFail(
                        $"Not enough research points: need {cost}, have {owned}.");
            }

            // ── Build new item properties (preserve existing + add research state) ──
            long   startedAt   = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            int    durationSec = Math.Max(1, (int)Math.Ceiling(plant.ResearchDurationSeconds));
            string outputType  = string.Empty;

            var newProps = itemInstance.properties != null
                ? new Dictionary<string, string>(itemInstance.properties)
                : new Dictionary<string, string>();

            newProps[ResearchPropertyKeys.StartedAt]       = startedAt.ToString();
            newProps[ResearchPropertyKeys.DurationSecs]    = durationSec.ToString();
            newProps[ResearchPropertyKeys.OutputContentId] = plant.ResearchOutputContentId;
            newProps[ResearchPropertyKeys.OutputQuantity]  = plant.ResearchOutputQuantity.ToString();
            newProps[ResearchPropertyKeys.OutputType]      = outputType;

            // ── Apply inventory update atomically ─────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.UpdateItem(itemContentId, itemInstanceId, newProps);

            if (cost > 0)
                updateBuilder.CurrencyChange(ResearchPointsCurrencyId, -cost);

            await Services.Inventory.Update(updateBuilder);

            return new StartResearchResult
            {
                success             = true,
                startedAtUtcSeconds = startedAt,
                pointsSpent         = cost,
                message             = $"Research started on '{itemContentId}'. " +
                                      $"Ready in {durationSec}s. Spent {cost} research point(s).",
            };
        }

        /// <summary>
        /// Collects completed research: consumes the item (which holds the research state
        /// in its properties) and grants the configured output reward.
        ///
        /// Output dispatch by OutputType stored in item properties:
        ///   PlantModifier → CurrencyChange(outputContentId, outputQuantity)
        ///   Currency      → CurrencyChange(outputContentId, outputQuantity)
        ///   Item          → AddItem(outputContentId) × outputQuantity
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file.
        /// </summary>
        [ClientCallable]
        public async Task<CollectResearchResult> CollectResearch(long itemInstanceId, string itemContentId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (itemInstanceId <= 0)
                return ResearchCollectFail("itemInstanceId must be a valid positive instance ID.");

            if (string.IsNullOrWhiteSpace(itemContentId))
                return ResearchCollectFail("itemContentId must not be empty.");

            // ── Find the item instance ────────────────────────────────────────
            var inventory = await Services.Inventory.GetCurrent("items");

            ItemView itemInstance = null;
            if (inventory?.items != null &&
                inventory.items.TryGetValue(itemContentId, out var itemGroup))
            {
                itemInstance = itemGroup?.FirstOrDefault(i => i.id == itemInstanceId);
            }

            if (itemInstance == null)
                return ResearchCollectFail(
                    $"Item instance {itemInstanceId} (contentId='{itemContentId}') not found in inventory.");

            // ── Verify item is under research ─────────────────────────────────
            var props = itemInstance.properties ?? new Dictionary<string, string>();

            if (!props.TryGetValue(ResearchPropertyKeys.StartedAt, out var startedAtStr) ||
                !long.TryParse(startedAtStr, out long startedAt))
            {
                return ResearchCollectFail($"Item {itemInstanceId} is not under research.");
            }

            if (!props.TryGetValue(ResearchPropertyKeys.DurationSecs, out var durationStr) ||
                !int.TryParse(durationStr, out int durationSecs) || durationSecs <= 0)
            {
                return ResearchCollectFail("Corrupted research duration on item — please contact support.");
            }

            props.TryGetValue(ResearchPropertyKeys.OutputContentId, out string outputContentId);
            props.TryGetValue(ResearchPropertyKeys.OutputType, out string outputType);
            props.TryGetValue(ResearchPropertyKeys.OutputQuantity, out string outputQtyStr);

            if (string.IsNullOrEmpty(outputContentId))
                return ResearchCollectFail("No output configured for this research — please contact support.");

            int outputQuantity = int.TryParse(outputQtyStr, out var qty) ? Math.Max(1, qty) : 1;
            if (string.IsNullOrWhiteSpace(outputType))
                outputType = nameof(EResearchOutputType.PlantModifier);

            // ── Timing check (server-authoritative) ───────────────────────────
            long readyAt = startedAt + durationSecs;
            long nowUtc  = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            if (nowUtc < readyAt)
            {
                long remaining = readyAt - nowUtc;
                return ResearchCollectFail(
                    $"Research on item {itemInstanceId} is not complete yet. {remaining}s remaining.");
            }

            // ── Build update: consume item, grant output ───────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.DeleteItem(itemContentId, itemInstanceId);

            if (outputType == nameof(EResearchOutputType.Item))
            {
                for (int i = 0; i < outputQuantity; i++)
                    updateBuilder.AddItem(outputContentId, new Dictionary<string, string>());
            }
            else
            {
                // PlantModifier and Currency are both Beamable currencies.
                updateBuilder.CurrencyChange(outputContentId, outputQuantity);
            }

            await Services.Inventory.Update(updateBuilder);

            return new CollectResearchResult
            {
                success         = true,
                outputContentId = outputContentId,
                outputQuantity  = outputQuantity,
                outputType      = outputType,
                message         = $"Research collected for item {itemInstanceId}. " +
                                  $"Granted {outputQuantity}× '{outputContentId}'.",
            };
        }

        // ══════════════════════════════════════════════════════════════════════
        // STATS HELPERS
        // ══════════════════════════════════════════════════════════════════════

        private async Task<string> GetSlotStat(string key)
        {
            var stats = await Services.Stats.GetStats(StatsDomainType.Game, StatsAccessType.Private, Context.UserId);
            return stats != null && stats.TryGetValue(key, out var v) ? v : string.Empty;
        }

        private async Task SetSlotStat(string key, string value)
        {
            await Services.Stats.SetStat(StatsDomainType.Game, StatsAccessType.Private, Context.UserId, key, value);
        }

        // ══════════════════════════════════════════════════════════════════════
        // PROPERTY GENERATION
        // ══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Generates random properties for a harvested plant.
        /// Each property has a 20% chance to be assigned with a value between 1 and 10.
        /// </summary>
        private static Dictionary<string, string> GeneratePlantProperties()
        {
            var plantProperties = new Dictionary<string, string>();
            var random = new Random();

            foreach (var property in Enum.GetNames(typeof(BeamFarmPlantPropertyType)))
            {
                bool hasProperty = random.NextDouble() < 0.2;
                if (hasProperty)
                {
                    int value = random.Next(1, 11);
                    plantProperties[property] = value.ToString();
                }
            }

            return plantProperties;
        }

        // ══════════════════════════════════════════════════════════════════════
        // ERROR HELPERS
        // ══════════════════════════════════════════════════════════════════════

        private static PlantResult PlantFail(string message) =>
            new PlantResult { success = false, plantedAtUtcSeconds = 0L, message = message };

        private static CollectResult CollectFail(string message) =>
            new CollectResult { success = false, harvestedItemContentId = string.Empty, message = message };

        private static RegisterGroundItemResult RegGroundFail(string message) =>
            new RegisterGroundItemResult { success = false, message = message };

        private static CollectGroundItemResult CollectGroundFail(string message) =>
            new CollectGroundItemResult { success = false, grantedContentId = string.Empty, grantedQuantity = 0, message = message };

        private static GetSlotStatesResult GetSlotStatesFail(string message) =>
            new GetSlotStatesResult { success = false, slots = new List<SlotStateEntry>(), message = message };

        private static GetGroundItemsResult GetGroundItemsFail(string message) =>
            new GetGroundItemsResult { success = false, items = new List<GroundItemEntry>(), message = message };

        private static DeliverOrderResult DeliverFail(string orderId, string message) =>
            new DeliverOrderResult
            {
                success          = false,
                orderId          = orderId ?? string.Empty,
                rewardCurrencyId = string.Empty,
                rewardAmount     = 0,
                message          = message
            };

        private static GetDeliveryOrdersResult GetOrdersFail(string message) =>
            new GetDeliveryOrdersResult
            {
                success = false,
                orders  = new List<DeliveryOrderInfo>(),
                message = message
            };

        private static MutateWithModifiersResult ModifyFail(string message) =>
            new MutateWithModifiersResult
            {
                success       = false,
                newProperties = new Dictionary<string, string>(),
                message       = message
            };

        private static StartResearchResult ResearchStartFail(string message) =>
            new StartResearchResult
            {
                success             = false,
                startedAtUtcSeconds = 0L,
                pointsSpent         = 0,
                message             = message,
            };

        private static CollectResearchResult ResearchCollectFail(string message) =>
            new CollectResearchResult
            {
                success         = false,
                outputContentId = string.Empty,
                outputQuantity  = 0,
                outputType      = string.Empty,
                message         = message,
            };
    }
}
