using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Content;
using Beamable.Api.Autogenerated.Inventory;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Api.Stats;
using Beamable.Common.Content;
using Beamable.Common.Inventory;
using Beamable.Content;
using Beamable.Server;
using Beamable.Server.Api.Inventory;
using IContentApi = Beamable.Common.Api.Content.IContentApi;
using IInventoryApi = Beamable.Api.Autogenerated.Inventory.IInventoryApi;

namespace Beamable.BeamFarmMs
{
    // ══════════════════════════════════════════════════════════════════════════
    // ENUMS
    // ══════════════════════════════════════════════════════════════════════════

    public enum BeamFarmPlantPropertyType
    {
        Corrosive,
        Mutagenic,
        Radioactive
    }

    public enum GroundItemType
    {
        /// <summary>Raw material currency (plant.raw.material.*) — granted via CurrencyChange.</summary>
        RawMaterial,
        /// <summary>Harvested plant item (itemplant.*) — granted via AddItem.</summary>
        PlantItem
    }

    // ══════════════════════════════════════════════════════════════════════════
    // DATA MODELS
    // ══════════════════════════════════════════════════════════════════════════

    #region Slot Data Models

    [Serializable]
    public class SlotData
    {
        public long plantedAt;
        public string seedId;
        public string harvestId;
        public int growSecs;
    }

    [Serializable]
    public class SeedDataProperty
    {
        public string DisplayName { get; set; }
        public string GrowingSprite { get; set; }
        public float GrowTimeSeconds { get; set; }
        public string HarvestItemContentId { get; set; }
        public string SeedSprite { get; set; }
    }

    #endregion

    #region Plant Request/Response

    [Serializable]
    public class PlantResult
    {
        public bool success;

        /// <summary>
        /// Server-authoritative Unix timestamp (UTC seconds) at which planting was recorded.
        /// Store this on the Unreal side if you want to display a client-side grow timer.
        /// The authoritative check is done server-side in CollectHarvest.
        /// </summary>
        public long plantedAtUtcSeconds;

        public string message;
    }

    #endregion

    #region Collect Request/Response

    [Serializable]
    public class CollectResult
    {
        public bool success;

        /// <summary>Content ID of the harvest item that was granted to the player's inventory (itemplant.*).</summary>
        public string harvestedItemContentId;

        /// <summary>Human-readable result message, useful for debug logging in Blueprint.</summary>
        public string message;
    }

    #endregion

    #region Seed Content

    [System.Serializable]
    public class BeamSeedData
    {
        /// <summary>Display name shown in UI (e.g., "Wheat Seed", "Corn Seed")</summary>
        [JsonPropertyName("DisplayName")]
        public string DisplayName;

        /// <summary>Time in seconds for the seed to grow from planting to harvest</summary>
        [JsonPropertyName("GrowTimeSeconds")]
        public float GrowTimeSeconds = 30f;

        /// <summary>Soft path to the sprite shown in the player's inventory</summary>
        [JsonPropertyName("SeedSprite")] 
        public string SeedSprite;

        /// <summary>Soft path to the sprite shown on the farm slot while the seed is growing</summary>
        [JsonPropertyName("GrowingSprite")] 
        public string GrowingSprite;

        /// <summary>Content ID of the plant item the player receives when harvesting</summary>
        [JsonPropertyName("HarvestItemContentId")]
        public string HarvestItemContentId;
    }
    
    [Serializable]
    [ContentType("plant_raw_material")]
    public class SeedContent : CurrencyContent
    {
        public BeamSeedData SeedData;
    }

    #endregion

    #region Ground Collectible Models

    [Serializable]
    public class GroundItemData
    {
        public string contentId;
        public int quantity;
        public string itemType; // "RawMaterial" | "PlantItem"
        public long spawnedAt;
    }

    [Serializable]
    public class RegisterGroundItemResult
    {
        public bool success;
        public string message;
    }

    [Serializable]
    public class CollectGroundItemResult
    {
        public bool success;

        /// <summary>Content ID that was granted to inventory.</summary>
        public string grantedContentId;

        /// <summary>How many units were granted.</summary>
        public int grantedQuantity;

        public string message;
    }

    #endregion

    // ══════════════════════════════════════════════════════════════════════════
    // MICROSERVICE IMPLEMENTATION
    // ══════════════════════════════════════════════════════════════════════════

    public partial class BeamFarmMs
    {
        // ──────────────────────────────────────────────────────────────────────
        // CONSTANTS & HELPERS
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>Stat key for storing slot data as JSON.</summary>
        private static string SlotDataKey(string slotId) => $"farm_{slotId}_data";

        /// <summary>Stat key for storing a registered ground item record as JSON.</summary>
        private static string GroundItemKey(string groundItemId) => $"ground_item_{groundItemId}";

        // ──────────────────────────────────────────────────────────────────────
        // PLANTING
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Called when the player plants a seed on a farm slot.
        ///
        /// Validates that the caller owns at least one unit of the seed currency and deducts it.
        /// Records the planting time and slot metadata as private game stats so that
        /// <see cref="CollectHarvest"/> can perform authoritative timing validation.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. Override UFarmingComponent::OnSeedConsumed in your Blueprint subclass.
        ///   2. Inside the event, call the auto-generated BeamFarmMsPlantSeed node.
        ///   3. Pass the following arguments:
        ///        seedContentId        → FarmingComponent.SelectedCropContentId
        ///        slotId               → the Slot actor's AFarmSlotActor::SlotId property
        ///   4. On success, store PlantResult.plantedAtUtcSeconds locally if you want
        ///      to display a client-side countdown timer.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsPlantSeed node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<PlantResult> PlantSeed(string seedContentId, string slotId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(seedContentId))
                return PlantFail("seedContentId must not be empty.");

            if (string.IsNullOrWhiteSpace(slotId))
                return PlantFail("slotId must not be empty.");

            // ── Seed ownership check ──────────────────────────────────────────
            var inventory = await Services.Inventory.GetCurrent("currency");
          
            var seedCurrency = inventory.currencies
                .FirstOrDefault(c => c.Key == seedContentId);
            
            if (seedCurrency.Value < 1)
                return PlantFail($"Player does not own any '{seedContentId}'.");
        
            var seedContent = await Services.Content.GetContent<SeedContent>(new ContentRef(typeof(SeedContent), seedContentId));
      
            // ── Extract SeedData from content ─────────────────────
            if (seedContent == null)
                return PlantFail($"No content found for seed '{seedContentId}'.");
            
            BeamSeedData seedData = seedContent.SeedData;
            try
            { ;
                if (seedData == null)
                    return PlantFail($"Failed to parse SeedData for seed '{seedContentId}'.");
            }
            catch (Exception ex)
            {
                return PlantFail($"Invalid SeedData format: {ex.Message}");
            }

            if (string.IsNullOrEmpty(seedData.HarvestItemContentId))
                return PlantFail($"SeedData missing HarvestItemContentId for seed '{seedContentId}'.");

            if (seedData.GrowTimeSeconds <= 0f)
                return PlantFail($"SeedData has invalid GrowTimeSeconds ({seedData.GrowTimeSeconds}) for seed '{seedContentId}'.");

            // ── Reject if slot already has an active planting ─────────────────
            string existingPlantJson = await GetSlotStat(SlotDataKey(slotId));
            if (!string.IsNullOrEmpty(existingPlantJson))
            {
                try
                {
                    var existingData = Newtonsoft.Json.JsonConvert.DeserializeObject<SlotData>(existingPlantJson);
                    if (existingData?.plantedAt > 0)
                        return PlantFail($"Slot '{slotId}' already has an active planting. Collect it first.");
                }
                catch
                {
                    // Corrupted data, allow overwriting
                }
            }

            // ── Consume the seed from inventory ───────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            updateBuilder.CurrencyChange(seedContentId, -1);
            await Services.Inventory.Update(updateBuilder);

            // ── Record planting state as a single JSON stat ───────────────────
            long plantedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            int growSecs = Math.Max(1, (int)Math.Ceiling(seedData.GrowTimeSeconds));
            
            var slotData = new SlotData
            {
                plantedAt = plantedAt,
                seedId = seedContentId,
                harvestId = seedData.HarvestItemContentId,
                growSecs = growSecs
            };

            string slotDataJson = Newtonsoft.Json.JsonConvert.SerializeObject(slotData);
            await SetSlotStat(SlotDataKey(slotId), slotDataJson);

            return new PlantResult
            {
                success = true,
                plantedAtUtcSeconds = plantedAt,
                message = $"Planted '{seedContentId}' in slot '{slotId}'. Ready in {growSecs}s."
            };
        }

        // ──────────────────────────────────────────────────────────────────────
        // COLLECTING / HARVESTING
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Called when the player harvests a fully-grown crop from a farm slot.
        ///
        /// Reads the planting record written by <see cref="PlantSeed"/> and validates:
        ///   1. A planting record exists for the given slot.
        ///   2. The grow time has fully elapsed (server clock — cannot be spoofed by the client).
        ///
        /// On success:
        ///   • One harvest item (itemplant.*) is added to the player's Beamable inventory.
        ///   • The planting stats for the slot are cleared, making the slot available to plant again.
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. Override UFarmingComponent::OnItemsHarvested in your Blueprint subclass.
        ///   2. Inside the event, call the auto-generated BeamFarmMsCollectHarvest node.
        ///   3. Pass the following arguments:
        ///        slotId → the Slot actor's AFarmSlotActor::SlotId property
        ///   4. On success, use CollectResult.harvestedItemContentId to update
        ///      any local inventory display (the Beamable SDK will also push an
        ///      inventory update event automatically).
        ///   5. On failure (e.g. crop not ready yet), show appropriate feedback to the player.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsCollectHarvest node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<CollectResult> CollectHarvest(string slotId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(slotId))
                return CollectFail("slotId must not be empty.");

            // ── Load planting data ────────────────────────────────────────────
            string slotDataJson = await GetSlotStat(SlotDataKey(slotId));

            if (string.IsNullOrEmpty(slotDataJson))
                return CollectFail($"No active planting found for slot '{slotId}'. Call PlantSeed first.");

            // ── Parse and validate the planting record ────────────────────────
            SlotData slotData;
            try
            {
                slotData = Newtonsoft.Json.JsonConvert.DeserializeObject<SlotData>(slotDataJson);
                if (slotData == null || slotData.plantedAt <= 0)
                    return CollectFail($"No active planting found for slot '{slotId}'. Call PlantSeed first.");
            }
            catch
            {
                return CollectFail("Corrupted planting data — please contact support.");
            }

            if (slotData.growSecs <= 0)
                return CollectFail("Corrupted grow time record — please contact support.");

            if (string.IsNullOrEmpty(slotData.harvestId))
                return CollectFail("No harvest item configured for this slot — please contact support.");

            // ── Timing check (server-authoritative) ───────────────────────────
            long readyAt = slotData.plantedAt + slotData.growSecs;
            long nowUtc  = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            if (nowUtc < readyAt)
            {
                long remaining = readyAt - nowUtc;
                return CollectFail($"Crop in slot '{slotId}' is not ready yet. {remaining}s remaining.");
            }

            // ── Grant harvest item to inventory ───────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();
            
            Dictionary<string, string> plantProperties = GeneratePlantProperties();
            
            updateBuilder.AddItem(slotData.harvestId, plantProperties);
            
            await Services.Inventory.Update(updateBuilder);

            // ── Clear planting data ───────────────────────────────────────────
            await SetSlotStat(SlotDataKey(slotId), string.Empty);

            return new CollectResult
            {
                success = true,
                harvestedItemContentId = slotData.harvestId,
                message = $"Harvested '{slotData.harvestId}' from slot '{slotId}'."
            };
        }

        // ──────────────────────────────────────────────────────────────────────
        // GROUND COLLECTIBLES
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Registers a collectible item when it appears in the world so the server can
        /// later validate that the player collected a legitimate item and prevent duplication.
        ///
        /// Call this from the Blueprint implementations of:
        ///   • UFarmCollectibleSpawner::OnCollectibleSpawned    (itemType = "RawMaterial")
        ///   • UFarmPlantCollectibleSpawner::OnPlantCollectibleSpawned (itemType = "PlantItem")
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. On spawn, generate a unique ID via the Blueprint MakeGuid node.
        ///      Store it in a BlueprintReadWrite property on the collectible actor.
        ///   2. Call BeamFarmMsRegisterGroundItem with:
        ///        groundItemId  → the generated GUID string
        ///        contentId     → MaterialData.ContentId  (seeds)  or  Plant.ContentId  (plants)
        ///        quantity      → QuantityPerCollectible from the spawner component
        ///        itemType      → "RawMaterial" for seeds | "PlantItem" for plants
        ///   3. On failure, optionally destroy the collectible actor to keep the world in sync.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsRegisterGroundItem node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<RegisterGroundItemResult> RegisterGroundItem(
            string groundItemId, string contentId, int quantity, string itemType)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(groundItemId))
                return RegGroundFail("groundItemId must not be empty.");

            if (string.IsNullOrWhiteSpace(contentId))
                return RegGroundFail("contentId must not be empty.");

            if (quantity <= 0)
                return RegGroundFail($"quantity must be positive (got {quantity}).");

            if (itemType != nameof(GroundItemType.RawMaterial) && itemType != nameof(GroundItemType.PlantItem))
                return RegGroundFail($"itemType must be '{nameof(GroundItemType.RawMaterial)}' or '{nameof(GroundItemType.PlantItem)}' (got '{itemType}').");

            // ── Reject duplicate registrations ────────────────────────────────
            var groundItemKey = GroundItemKey(groundItemId);
            string existing = await GetSlotStat(groundItemKey);
            if (!string.IsNullOrEmpty(existing))
                return RegGroundFail($"Ground item '{groundItemId}' is already registered.");

            // ── Persist the ground item record ────────────────────────────────
            var data = new GroundItemData
            {
                contentId = contentId,
                quantity  = quantity,
                itemType  = itemType,
                spawnedAt = DateTimeOffset.UtcNow.ToUnixTimeSeconds()
            };

            await SetSlotStat(groundItemKey,
                Newtonsoft.Json.JsonConvert.SerializeObject(data));

            return new RegisterGroundItemResult
            {
                success = true,
                message = $"Registered ground item '{groundItemId}' ({contentId} x{quantity}, type={itemType})."
            };
        }

        /// <summary>
        /// Validates and fulfils a ground item collection, granting the item to the
        /// player's Beamable inventory. Clears the registration record before granting
        /// to prevent double-collection.
        ///
        /// Call this from the Blueprint implementations of:
        ///   • UFarmCollectibleSpawner::OnCollectibleCollected
        ///   • UFarmPlantCollectibleSpawner::OnPlantCollectibleCollected
        ///
        /// ═══ Unreal integration ═══════════════════════════════════════════
        ///
        ///   1. In OnCollectibleCollected / OnPlantCollectibleCollected, read the
        ///      groundItemId from the collectible actor's BlueprintReadWrite property.
        ///   2. Call BeamFarmMsCollectGroundItem with that groundItemId.
        ///   3. On success, use CollectGroundItemResult.grantedContentId and
        ///      grantedQuantity to update local UI. The Beamable SDK will also push
        ///      an inventory update event automatically.
        ///   4. On failure, log the message for debugging. Do NOT re-grant inventory
        ///      client-side on failure.
        ///
        /// NOTE: Run `dotnet beam generate` after modifying this file to regenerate
        /// the Blueprint-callable BeamFarmMsCollectGroundItem node.
        /// ═════════════════════════════════════════════════════════════════════
        /// </summary>
        [ClientCallable]
        public async Task<CollectGroundItemResult> CollectGroundItem(string groundItemId)
        {
            // ── Input validation ──────────────────────────────────────────────
            if (string.IsNullOrWhiteSpace(groundItemId))
                return CollectGroundFail("groundItemId must not be empty.");

            // ── Load registration record ──────────────────────────────────────
            string statKey = GroundItemKey(groundItemId);
            string json    = await GetSlotStat(statKey);

            if (string.IsNullOrEmpty(json))
                return CollectGroundFail($"No registered ground item found for '{groundItemId}'. Was it already collected?");

            // ── Parse record ──────────────────────────────────────────────────
            GroundItemData data;
            try
            {
                data = Newtonsoft.Json.JsonConvert.DeserializeObject<GroundItemData>(json);
                if (data == null || string.IsNullOrEmpty(data.contentId))
                    return CollectGroundFail("Corrupted ground item data — please contact support.");
            }
            catch
            {
                return CollectGroundFail("Corrupted ground item data — please contact support.");
            }

            // ── Clear first to prevent double-collection ──────────────────────
            await SetSlotStat(statKey, string.Empty);

            // ── Grant to inventory ────────────────────────────────────────────
            var updateBuilder = new InventoryUpdateBuilder();

            if (data.itemType == nameof(GroundItemType.RawMaterial))
            {
                updateBuilder.CurrencyChange(data.contentId, data.quantity);
            }
            else
            {
                for (int i = 0; i < data.quantity; i++)
                    updateBuilder.AddItem(data.contentId, GeneratePlantProperties());
            }

            await Services.Inventory.Update(updateBuilder);

            return new CollectGroundItemResult
            {
                success          = true,
                grantedContentId = data.contentId,
                grantedQuantity  = data.quantity,
                message          = $"Collected '{data.contentId}' x{data.quantity} from ground item '{groundItemId}'."
            };
        }

        // ──────────────────────────────────────────────────────────────────────
        // STATS HELPERS
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Reads a single private game stat for the current caller.
        ///
        /// NOTE: If SetStat / GetStat do not compile, your SDK may use a different interface.
        /// Common alternatives:
        ///   A) await Services.Stats.GetStats(StatsDomainType.Game, StatsAccessType.Private, Context.UserId)
        ///      → returns Dictionary‹string, string›; extract with TryGetValue.
        ///   B) await Services.Stats.SearchOne("game", "private", "player", Context.UserId.ToString())
        ///      → same dictionary shape.
        /// </summary>
        private async Task<string> GetSlotStat(string key)
        {
            var stats = await Services.Stats.GetStats(StatsDomainType.Game, StatsAccessType.Private, Context.UserId);
            return stats != null && stats.TryGetValue(key, out var v) ? v : string.Empty;
        }

        /// <summary>
        /// Writes a single private game stat for the current caller.
        /// See GetSlotStat for alternative patterns if this does not compile.
        /// </summary>
        private async Task SetSlotStat(string key, string value)
        {
            await Services.Stats.SetStat(StatsDomainType.Game, StatsAccessType.Private, Context.UserId, key, value);
        }

        // ──────────────────────────────────────────────────────────────────────
        // PROPERTY GENERATION HELPERS
        // ──────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates random properties for a harvested plant.
        /// Each property has a 20% chance to be assigned with a value between 1 and 10.
        /// </summary>
        private static Dictionary<string, string> GeneratePlantProperties()
        {
            var plantProperties = new Dictionary<string, string>();
            var random = new Random();
            
            foreach (var property in Enum.GetNames(typeof(BeamFarmPlantPropertyType)))
            {
                // create a chance for the plant to have each property, e.g. 20% chance for each
                bool hasProperty = random.NextDouble() < 0.2;
                if (hasProperty)
                {
                    // add a value between 1 and 10 for this property
                    int value = random.Next(1, 11);
                    plantProperties[property] = value.ToString();
                }
            }
            
            return plantProperties;
        }

        // ──────────────────────────────────────────────────────────────────────
        // ERROR HELPERS
        // ──────────────────────────────────────────────────────────────────────

        private static PlantResult PlantFail(string message) =>
            new PlantResult { success = false, plantedAtUtcSeconds = 0L, message = message };

        private static CollectResult CollectFail(string message) =>
            new CollectResult { success = false, harvestedItemContentId = string.Empty, message = message };

        private static RegisterGroundItemResult RegGroundFail(string message) =>
            new RegisterGroundItemResult { success = false, message = message };

        private static CollectGroundItemResult CollectGroundFail(string message) =>
            new CollectGroundItemResult { success = false, grantedContentId = string.Empty, grantedQuantity = 0, message = message };
    }
}
