site_name: Unreal SDK
site_url: https://beamable.github.io/UnrealSDK/
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/beamable-badge.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue

repo_url: https://github.com/Beamable/UnrealSDK
repo_name: Beamable/UnrealSDK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ¶

plugins:
   - glightbox
   - search
   - autorefs

nav:
  - Concepts:
      - Runtime Concepts: 'concepts/runtime-concepts.md'
      - Operations & Waits: 'concepts/operations-and-waits.md'
      - Microservices: 'concepts/microservices.md'
      - Dedicated Servers: 'concepts/dedicated-servers.md'
      - Online Subsystem: 'concepts/online-subsystem.md'
      - Federation: 'concepts/federation.md'
  - Managed Services:
      - Content: 'features/content.md'
      - Stats: 'features/stats.md'
      - Inventory: 'features/inventory.md'
      - Stores: 'features/stores.md'
  - How-To Guides: 
    - Getting Started: 'guides/intro.md'
    - Setting Up a Microservice: 'guides/intro-microservices.md'
    - Upgrades:
      - 1.0.0-PREVIEW to 1.0.0: 'guides/upgrades/upgrade-1.0.0-preview-to-1.0.0.md'
    - Federations:
      - IFederatedInventory: 'guides/federations/federated-inventory.md'
      - IFederatedGameServer: 'guides/federations/federated-game-server.md'
      - IFederatedLogin: 'guides/federations/federated-login.md'      
    - Unreal:
        - Linux Builds: 'guides/unreal/linux-builds.md'  
  - Samples: 
    - Intro: 'samples/intro.md'
    - Basic Samples:    
      - Discord Demo: 'samples/basic/discord-demo.md'
      - Steam Demo: 'samples/basic/steam-demo.md'      
    - Complex Samples:
      - LiveOps Demo: 'samples/complex/live-ops-demo.md'
      - Hathora Demo: 'samples/complex/hathora-demo.md'

copyright: |
  &copy; 2024 <a href="https://github.com/Beamable"  target="_blank" rel="noopener">Beamable</a>