site_name: Unreal SDK
site_url: https://beamable.github.io/UnrealSDK/
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/beamable-badge.png
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue

repo_url: https://github.com/Beamable/UnrealSDK
repo_name: Beamable/UnrealSDK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ¶

plugins:
   - glightbox
   - search
   - autorefs

nav:
  - Introduction: 'index.md'
  - Getting Started: 'getting-started.md'
  - What's New:
      - 1.1.0: 'whatsnew/1.1.0.md'
      - 1.0.0: 'whatsnew/1.0.0.md'
  - User Reference:
      - SDK Technical Overview: 'user-reference/overview.md'
      - Runtime Systems:
          - User Slots: 'user-reference/runtime-systems/user-slots.md'
          - Operations & Waits: 'user-reference/runtime-systems/operations-and-waits.md'
          - Connectivity Management: 'user-reference/runtime-systems/connectivity.md'
          - Lower Level SDK: 'user-reference/runtime-systems/lower-level.md'
      - Beamable Services:
          - Indentity: 'user-reference/beamable-services/identity.md'
          - Content: 'user-reference/beamable-services/content.md'
          - Stats: 'user-reference/beamable-services/stats.md'
          - Announcements: 'user-reference/beamable-services/announcements.md'
          - Inventory: 'user-reference/beamable-services/inventory.md'
          - Stores: 'user-reference/beamable-services/stores.md'
          - Lobbies: 'user-reference/beamable-services/lobbies.md'
          - Matchmaking: 'user-reference/beamable-services/matchmaking.md'
      - Microservices:
          - Overview: 'user-reference/microservices/microservices.md'
          - Setting Up Microservices: 'user-reference/microservices/setting-microservices.md'
      - Federation:
          - Overview: 'user-reference/federation/federation.md'
          - Federated Inventory: 'user-reference/federation/federated-inventory.md'
          - Federated Game Server: 'user-reference/federation/federated-game-server.md'
          - Federated Login: 'user-reference/federation/federated-login.md'
      - Servers and Builds:
          - Dedicated Servers: 'user-reference/servers-and-builds/dedicated-servers.md'
          - Linux Builds: 'user-reference/servers-and-builds/linux-builds.md'
      - Unreal Online Subsystems:
        - Overview: 'user-reference/online-subsystems/online-subsystem.md'
        - Online Subsystem Identity: 'user-reference/online-subsystems/online-subsystem-identity.md'

  - Samples: 
    - Setup Sample Projects: 'samples/intro.md'
    - Sample Projects:
      - LiveOps: 'samples/live-ops-demo.md'
      - Discord: 'samples/discord-demo.md'
      - Steam: 'samples/steam-demo.md'      
      - Hathora: 'samples/hathora-demo.md'

copyright: |
  &copy; 2024 <a href="https://github.com/Beamable"  target="_blank" rel="noopener">Beamable</a>
  
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js