// Copyright Epic Games, Inc. All Rights Reserved.

using UnrealBuildTool;
using System;
using System.IO;
using System.Linq;

public class BeamableUnrealIOSTarget : BeamableUnrealTarget
{
	public BeamableUnrealIOSTarget(TargetInfo Target) : base(Target)
	{
		// Set up a Global define so that we can cut code out of non-iOS builds
		GlobalDefinitions.Add("IS_IOS_DISTRIBUTION=1");
		Console.WriteLine($"[DEBUG] Constructor started - Platform: {Platform}, Type: {Type}");

		// iOS-specific post-build setup with Apple signing integration
		if (Type == TargetType.Game && Platform == UnrealTargetPlatform.IOS)
		{
			var iniPath = Path.Combine(ProjectFile.Directory.FullName, "Config", "DefaultEngine.ini");
			UpdateEngineIniForIOS(iniPath);
		}
	}

	/// <summary>
	/// Updates DefaultEngine.ini with iOS-specific configuration including:
	/// - OnlineSubsystemGoogle ClientId replacement with iOS-specific value
	/// - AdditionalPlistData auto-generation for CFBundleURLSchemes
	/// - Apple as default platform service
	/// </summary>
	/// <param name="iniPath">Path to DefaultEngine.ini file</param>
	private void UpdateEngineIniForIOS(string iniPath)
	{
		Console.WriteLine($"[DEBUG] INI Path: {iniPath}");
		
		if (!File.Exists(iniPath))
		{
			Console.WriteLine($"[WARNING] DefaultEngine.ini not found at {iniPath}");
			return;
		}

		var iniContents = File.ReadAllLines(iniPath).ToList();

		// Read Apple OAuth configuration for iOS
		var appleClientIdLine = iniContents.FirstOrDefault(c => c.Trim().Contains("ClientId-iOS"));
		
		if (appleClientIdLine == null)
		{
			Console.WriteLine($"[WARNING] ClientId-iOS not found in DefaultEngine.ini");
			return;
		}

		// Extract the iOS ClientId value
		var iosClientId = appleClientIdLine.Split('=')[1].Trim();
		Console.WriteLine($"[DEBUG] Found iOS ClientId: {iosClientId}");
		
		// Extract the reversed ClientId for CFBundleURLSchemes (e.g., com.googleusercontent.apps.881944816744-xxx)
		var parts = iosClientId.Split('.');
		Array.Reverse(parts);
		var reversedClientId = string.Join(".", parts);
		Console.WriteLine($"[DEBUG] Generated reversed ClientId for URL Scheme: {reversedClientId}");
		
		// Read additional Apple configuration
		var appleTeamIdLine = iniContents.FirstOrDefault(c => c.Trim().StartsWith("AppleTeamId"));
		var appleBundleIdLine = iniContents.FirstOrDefault(c => c.Trim().StartsWith("AppleBundleId"));

		if (appleTeamIdLine == null || appleBundleIdLine == null)
		{
			Console.WriteLine($"[WARNING] AppleTeamId or AppleBundleId not found in DefaultEngine.ini");
			return;
		}

		Console.WriteLine($"[DEBUG] Found Apple configuration - processing INI updates");

		// Process INI file updates
		ProcessIniSections(iniContents, iosClientId, reversedClientId);
		
		// Write updated ini file
		File.WriteAllLines(iniPath, iniContents);
		Console.WriteLine($"[DEBUG] Wrote the configs for Apple Sign In to DefaultEngine.ini with {iniContents.Count} lines.");
	}

	/// <summary>
	/// Processes and updates all relevant sections in the INI file
	/// </summary>
	private void ProcessIniSections(System.Collections.Generic.List<string> iniContents, string iosClientId, string reversedClientId)
	{
		// Update OnlineSubsystem section
		UpdateOrInsertIniValue(iniContents, "[OnlineSubsystem]", "DefaultPlatformService", "Apple");
		
		// Update OnlineSubsystemGoogle section with iOS ClientId
		UpdateOrInsertIniValue(iniContents, "[OnlineSubsystemGoogle]", "ClientId", iosClientId);
		
		// Update IOSRuntimeSettings section with AdditionalPlistData
		var additionalPlistData = $"<key>CFBundleURLTypes</key><array>    <dict>        <key>CFBundleURLSchemes</key>        <array>            <string>{reversedClientId}</string>        </array>    </dict></array>";
		UpdateOrInsertIniValue(iniContents, "[/Script/IOSRuntimeSettings.IOSRuntimeSettings]", "AdditionalPlistData", additionalPlistData, ";; AutoGenerated by the iOS Build Pipeline");
	}

	/// <summary>
	/// Updates or inserts a key-value pair in the specified INI section.
	/// If the key exists, it updates the value. If not, it inserts at the end of the section.
	/// </summary>
	/// <param name="iniContents">The INI file contents as a list of lines</param>
	/// <param name="sectionName">The section name (e.g., "[OnlineSubsystem]")</param>
	/// <param name="key">The key to update or insert (e.g., "DefaultPlatformService")</param>
	/// <param name="value">The value to set</param>
	/// <param name="comment">Optional comment to add above the key-value pair</param>
	private void UpdateOrInsertIniValue(System.Collections.Generic.List<string> iniContents, string sectionName, string key, string value, string comment = null)
	{
		int sectionIndex = -1;
		int keyIndex = -1;
		int sectionEndIndex = -1;
		bool inSection = false;

		// Find the section, check if key exists, and find section end
		for (int i = 0; i < iniContents.Count; i++)
		{
			if (iniContents[i].Trim() == sectionName)
			{
				sectionIndex = i;
				inSection = true;
				continue;
			}

			if (inSection)
			{
				// Check if we found the key
				if (iniContents[i].Trim().StartsWith($"{key}="))
				{
					keyIndex = i;
					inSection = false;
					break;
				}

				// If we hit another section, mark the end and stop looking
				if (iniContents[i].Trim().StartsWith("["))
				{
					sectionEndIndex = i;
					inSection = false;
					break;
				}
			}
		}

		// If we're still in section at end of file, mark end as last line
		if (inSection)
		{
			sectionEndIndex = iniContents.Count;
		}

		// If section doesn't exist, create it at the end
		if (sectionIndex == -1)
		{
			iniContents.Add("");
			iniContents.Add(sectionName);
			if (!string.IsNullOrEmpty(comment))
			{
				iniContents.Add(comment);
			}
			iniContents.Add($"{key}={value}");
			Console.WriteLine($"[DEBUG] Created section {sectionName} with {key}={value}");
			return;
		}

		// If key exists, update it
		if (keyIndex != -1)
		{
			// Check if there's an auto-generated comment above
			if (keyIndex > 0 && !string.IsNullOrEmpty(comment) && iniContents[keyIndex - 1].Trim() == comment)
			{
				// Just update the value
				iniContents[keyIndex] = $"{key}={value}";
			}
			else if (!string.IsNullOrEmpty(comment))
			{
				// Replace line above with comment and update the value
				iniContents[keyIndex - 1] = comment;
				iniContents[keyIndex] = $"{key}={value}";
			}
			else
			{
				// Just update the value
				iniContents[keyIndex] = $"{key}={value}";
			}
			Console.WriteLine($"[DEBUG] Updated {key} in {sectionName}");
		}
		else
		{
			// Key doesn't exist, insert at the end of the section (before next section or at file end)
			int insertIndex = sectionEndIndex;
			if (!string.IsNullOrEmpty(comment))
			{
				iniContents.Insert(insertIndex, comment);
				insertIndex++;
			}
			iniContents.Insert(insertIndex, $"{key}={value}");
			Console.WriteLine($"[DEBUG] Inserted {key}={value} at end of {sectionName}");
		}
	}
}
