name: Docs - Deploy

on:
  push:
    branches:
      - main
    paths:
      - Docs/**

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Run commands to print out more information about the runner
      - name: Print out Additional Runner info
        run: |
          curl https://api.ipify.org
          
      - uses: actions/checkout@v4
        with: 
            lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: bash docs_build.sh
      - run: mkdocs gh-deploy --force
        working-directory: ./Docs
        