name: Docs - Deploy

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: Commit hash to deploy
        default: main

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Run commands to print out more information about the runner
      - name: Print out Additional Runner info
        run: |
          curl https://api.ipify.org
          
      - uses: actions/checkout@v4
        with: 
            lfs: true   
            ref: ${{ inputs.commit }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: bash docs_build.sh
      - run: python -m mkdocs gh-deploy --force
        if: github.ref == 'refs/heads/main'
        working-directory: ./Docs
      - run: python -m mkdocs build
        if: github.ref != 'refs/heads/main'
        working-directory: ./Docs
        