#include "BeamLogging.h"

//General Log
DEFINE_LOG_CATEGORY(LogBeamBackend);
DEFINE_LOG_CATEGORY(LogBeamNotifications);
DEFINE_LOG_CATEGORY(LogBeamUserSlots);
DEFINE_LOG_CATEGORY(LogBeamRequestTracker);


DEFINE_LOG_CATEGORY(LogBeamEditor);
DEFINE_LOG_CATEGORY(LogBeamRuntime);

DEFINE_LOG_CATEGORY(LogBeamContent);
DEFINE_LOG_CATEGORY(LogBeamMicroservices);

DEFINE_LOG_CATEGORY(LogBeamStats);
DEFINE_LOG_CATEGORY(LogBeamLobby);
DEFINE_LOG_CATEGORY(LogBeamMatchmaking);
DEFINE_LOG_CATEGORY(LogBeamStore);
DEFINE_LOG_CATEGORY(LogBeamParty);
DEFINE_LOG_CATEGORY(LogBeamFriend);

DEFINE_LOG_CATEGORY(LogBeamCli);
